// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: scribe/v1/annotation.proto

package scribev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchAnnotationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanvasUri     string                 `protobuf:"bytes,1,opt,name=canvas_uri,json=canvasUri,proto3" json:"canvas_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAnnotationsRequest) Reset() {
	*x = SearchAnnotationsRequest{}
	mi := &file_scribe_v1_annotation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAnnotationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAnnotationsRequest) ProtoMessage() {}

func (x *SearchAnnotationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_annotation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAnnotationsRequest.ProtoReflect.Descriptor instead.
func (*SearchAnnotationsRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_annotation_proto_rawDescGZIP(), []int{0}
}

func (x *SearchAnnotationsRequest) GetCanvasUri() string {
	if x != nil {
		return x.CanvasUri
	}
	return ""
}

type SearchAnnotationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full IIIF AnnotationPage JSON, serialised as string for round-trip fidelity.
	AnnotationPageJson string `protobuf:"bytes,1,opt,name=annotation_page_json,json=annotationPageJson,proto3" json:"annotation_page_json,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SearchAnnotationsResponse) Reset() {
	*x = SearchAnnotationsResponse{}
	mi := &file_scribe_v1_annotation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAnnotationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAnnotationsResponse) ProtoMessage() {}

func (x *SearchAnnotationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_annotation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAnnotationsResponse.ProtoReflect.Descriptor instead.
func (*SearchAnnotationsResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_annotation_proto_rawDescGZIP(), []int{1}
}

func (x *SearchAnnotationsResponse) GetAnnotationPageJson() string {
	if x != nil {
		return x.AnnotationPageJson
	}
	return ""
}

type GetAnnotationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bare ID suffix (the part after /v1/annotations/3/item/)
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnnotationRequest) Reset() {
	*x = GetAnnotationRequest{}
	mi := &file_scribe_v1_annotation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnnotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnnotationRequest) ProtoMessage() {}

func (x *GetAnnotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_annotation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnnotationRequest.ProtoReflect.Descriptor instead.
func (*GetAnnotationRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_annotation_proto_rawDescGZIP(), []int{2}
}

func (x *GetAnnotationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAnnotationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AnnotationJson string                 `protobuf:"bytes,1,opt,name=annotation_json,json=annotationJson,proto3" json:"annotation_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAnnotationResponse) Reset() {
	*x = GetAnnotationResponse{}
	mi := &file_scribe_v1_annotation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnnotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnnotationResponse) ProtoMessage() {}

func (x *GetAnnotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_annotation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnnotationResponse.ProtoReflect.Descriptor instead.
func (*GetAnnotationResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_annotation_proto_rawDescGZIP(), []int{3}
}

func (x *GetAnnotationResponse) GetAnnotationJson() string {
	if x != nil {
		return x.AnnotationJson
	}
	return ""
}

type CreateAnnotationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AnnotationJson string                 `protobuf:"bytes,1,opt,name=annotation_json,json=annotationJson,proto3" json:"annotation_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAnnotationRequest) Reset() {
	*x = CreateAnnotationRequest{}
	mi := &file_scribe_v1_annotation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnnotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnnotationRequest) ProtoMessage() {}

func (x *CreateAnnotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_annotation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnnotationRequest.ProtoReflect.Descriptor instead.
func (*CreateAnnotationRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_annotation_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAnnotationRequest) GetAnnotationJson() string {
	if x != nil {
		return x.AnnotationJson
	}
	return ""
}

type CreateAnnotationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AnnotationJson string                 `protobuf:"bytes,1,opt,name=annotation_json,json=annotationJson,proto3" json:"annotation_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAnnotationResponse) Reset() {
	*x = CreateAnnotationResponse{}
	mi := &file_scribe_v1_annotation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnnotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnnotationResponse) ProtoMessage() {}

func (x *CreateAnnotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_annotation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnnotationResponse.ProtoReflect.Descriptor instead.
func (*CreateAnnotationResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_annotation_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAnnotationResponse) GetAnnotationJson() string {
	if x != nil {
		return x.AnnotationJson
	}
	return ""
}

type UpdateAnnotationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AnnotationJson string                 `protobuf:"bytes,1,opt,name=annotation_json,json=annotationJson,proto3" json:"annotation_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateAnnotationRequest) Reset() {
	*x = UpdateAnnotationRequest{}
	mi := &file_scribe_v1_annotation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnnotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnnotationRequest) ProtoMessage() {}

func (x *UpdateAnnotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_annotation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnnotationRequest.ProtoReflect.Descriptor instead.
func (*UpdateAnnotationRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_annotation_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAnnotationRequest) GetAnnotationJson() string {
	if x != nil {
		return x.AnnotationJson
	}
	return ""
}

type UpdateAnnotationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AnnotationJson string                 `protobuf:"bytes,1,opt,name=annotation_json,json=annotationJson,proto3" json:"annotation_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateAnnotationResponse) Reset() {
	*x = UpdateAnnotationResponse{}
	mi := &file_scribe_v1_annotation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnnotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnnotationResponse) ProtoMessage() {}

func (x *UpdateAnnotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_annotation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnnotationResponse.ProtoReflect.Descriptor instead.
func (*UpdateAnnotationResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_annotation_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAnnotationResponse) GetAnnotationJson() string {
	if x != nil {
		return x.AnnotationJson
	}
	return ""
}

type DeleteAnnotationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAnnotationRequest) Reset() {
	*x = DeleteAnnotationRequest{}
	mi := &file_scribe_v1_annotation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAnnotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnnotationRequest) ProtoMessage() {}

func (x *DeleteAnnotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_annotation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnnotationRequest.ProtoReflect.Descriptor instead.
func (*DeleteAnnotationRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_annotation_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAnnotationRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type DeleteAnnotationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAnnotationResponse) Reset() {
	*x = DeleteAnnotationResponse{}
	mi := &file_scribe_v1_annotation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAnnotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnnotationResponse) ProtoMessage() {}

func (x *DeleteAnnotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_annotation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnnotationResponse.ProtoReflect.Descriptor instead.
func (*DeleteAnnotationResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_annotation_proto_rawDescGZIP(), []int{9}
}

// EnrichAnnotationRequest sends a IIIF annotation (one line or an entire
// AnnotationPage) to Scribe's transcription service for improvement.
// The caller provides the raw JSON and specifies the scope.
type EnrichAnnotationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "line" = single Annotation JSON; "page" = full AnnotationPage JSON
	Scope          string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	AnnotationJson string `protobuf:"bytes,2,opt,name=annotation_json,json=annotationJson,proto3" json:"annotation_json,omitempty"`
	// Optional: override context used for transcription
	ContextId     uint64 `protobuf:"varint,3,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichAnnotationRequest) Reset() {
	*x = EnrichAnnotationRequest{}
	mi := &file_scribe_v1_annotation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichAnnotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichAnnotationRequest) ProtoMessage() {}

func (x *EnrichAnnotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_annotation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichAnnotationRequest.ProtoReflect.Descriptor instead.
func (*EnrichAnnotationRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_annotation_proto_rawDescGZIP(), []int{10}
}

func (x *EnrichAnnotationRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *EnrichAnnotationRequest) GetAnnotationJson() string {
	if x != nil {
		return x.AnnotationJson
	}
	return ""
}

func (x *EnrichAnnotationRequest) GetContextId() uint64 {
	if x != nil {
		return x.ContextId
	}
	return 0
}

type EnrichAnnotationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AnnotationJson string                 `protobuf:"bytes,1,opt,name=annotation_json,json=annotationJson,proto3" json:"annotation_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnrichAnnotationResponse) Reset() {
	*x = EnrichAnnotationResponse{}
	mi := &file_scribe_v1_annotation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichAnnotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichAnnotationResponse) ProtoMessage() {}

func (x *EnrichAnnotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_annotation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichAnnotationResponse.ProtoReflect.Descriptor instead.
func (*EnrichAnnotationResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_annotation_proto_rawDescGZIP(), []int{11}
}

func (x *EnrichAnnotationResponse) GetAnnotationJson() string {
	if x != nil {
		return x.AnnotationJson
	}
	return ""
}

var File_scribe_v1_annotation_proto protoreflect.FileDescriptor

const file_scribe_v1_annotation_proto_rawDesc = "" +
	"\n" +
	"\x1ascribe/v1/annotation.proto\x12\tscribe.v1\"9\n" +
	"\x18SearchAnnotationsRequest\x12\x1d\n" +
	"\n" +
	"canvas_uri\x18\x01 \x01(\tR\tcanvasUri\"M\n" +
	"\x19SearchAnnotationsResponse\x120\n" +
	"\x14annotation_page_json\x18\x01 \x01(\tR\x12annotationPageJson\"&\n" +
	"\x14GetAnnotationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x15GetAnnotationResponse\x12'\n" +
	"\x0fannotation_json\x18\x01 \x01(\tR\x0eannotationJson\"B\n" +
	"\x17CreateAnnotationRequest\x12'\n" +
	"\x0fannotation_json\x18\x01 \x01(\tR\x0eannotationJson\"C\n" +
	"\x18CreateAnnotationResponse\x12'\n" +
	"\x0fannotation_json\x18\x01 \x01(\tR\x0eannotationJson\"B\n" +
	"\x17UpdateAnnotationRequest\x12'\n" +
	"\x0fannotation_json\x18\x01 \x01(\tR\x0eannotationJson\"C\n" +
	"\x18UpdateAnnotationResponse\x12'\n" +
	"\x0fannotation_json\x18\x01 \x01(\tR\x0eannotationJson\"+\n" +
	"\x17DeleteAnnotationRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\"\x1a\n" +
	"\x18DeleteAnnotationResponse\"w\n" +
	"\x17EnrichAnnotationRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12'\n" +
	"\x0fannotation_json\x18\x02 \x01(\tR\x0eannotationJson\x12\x1d\n" +
	"\n" +
	"context_id\x18\x03 \x01(\x04R\tcontextId\"C\n" +
	"\x18EnrichAnnotationResponse\x12'\n" +
	"\x0fannotation_json\x18\x01 \x01(\tR\x0eannotationJson2\xbb\x04\n" +
	"\x11AnnotationService\x12^\n" +
	"\x11SearchAnnotations\x12#.scribe.v1.SearchAnnotationsRequest\x1a$.scribe.v1.SearchAnnotationsResponse\x12R\n" +
	"\rGetAnnotation\x12\x1f.scribe.v1.GetAnnotationRequest\x1a .scribe.v1.GetAnnotationResponse\x12[\n" +
	"\x10CreateAnnotation\x12\".scribe.v1.CreateAnnotationRequest\x1a#.scribe.v1.CreateAnnotationResponse\x12[\n" +
	"\x10UpdateAnnotation\x12\".scribe.v1.UpdateAnnotationRequest\x1a#.scribe.v1.UpdateAnnotationResponse\x12[\n" +
	"\x10DeleteAnnotation\x12\".scribe.v1.DeleteAnnotationRequest\x1a#.scribe.v1.DeleteAnnotationResponse\x12[\n" +
	"\x10EnrichAnnotation\x12\".scribe.v1.EnrichAnnotationRequest\x1a#.scribe.v1.EnrichAnnotationResponseB\xad\x01\n" +
	"\rcom.scribe.v1B\x0fAnnotationProtoP\x01ZFgithub.com/lehigh-university-libraries/scribe/proto/scribe/v1;scribev1\xa2\x02\x03SXX\xaa\x02\tScribe.V1\xca\x02\tScribe\\V1\xe2\x02\x15Scribe\\V1\\GPBMetadata\xea\x02\n" +
	"Scribe::V1b\x06proto3"

var (
	file_scribe_v1_annotation_proto_rawDescOnce sync.Once
	file_scribe_v1_annotation_proto_rawDescData []byte
)

func file_scribe_v1_annotation_proto_rawDescGZIP() []byte {
	file_scribe_v1_annotation_proto_rawDescOnce.Do(func() {
		file_scribe_v1_annotation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scribe_v1_annotation_proto_rawDesc), len(file_scribe_v1_annotation_proto_rawDesc)))
	})
	return file_scribe_v1_annotation_proto_rawDescData
}

var file_scribe_v1_annotation_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_scribe_v1_annotation_proto_goTypes = []any{
	(*SearchAnnotationsRequest)(nil),  // 0: scribe.v1.SearchAnnotationsRequest
	(*SearchAnnotationsResponse)(nil), // 1: scribe.v1.SearchAnnotationsResponse
	(*GetAnnotationRequest)(nil),      // 2: scribe.v1.GetAnnotationRequest
	(*GetAnnotationResponse)(nil),     // 3: scribe.v1.GetAnnotationResponse
	(*CreateAnnotationRequest)(nil),   // 4: scribe.v1.CreateAnnotationRequest
	(*CreateAnnotationResponse)(nil),  // 5: scribe.v1.CreateAnnotationResponse
	(*UpdateAnnotationRequest)(nil),   // 6: scribe.v1.UpdateAnnotationRequest
	(*UpdateAnnotationResponse)(nil),  // 7: scribe.v1.UpdateAnnotationResponse
	(*DeleteAnnotationRequest)(nil),   // 8: scribe.v1.DeleteAnnotationRequest
	(*DeleteAnnotationResponse)(nil),  // 9: scribe.v1.DeleteAnnotationResponse
	(*EnrichAnnotationRequest)(nil),   // 10: scribe.v1.EnrichAnnotationRequest
	(*EnrichAnnotationResponse)(nil),  // 11: scribe.v1.EnrichAnnotationResponse
}
var file_scribe_v1_annotation_proto_depIdxs = []int32{
	0,  // 0: scribe.v1.AnnotationService.SearchAnnotations:input_type -> scribe.v1.SearchAnnotationsRequest
	2,  // 1: scribe.v1.AnnotationService.GetAnnotation:input_type -> scribe.v1.GetAnnotationRequest
	4,  // 2: scribe.v1.AnnotationService.CreateAnnotation:input_type -> scribe.v1.CreateAnnotationRequest
	6,  // 3: scribe.v1.AnnotationService.UpdateAnnotation:input_type -> scribe.v1.UpdateAnnotationRequest
	8,  // 4: scribe.v1.AnnotationService.DeleteAnnotation:input_type -> scribe.v1.DeleteAnnotationRequest
	10, // 5: scribe.v1.AnnotationService.EnrichAnnotation:input_type -> scribe.v1.EnrichAnnotationRequest
	1,  // 6: scribe.v1.AnnotationService.SearchAnnotations:output_type -> scribe.v1.SearchAnnotationsResponse
	3,  // 7: scribe.v1.AnnotationService.GetAnnotation:output_type -> scribe.v1.GetAnnotationResponse
	5,  // 8: scribe.v1.AnnotationService.CreateAnnotation:output_type -> scribe.v1.CreateAnnotationResponse
	7,  // 9: scribe.v1.AnnotationService.UpdateAnnotation:output_type -> scribe.v1.UpdateAnnotationResponse
	9,  // 10: scribe.v1.AnnotationService.DeleteAnnotation:output_type -> scribe.v1.DeleteAnnotationResponse
	11, // 11: scribe.v1.AnnotationService.EnrichAnnotation:output_type -> scribe.v1.EnrichAnnotationResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_scribe_v1_annotation_proto_init() }
func file_scribe_v1_annotation_proto_init() {
	if File_scribe_v1_annotation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scribe_v1_annotation_proto_rawDesc), len(file_scribe_v1_annotation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scribe_v1_annotation_proto_goTypes,
		DependencyIndexes: file_scribe_v1_annotation_proto_depIdxs,
		MessageInfos:      file_scribe_v1_annotation_proto_msgTypes,
	}.Build()
	File_scribe_v1_annotation_proto = out.File
	file_scribe_v1_annotation_proto_goTypes = nil
	file_scribe_v1_annotation_proto_depIdxs = nil
}
