// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: scribe/v1/context.proto

package scribev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/lehigh-university-libraries/scribe/proto/scribe/v1/options/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ImagePreprocessor is a single image pre-processing step.
type ImagePreprocessor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type: resize | contrast | binarize | invert
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// JSON-encoded parameters, e.g. {"px":2000} for resize
	Params        string `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePreprocessor) Reset() {
	*x = ImagePreprocessor{}
	mi := &file_scribe_v1_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePreprocessor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePreprocessor) ProtoMessage() {}

func (x *ImagePreprocessor) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePreprocessor.ProtoReflect.Descriptor instead.
func (*ImagePreprocessor) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{0}
}

func (x *ImagePreprocessor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ImagePreprocessor) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

// Context bundles all processing parameters for a pipeline run.
type Context struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Creator user for workspace-owned contexts; 0 means system context.
	UserId      uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsDefault   bool   `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	// Segmentation model: "tesseract" | "scribe" | "kraken:<model-id>"
	SegmentationModel     string               `protobuf:"bytes,6,opt,name=segmentation_model,json=segmentationModel,proto3" json:"segmentation_model,omitempty"`
	ImagePreprocessors    []*ImagePreprocessor `protobuf:"bytes,7,rep,name=image_preprocessors,json=imagePreprocessors,proto3" json:"image_preprocessors,omitempty"`
	TranscriptionProvider string               `protobuf:"bytes,8,opt,name=transcription_provider,json=transcriptionProvider,proto3" json:"transcription_provider,omitempty"`
	TranscriptionModel    string               `protobuf:"bytes,9,opt,name=transcription_model,json=transcriptionModel,proto3" json:"transcription_model,omitempty"`
	TranscriptionBaseUrl  string               `protobuf:"bytes,15,opt,name=transcription_base_url,json=transcriptionBaseUrl,proto3" json:"transcription_base_url,omitempty"`
	TranscriptionAudience string               `protobuf:"bytes,16,opt,name=transcription_audience,json=transcriptionAudience,proto3" json:"transcription_audience,omitempty"`
	// -1 means "use provider default"
	Temperature         float64  `protobuf:"fixed64,10,opt,name=temperature,proto3" json:"temperature,omitempty"`
	SystemPrompt        string   `protobuf:"bytes,11,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	PostProcessingSteps []string `protobuf:"bytes,12,rep,name=post_processing_steps,json=postProcessingSteps,proto3" json:"post_processing_steps,omitempty"`
	CreatedAt           string   `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           string   `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_scribe_v1_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{1}
}

func (x *Context) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Context) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Context) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Context) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Context) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Context) GetSegmentationModel() string {
	if x != nil {
		return x.SegmentationModel
	}
	return ""
}

func (x *Context) GetImagePreprocessors() []*ImagePreprocessor {
	if x != nil {
		return x.ImagePreprocessors
	}
	return nil
}

func (x *Context) GetTranscriptionProvider() string {
	if x != nil {
		return x.TranscriptionProvider
	}
	return ""
}

func (x *Context) GetTranscriptionModel() string {
	if x != nil {
		return x.TranscriptionModel
	}
	return ""
}

func (x *Context) GetTranscriptionBaseUrl() string {
	if x != nil {
		return x.TranscriptionBaseUrl
	}
	return ""
}

func (x *Context) GetTranscriptionAudience() string {
	if x != nil {
		return x.TranscriptionAudience
	}
	return ""
}

func (x *Context) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *Context) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *Context) GetPostProcessingSteps() []string {
	if x != nil {
		return x.PostProcessingSteps
	}
	return nil
}

func (x *Context) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Context) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// RuleCondition is a single AND-clause predicate.
type RuleCondition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Field string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// eq | neq | contains | starts_with | ends_with
	Operator      string `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Value         string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleCondition) Reset() {
	*x = RuleCondition{}
	mi := &file_scribe_v1_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleCondition) ProtoMessage() {}

func (x *RuleCondition) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleCondition.ProtoReflect.Descriptor instead.
func (*RuleCondition) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{2}
}

func (x *RuleCondition) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *RuleCondition) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *RuleCondition) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ContextSelectionRule maps a set of AND conditions to a context.
// The engine evaluates rules ordered by priority (descending); the first
// fully-matching rule wins. If no rule matches, the default context is used.
type ContextSelectionRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ContextId     uint64                 `protobuf:"varint,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Conditions    []*RuleCondition       `protobuf:"bytes,4,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextSelectionRule) Reset() {
	*x = ContextSelectionRule{}
	mi := &file_scribe_v1_context_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextSelectionRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextSelectionRule) ProtoMessage() {}

func (x *ContextSelectionRule) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextSelectionRule.ProtoReflect.Descriptor instead.
func (*ContextSelectionRule) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{3}
}

func (x *ContextSelectionRule) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContextSelectionRule) GetContextId() uint64 {
	if x != nil {
		return x.ContextId
	}
	return 0
}

func (x *ContextSelectionRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ContextSelectionRule) GetConditions() []*RuleCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type ListContextsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, only return system contexts.
	SystemOnly    bool `protobuf:"varint,1,opt,name=system_only,json=systemOnly,proto3" json:"system_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContextsRequest) Reset() {
	*x = ListContextsRequest{}
	mi := &file_scribe_v1_context_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContextsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContextsRequest) ProtoMessage() {}

func (x *ListContextsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContextsRequest.ProtoReflect.Descriptor instead.
func (*ListContextsRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{4}
}

func (x *ListContextsRequest) GetSystemOnly() bool {
	if x != nil {
		return x.SystemOnly
	}
	return false
}

type ListContextsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contexts      []*Context             `protobuf:"bytes,1,rep,name=contexts,proto3" json:"contexts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContextsResponse) Reset() {
	*x = ListContextsResponse{}
	mi := &file_scribe_v1_context_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContextsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContextsResponse) ProtoMessage() {}

func (x *ListContextsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContextsResponse.ProtoReflect.Descriptor instead.
func (*ListContextsResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{5}
}

func (x *ListContextsResponse) GetContexts() []*Context {
	if x != nil {
		return x.Contexts
	}
	return nil
}

type GetContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextId     uint64                 `protobuf:"varint,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextRequest) Reset() {
	*x = GetContextRequest{}
	mi := &file_scribe_v1_context_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextRequest) ProtoMessage() {}

func (x *GetContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextRequest.ProtoReflect.Descriptor instead.
func (*GetContextRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{6}
}

func (x *GetContextRequest) GetContextId() uint64 {
	if x != nil {
		return x.ContextId
	}
	return 0
}

type GetContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *Context               `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextResponse) Reset() {
	*x = GetContextResponse{}
	mi := &file_scribe_v1_context_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextResponse) ProtoMessage() {}

func (x *GetContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextResponse.ProtoReflect.Descriptor instead.
func (*GetContextResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{7}
}

func (x *GetContextResponse) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type CreateContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *Context               `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContextRequest) Reset() {
	*x = CreateContextRequest{}
	mi := &file_scribe_v1_context_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContextRequest) ProtoMessage() {}

func (x *CreateContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContextRequest.ProtoReflect.Descriptor instead.
func (*CreateContextRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{8}
}

func (x *CreateContextRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type CreateContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *Context               `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContextResponse) Reset() {
	*x = CreateContextResponse{}
	mi := &file_scribe_v1_context_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContextResponse) ProtoMessage() {}

func (x *CreateContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContextResponse.ProtoReflect.Descriptor instead.
func (*CreateContextResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{9}
}

func (x *CreateContextResponse) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type UpdateContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *Context               `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContextRequest) Reset() {
	*x = UpdateContextRequest{}
	mi := &file_scribe_v1_context_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContextRequest) ProtoMessage() {}

func (x *UpdateContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContextRequest.ProtoReflect.Descriptor instead.
func (*UpdateContextRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateContextRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type UpdateContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *Context               `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContextResponse) Reset() {
	*x = UpdateContextResponse{}
	mi := &file_scribe_v1_context_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContextResponse) ProtoMessage() {}

func (x *UpdateContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContextResponse.ProtoReflect.Descriptor instead.
func (*UpdateContextResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateContextResponse) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type DeleteContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextId     uint64                 `protobuf:"varint,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContextRequest) Reset() {
	*x = DeleteContextRequest{}
	mi := &file_scribe_v1_context_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContextRequest) ProtoMessage() {}

func (x *DeleteContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContextRequest.ProtoReflect.Descriptor instead.
func (*DeleteContextRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteContextRequest) GetContextId() uint64 {
	if x != nil {
		return x.ContextId
	}
	return 0
}

type DeleteContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContextResponse) Reset() {
	*x = DeleteContextResponse{}
	mi := &file_scribe_v1_context_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContextResponse) ProtoMessage() {}

func (x *DeleteContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContextResponse.ProtoReflect.Descriptor instead.
func (*DeleteContextResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{13}
}

type ListSelectionRulesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by context; 0 = all rules
	ContextId     uint64 `protobuf:"varint,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSelectionRulesRequest) Reset() {
	*x = ListSelectionRulesRequest{}
	mi := &file_scribe_v1_context_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSelectionRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSelectionRulesRequest) ProtoMessage() {}

func (x *ListSelectionRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSelectionRulesRequest.ProtoReflect.Descriptor instead.
func (*ListSelectionRulesRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{14}
}

func (x *ListSelectionRulesRequest) GetContextId() uint64 {
	if x != nil {
		return x.ContextId
	}
	return 0
}

type ListSelectionRulesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Rules         []*ContextSelectionRule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSelectionRulesResponse) Reset() {
	*x = ListSelectionRulesResponse{}
	mi := &file_scribe_v1_context_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSelectionRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSelectionRulesResponse) ProtoMessage() {}

func (x *ListSelectionRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSelectionRulesResponse.ProtoReflect.Descriptor instead.
func (*ListSelectionRulesResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{15}
}

func (x *ListSelectionRulesResponse) GetRules() []*ContextSelectionRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type CreateSelectionRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *ContextSelectionRule  `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSelectionRuleRequest) Reset() {
	*x = CreateSelectionRuleRequest{}
	mi := &file_scribe_v1_context_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSelectionRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSelectionRuleRequest) ProtoMessage() {}

func (x *CreateSelectionRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSelectionRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateSelectionRuleRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{16}
}

func (x *CreateSelectionRuleRequest) GetRule() *ContextSelectionRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type CreateSelectionRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *ContextSelectionRule  `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSelectionRuleResponse) Reset() {
	*x = CreateSelectionRuleResponse{}
	mi := &file_scribe_v1_context_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSelectionRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSelectionRuleResponse) ProtoMessage() {}

func (x *CreateSelectionRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSelectionRuleResponse.ProtoReflect.Descriptor instead.
func (*CreateSelectionRuleResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{17}
}

func (x *CreateSelectionRuleResponse) GetRule() *ContextSelectionRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type DeleteSelectionRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        uint64                 `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSelectionRuleRequest) Reset() {
	*x = DeleteSelectionRuleRequest{}
	mi := &file_scribe_v1_context_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSelectionRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSelectionRuleRequest) ProtoMessage() {}

func (x *DeleteSelectionRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSelectionRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteSelectionRuleRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteSelectionRuleRequest) GetRuleId() uint64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

type DeleteSelectionRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSelectionRuleResponse) Reset() {
	*x = DeleteSelectionRuleResponse{}
	mi := &file_scribe_v1_context_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSelectionRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSelectionRuleResponse) ProtoMessage() {}

func (x *DeleteSelectionRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSelectionRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteSelectionRuleResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{19}
}

// ResolveContextRequest asks the selection engine to pick the right context
// for a given metadata bag (JSON object as string).
type ResolveContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetadataJson  string                 `protobuf:"bytes,1,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveContextRequest) Reset() {
	*x = ResolveContextRequest{}
	mi := &file_scribe_v1_context_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveContextRequest) ProtoMessage() {}

func (x *ResolveContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveContextRequest.ProtoReflect.Descriptor instead.
func (*ResolveContextRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{20}
}

func (x *ResolveContextRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type ResolveContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *Context               `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	IsDefault     bool                   `protobuf:"varint,2,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveContextResponse) Reset() {
	*x = ResolveContextResponse{}
	mi := &file_scribe_v1_context_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveContextResponse) ProtoMessage() {}

func (x *ResolveContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_context_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveContextResponse.ProtoReflect.Descriptor instead.
func (*ResolveContextResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_context_proto_rawDescGZIP(), []int{21}
}

func (x *ResolveContextResponse) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ResolveContextResponse) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

var File_scribe_v1_context_proto protoreflect.FileDescriptor

const file_scribe_v1_context_proto_rawDesc = "" +
	"\n" +
	"\x17scribe/v1/context.proto\x12\tscribe.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fscribe/v1/options/v1/auth.proto\"c\n" +
	"\x11ImagePreprocessor\x12$\n" +
	"\x04type\x18\x01 \x01(\tB\x10\xbaH\r\xc8\x01\x01r\b2\x06.*\\S.*R\x04type\x12(\n" +
	"\x06params\x18\x02 \x01(\tB\x10\xbaH\rr\v2\t^$|.*\\S.*R\x06params\"\xa3\x06\n" +
	"\aContext\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12$\n" +
	"\x04name\x18\x03 \x01(\tB\x10\xbaH\r\xc8\x01\x01r\b2\x06.*\\S.*R\x04name\x122\n" +
	"\vdescription\x18\x04 \x01(\tB\x10\xbaH\rr\v2\t^$|.*\\S.*R\vdescription\x12\x1d\n" +
	"\n" +
	"is_default\x18\x05 \x01(\bR\tisDefault\x12?\n" +
	"\x12segmentation_model\x18\x06 \x01(\tB\x10\xbaH\r\xc8\x01\x01r\b2\x06.*\\S.*R\x11segmentationModel\x12M\n" +
	"\x13image_preprocessors\x18\a \x03(\v2\x1c.scribe.v1.ImagePreprocessorR\x12imagePreprocessors\x12G\n" +
	"\x16transcription_provider\x18\b \x01(\tB\x10\xbaH\r\xc8\x01\x01r\b2\x06.*\\S.*R\x15transcriptionProvider\x12A\n" +
	"\x13transcription_model\x18\t \x01(\tB\x10\xbaH\rr\v2\t^$|.*\\S.*R\x12transcriptionModel\x12F\n" +
	"\x16transcription_base_url\x18\x0f \x01(\tB\x10\xbaH\rr\v2\t^$|.*\\S.*R\x14transcriptionBaseUrl\x12G\n" +
	"\x16transcription_audience\x18\x10 \x01(\tB\x10\xbaH\rr\v2\t^$|.*\\S.*R\x15transcriptionAudience\x12 \n" +
	"\vtemperature\x18\n" +
	" \x01(\x01R\vtemperature\x125\n" +
	"\rsystem_prompt\x18\v \x01(\tB\x10\xbaH\rr\v2\t^$|.*\\S.*R\fsystemPrompt\x122\n" +
	"\x15post_processing_steps\x18\f \x03(\tR\x13postProcessingSteps\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\"\x89\x03\n" +
	"\rRuleCondition\x12&\n" +
	"\x05field\x18\x01 \x01(\tB\x10\xbaH\r\xc8\x01\x01r\b2\x06.*\\S.*R\x05field\x12,\n" +
	"\boperator\x18\x02 \x01(\tB\x10\xbaH\r\xc8\x01\x01r\b2\x06.*\\S.*R\boperator\x12&\n" +
	"\x05value\x18\x03 \x01(\tB\x10\xbaH\r\xc8\x01\x01r\b2\x06.*\\S.*R\x05value:\xf9\x01\xbaH\xf5\x01\x1a\xf2\x01\n" +
	"\x17rule_condition.operator\x12Doperator must be one of eq, neq, contains, starts_with, or ends_with\x1a\x90\x01this.operator == 'eq' || this.operator == 'neq' || this.operator == 'contains' || this.operator == 'starts_with' || this.operator == 'ends_with'\"\xb1\x01\n" +
	"\x14ContextSelectionRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12)\n" +
	"\n" +
	"context_id\x18\x02 \x01(\x04B\n" +
	"\xbaH\a\xc8\x01\x012\x02 \x00R\tcontextId\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12B\n" +
	"\n" +
	"conditions\x18\x04 \x03(\v2\x18.scribe.v1.RuleConditionB\b\xbaH\x05\x92\x01\x02\b\x01R\n" +
	"conditions\"6\n" +
	"\x13ListContextsRequest\x12\x1f\n" +
	"\vsystem_only\x18\x01 \x01(\bR\n" +
	"systemOnly\"F\n" +
	"\x14ListContextsResponse\x12.\n" +
	"\bcontexts\x18\x01 \x03(\v2\x12.scribe.v1.ContextR\bcontexts\">\n" +
	"\x11GetContextRequest\x12)\n" +
	"\n" +
	"context_id\x18\x01 \x01(\x04B\n" +
	"\xbaH\a\xc8\x01\x012\x02 \x00R\tcontextId\"B\n" +
	"\x12GetContextResponse\x12,\n" +
	"\acontext\x18\x01 \x01(\v2\x12.scribe.v1.ContextR\acontext\"L\n" +
	"\x14CreateContextRequest\x124\n" +
	"\acontext\x18\x01 \x01(\v2\x12.scribe.v1.ContextB\x06\xbaH\x03\xc8\x01\x01R\acontext\"E\n" +
	"\x15CreateContextResponse\x12,\n" +
	"\acontext\x18\x01 \x01(\v2\x12.scribe.v1.ContextR\acontext\"\xa8\x01\n" +
	"\x14UpdateContextRequest\x124\n" +
	"\acontext\x18\x01 \x01(\v2\x12.scribe.v1.ContextB\x06\xbaH\x03\xc8\x01\x01R\acontext:Z\xbaHW\x1aU\n" +
	"\x11update_context.id\x12\x16context.id is required\x1a(has(this.context) && this.context.id > 0\"E\n" +
	"\x15UpdateContextResponse\x12,\n" +
	"\acontext\x18\x01 \x01(\v2\x12.scribe.v1.ContextR\acontext\"A\n" +
	"\x14DeleteContextRequest\x12)\n" +
	"\n" +
	"context_id\x18\x01 \x01(\x04B\n" +
	"\xbaH\a\xc8\x01\x012\x02 \x00R\tcontextId\"\x17\n" +
	"\x15DeleteContextResponse\":\n" +
	"\x19ListSelectionRulesRequest\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\x04R\tcontextId\"S\n" +
	"\x1aListSelectionRulesResponse\x125\n" +
	"\x05rules\x18\x01 \x03(\v2\x1f.scribe.v1.ContextSelectionRuleR\x05rules\"Y\n" +
	"\x1aCreateSelectionRuleRequest\x12;\n" +
	"\x04rule\x18\x01 \x01(\v2\x1f.scribe.v1.ContextSelectionRuleB\x06\xbaH\x03\xc8\x01\x01R\x04rule\"R\n" +
	"\x1bCreateSelectionRuleResponse\x123\n" +
	"\x04rule\x18\x01 \x01(\v2\x1f.scribe.v1.ContextSelectionRuleR\x04rule\"A\n" +
	"\x1aDeleteSelectionRuleRequest\x12#\n" +
	"\arule_id\x18\x01 \x01(\x04B\n" +
	"\xbaH\a\xc8\x01\x012\x02 \x00R\x06ruleId\"\x1d\n" +
	"\x1bDeleteSelectionRuleResponse\"<\n" +
	"\x15ResolveContextRequest\x12#\n" +
	"\rmetadata_json\x18\x01 \x01(\tR\fmetadataJson\"e\n" +
	"\x16ResolveContextResponse\x12,\n" +
	"\acontext\x18\x01 \x01(\v2\x12.scribe.v1.ContextR\acontext\x12\x1d\n" +
	"\n" +
	"is_default\x18\x02 \x01(\bR\tisDefault2\xbd\a\n" +
	"\x0eContextService\x12Y\n" +
	"\fListContexts\x12\x1e.scribe.v1.ListContextsRequest\x1a\x1f.scribe.v1.ListContextsResponse\"\b\x92\xb5\x18\x04\x10\x02\x18\x01\x12_\n" +
	"\n" +
	"GetContext\x12\x1c.scribe.v1.GetContextRequest\x1a\x1d.scribe.v1.GetContextResponse\"\x14\x92\xb5\x18\x10\x10\x05\x18\x01\"\n" +
	"context_id\x12\\\n" +
	"\rCreateContext\x12\x1f.scribe.v1.CreateContextRequest\x1a .scribe.v1.CreateContextResponse\"\b\x92\xb5\x18\x04\x10\x02\x18\x02\x12h\n" +
	"\rUpdateContext\x12\x1f.scribe.v1.UpdateContextRequest\x1a .scribe.v1.UpdateContextResponse\"\x14\x92\xb5\x18\x10\x10\x05\x18\x02\"\n" +
	"context.id\x12h\n" +
	"\rDeleteContext\x12\x1f.scribe.v1.DeleteContextRequest\x1a .scribe.v1.DeleteContextResponse\"\x14\x92\xb5\x18\x10\x10\x05\x18\x02\"\n" +
	"context_id\x12k\n" +
	"\x12ListSelectionRules\x12$.scribe.v1.ListSelectionRulesRequest\x1a%.scribe.v1.ListSelectionRulesResponse\"\b\x92\xb5\x18\x04\x10\x02\x18\x01\x12\x7f\n" +
	"\x13CreateSelectionRule\x12%.scribe.v1.CreateSelectionRuleRequest\x1a&.scribe.v1.CreateSelectionRuleResponse\"\x19\x92\xb5\x18\x15\x10\x05\x18\x02\"\x0frule.context_id\x12n\n" +
	"\x13DeleteSelectionRule\x12%.scribe.v1.DeleteSelectionRuleRequest\x1a&.scribe.v1.DeleteSelectionRuleResponse\"\b\x92\xb5\x18\x04\x10\x02\x18\x02\x12_\n" +
	"\x0eResolveContext\x12 .scribe.v1.ResolveContextRequest\x1a!.scribe.v1.ResolveContextResponse\"\b\x92\xb5\x18\x04\x10\x02\x18\x01B\xaa\x01\n" +
	"\rcom.scribe.v1B\fContextProtoP\x01ZFgithub.com/lehigh-university-libraries/scribe/proto/scribe/v1;scribev1\xa2\x02\x03SXX\xaa\x02\tScribe.V1\xca\x02\tScribe\\V1\xe2\x02\x15Scribe\\V1\\GPBMetadata\xea\x02\n" +
	"Scribe::V1b\x06proto3"

var (
	file_scribe_v1_context_proto_rawDescOnce sync.Once
	file_scribe_v1_context_proto_rawDescData []byte
)

func file_scribe_v1_context_proto_rawDescGZIP() []byte {
	file_scribe_v1_context_proto_rawDescOnce.Do(func() {
		file_scribe_v1_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scribe_v1_context_proto_rawDesc), len(file_scribe_v1_context_proto_rawDesc)))
	})
	return file_scribe_v1_context_proto_rawDescData
}

var file_scribe_v1_context_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_scribe_v1_context_proto_goTypes = []any{
	(*ImagePreprocessor)(nil),           // 0: scribe.v1.ImagePreprocessor
	(*Context)(nil),                     // 1: scribe.v1.Context
	(*RuleCondition)(nil),               // 2: scribe.v1.RuleCondition
	(*ContextSelectionRule)(nil),        // 3: scribe.v1.ContextSelectionRule
	(*ListContextsRequest)(nil),         // 4: scribe.v1.ListContextsRequest
	(*ListContextsResponse)(nil),        // 5: scribe.v1.ListContextsResponse
	(*GetContextRequest)(nil),           // 6: scribe.v1.GetContextRequest
	(*GetContextResponse)(nil),          // 7: scribe.v1.GetContextResponse
	(*CreateContextRequest)(nil),        // 8: scribe.v1.CreateContextRequest
	(*CreateContextResponse)(nil),       // 9: scribe.v1.CreateContextResponse
	(*UpdateContextRequest)(nil),        // 10: scribe.v1.UpdateContextRequest
	(*UpdateContextResponse)(nil),       // 11: scribe.v1.UpdateContextResponse
	(*DeleteContextRequest)(nil),        // 12: scribe.v1.DeleteContextRequest
	(*DeleteContextResponse)(nil),       // 13: scribe.v1.DeleteContextResponse
	(*ListSelectionRulesRequest)(nil),   // 14: scribe.v1.ListSelectionRulesRequest
	(*ListSelectionRulesResponse)(nil),  // 15: scribe.v1.ListSelectionRulesResponse
	(*CreateSelectionRuleRequest)(nil),  // 16: scribe.v1.CreateSelectionRuleRequest
	(*CreateSelectionRuleResponse)(nil), // 17: scribe.v1.CreateSelectionRuleResponse
	(*DeleteSelectionRuleRequest)(nil),  // 18: scribe.v1.DeleteSelectionRuleRequest
	(*DeleteSelectionRuleResponse)(nil), // 19: scribe.v1.DeleteSelectionRuleResponse
	(*ResolveContextRequest)(nil),       // 20: scribe.v1.ResolveContextRequest
	(*ResolveContextResponse)(nil),      // 21: scribe.v1.ResolveContextResponse
}
var file_scribe_v1_context_proto_depIdxs = []int32{
	0,  // 0: scribe.v1.Context.image_preprocessors:type_name -> scribe.v1.ImagePreprocessor
	2,  // 1: scribe.v1.ContextSelectionRule.conditions:type_name -> scribe.v1.RuleCondition
	1,  // 2: scribe.v1.ListContextsResponse.contexts:type_name -> scribe.v1.Context
	1,  // 3: scribe.v1.GetContextResponse.context:type_name -> scribe.v1.Context
	1,  // 4: scribe.v1.CreateContextRequest.context:type_name -> scribe.v1.Context
	1,  // 5: scribe.v1.CreateContextResponse.context:type_name -> scribe.v1.Context
	1,  // 6: scribe.v1.UpdateContextRequest.context:type_name -> scribe.v1.Context
	1,  // 7: scribe.v1.UpdateContextResponse.context:type_name -> scribe.v1.Context
	3,  // 8: scribe.v1.ListSelectionRulesResponse.rules:type_name -> scribe.v1.ContextSelectionRule
	3,  // 9: scribe.v1.CreateSelectionRuleRequest.rule:type_name -> scribe.v1.ContextSelectionRule
	3,  // 10: scribe.v1.CreateSelectionRuleResponse.rule:type_name -> scribe.v1.ContextSelectionRule
	1,  // 11: scribe.v1.ResolveContextResponse.context:type_name -> scribe.v1.Context
	4,  // 12: scribe.v1.ContextService.ListContexts:input_type -> scribe.v1.ListContextsRequest
	6,  // 13: scribe.v1.ContextService.GetContext:input_type -> scribe.v1.GetContextRequest
	8,  // 14: scribe.v1.ContextService.CreateContext:input_type -> scribe.v1.CreateContextRequest
	10, // 15: scribe.v1.ContextService.UpdateContext:input_type -> scribe.v1.UpdateContextRequest
	12, // 16: scribe.v1.ContextService.DeleteContext:input_type -> scribe.v1.DeleteContextRequest
	14, // 17: scribe.v1.ContextService.ListSelectionRules:input_type -> scribe.v1.ListSelectionRulesRequest
	16, // 18: scribe.v1.ContextService.CreateSelectionRule:input_type -> scribe.v1.CreateSelectionRuleRequest
	18, // 19: scribe.v1.ContextService.DeleteSelectionRule:input_type -> scribe.v1.DeleteSelectionRuleRequest
	20, // 20: scribe.v1.ContextService.ResolveContext:input_type -> scribe.v1.ResolveContextRequest
	5,  // 21: scribe.v1.ContextService.ListContexts:output_type -> scribe.v1.ListContextsResponse
	7,  // 22: scribe.v1.ContextService.GetContext:output_type -> scribe.v1.GetContextResponse
	9,  // 23: scribe.v1.ContextService.CreateContext:output_type -> scribe.v1.CreateContextResponse
	11, // 24: scribe.v1.ContextService.UpdateContext:output_type -> scribe.v1.UpdateContextResponse
	13, // 25: scribe.v1.ContextService.DeleteContext:output_type -> scribe.v1.DeleteContextResponse
	15, // 26: scribe.v1.ContextService.ListSelectionRules:output_type -> scribe.v1.ListSelectionRulesResponse
	17, // 27: scribe.v1.ContextService.CreateSelectionRule:output_type -> scribe.v1.CreateSelectionRuleResponse
	19, // 28: scribe.v1.ContextService.DeleteSelectionRule:output_type -> scribe.v1.DeleteSelectionRuleResponse
	21, // 29: scribe.v1.ContextService.ResolveContext:output_type -> scribe.v1.ResolveContextResponse
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_scribe_v1_context_proto_init() }
func file_scribe_v1_context_proto_init() {
	if File_scribe_v1_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scribe_v1_context_proto_rawDesc), len(file_scribe_v1_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scribe_v1_context_proto_goTypes,
		DependencyIndexes: file_scribe_v1_context_proto_depIdxs,
		MessageInfos:      file_scribe_v1_context_proto_msgTypes,
	}.Build()
	File_scribe_v1_context_proto = out.File
	file_scribe_v1_context_proto_goTypes = nil
	file_scribe_v1_context_proto_depIdxs = nil
}
