// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: scribe/v1/workspace.proto

package scribev1

import (
	_ "github.com/lehigh-university-libraries/scribe/proto/scribe/v1/options/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PictureUrl    string                 `protobuf:"bytes,4,opt,name=picture_url,json=pictureUrl,proto3" json:"picture_url,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,5,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetPictureUrl() string {
	if x != nil {
		return x.PictureUrl
	}
	return ""
}

func (x *UserProfile) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	IsPersonal    bool                   `protobuf:"varint,4,opt,name=is_personal,json=isPersonal,proto3" json:"is_personal,omitempty"`
	OwnerUserId   uint64                 `protobuf:"varint,5,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *Workspace) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Workspace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workspace) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Workspace) GetIsPersonal() bool {
	if x != nil {
		return x.IsPersonal
	}
	return false
}

func (x *Workspace) GetOwnerUserId() uint64 {
	if x != nil {
		return x.OwnerUserId
	}
	return 0
}

func (x *Workspace) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Workspace) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type WorkspaceAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceAccess) Reset() {
	*x = WorkspaceAccess{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceAccess) ProtoMessage() {}

func (x *WorkspaceAccess) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceAccess.ProtoReflect.Descriptor instead.
func (*WorkspaceAccess) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *WorkspaceAccess) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *WorkspaceAccess) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type WorkspaceMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   uint64                 `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	User          *UserProfile           `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceMember) Reset() {
	*x = WorkspaceMember{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceMember) ProtoMessage() {}

func (x *WorkspaceMember) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceMember.ProtoReflect.Descriptor instead.
func (*WorkspaceMember) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *WorkspaceMember) GetWorkspaceId() uint64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *WorkspaceMember) GetUser() *UserProfile {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *WorkspaceMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WorkspaceMember) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesRequest) Reset() {
	*x = ListWorkspacesRequest{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesRequest) ProtoMessage() {}

func (x *ListWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*ListWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{4}
}

type ListWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*WorkspaceAccess     `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesResponse) Reset() {
	*x = ListWorkspacesResponse{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesResponse) ProtoMessage() {}

func (x *ListWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *ListWorkspacesResponse) GetWorkspaces() []*WorkspaceAccess {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type CreateWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkspaceRequest) Reset() {
	*x = CreateWorkspaceRequest{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceRequest) ProtoMessage() {}

func (x *CreateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *CreateWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *WorkspaceAccess       `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkspaceResponse) Reset() {
	*x = CreateWorkspaceResponse{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceResponse) ProtoMessage() {}

func (x *CreateWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{7}
}

func (x *CreateWorkspaceResponse) GetWorkspace() *WorkspaceAccess {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type UpdateWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   uint64                 `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkspaceRequest) Reset() {
	*x = UpdateWorkspaceRequest{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkspaceRequest) ProtoMessage() {}

func (x *UpdateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateWorkspaceRequest) GetWorkspaceId() uint64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *UpdateWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkspaceResponse) Reset() {
	*x = UpdateWorkspaceResponse{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkspaceResponse) ProtoMessage() {}

func (x *UpdateWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*UpdateWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateWorkspaceResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type ListWorkspaceMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   uint64                 `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspaceMembersRequest) Reset() {
	*x = ListWorkspaceMembersRequest{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspaceMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspaceMembersRequest) ProtoMessage() {}

func (x *ListWorkspaceMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspaceMembersRequest.ProtoReflect.Descriptor instead.
func (*ListWorkspaceMembersRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{10}
}

func (x *ListWorkspaceMembersRequest) GetWorkspaceId() uint64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

type ListWorkspaceMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Members       []*WorkspaceMember     `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspaceMembersResponse) Reset() {
	*x = ListWorkspaceMembersResponse{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspaceMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspaceMembersResponse) ProtoMessage() {}

func (x *ListWorkspaceMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspaceMembersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspaceMembersResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{11}
}

func (x *ListWorkspaceMembersResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *ListWorkspaceMembersResponse) GetMembers() []*WorkspaceMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type AddWorkspaceMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   uint64                 `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWorkspaceMemberRequest) Reset() {
	*x = AddWorkspaceMemberRequest{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWorkspaceMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWorkspaceMemberRequest) ProtoMessage() {}

func (x *AddWorkspaceMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWorkspaceMemberRequest.ProtoReflect.Descriptor instead.
func (*AddWorkspaceMemberRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{12}
}

func (x *AddWorkspaceMemberRequest) GetWorkspaceId() uint64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *AddWorkspaceMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddWorkspaceMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AddWorkspaceMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *WorkspaceMember       `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWorkspaceMemberResponse) Reset() {
	*x = AddWorkspaceMemberResponse{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWorkspaceMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWorkspaceMemberResponse) ProtoMessage() {}

func (x *AddWorkspaceMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWorkspaceMemberResponse.ProtoReflect.Descriptor instead.
func (*AddWorkspaceMemberResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{13}
}

func (x *AddWorkspaceMemberResponse) GetMember() *WorkspaceMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type UpdateWorkspaceMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   uint64                 `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkspaceMemberRequest) Reset() {
	*x = UpdateWorkspaceMemberRequest{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkspaceMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkspaceMemberRequest) ProtoMessage() {}

func (x *UpdateWorkspaceMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkspaceMemberRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkspaceMemberRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateWorkspaceMemberRequest) GetWorkspaceId() uint64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *UpdateWorkspaceMemberRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateWorkspaceMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateWorkspaceMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *WorkspaceMember       `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkspaceMemberResponse) Reset() {
	*x = UpdateWorkspaceMemberResponse{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkspaceMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkspaceMemberResponse) ProtoMessage() {}

func (x *UpdateWorkspaceMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkspaceMemberResponse.ProtoReflect.Descriptor instead.
func (*UpdateWorkspaceMemberResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateWorkspaceMemberResponse) GetMember() *WorkspaceMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type DeleteWorkspaceMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   uint64                 `protobuf:"varint,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceMemberRequest) Reset() {
	*x = DeleteWorkspaceMemberRequest{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceMemberRequest) ProtoMessage() {}

func (x *DeleteWorkspaceMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceMemberRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceMemberRequest) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteWorkspaceMemberRequest) GetWorkspaceId() uint64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *DeleteWorkspaceMemberRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteWorkspaceMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceMemberResponse) Reset() {
	*x = DeleteWorkspaceMemberResponse{}
	mi := &file_scribe_v1_workspace_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceMemberResponse) ProtoMessage() {}

func (x *DeleteWorkspaceMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scribe_v1_workspace_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceMemberResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceMemberResponse) Descriptor() ([]byte, []int) {
	return file_scribe_v1_workspace_proto_rawDescGZIP(), []int{17}
}

var File_scribe_v1_workspace_proto protoreflect.FileDescriptor

const file_scribe_v1_workspace_proto_rawDesc = "" +
	"\n" +
	"\x19scribe/v1/workspace.proto\x12\tscribe.v1\x1a\x1fscribe/v1/options/v1/auth.proto\"\x83\x01\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1f\n" +
	"\vpicture_url\x18\x04 \x01(\tR\n" +
	"pictureUrl\x12\x19\n" +
	"\bis_admin\x18\x05 \x01(\bR\aisAdmin\"\xc6\x01\n" +
	"\tWorkspace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x1f\n" +
	"\vis_personal\x18\x04 \x01(\bR\n" +
	"isPersonal\x12\"\n" +
	"\rowner_user_id\x18\x05 \x01(\x04R\vownerUserId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"Y\n" +
	"\x0fWorkspaceAccess\x122\n" +
	"\tworkspace\x18\x01 \x01(\v2\x14.scribe.v1.WorkspaceR\tworkspace\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\x93\x01\n" +
	"\x0fWorkspaceMember\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x04R\vworkspaceId\x12*\n" +
	"\x04user\x18\x02 \x01(\v2\x16.scribe.v1.UserProfileR\x04user\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"\x17\n" +
	"\x15ListWorkspacesRequest\"T\n" +
	"\x16ListWorkspacesResponse\x12:\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x1a.scribe.v1.WorkspaceAccessR\n" +
	"workspaces\",\n" +
	"\x16CreateWorkspaceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"S\n" +
	"\x17CreateWorkspaceResponse\x128\n" +
	"\tworkspace\x18\x01 \x01(\v2\x1a.scribe.v1.WorkspaceAccessR\tworkspace\"O\n" +
	"\x16UpdateWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x04R\vworkspaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"M\n" +
	"\x17UpdateWorkspaceResponse\x122\n" +
	"\tworkspace\x18\x01 \x01(\v2\x14.scribe.v1.WorkspaceR\tworkspace\"@\n" +
	"\x1bListWorkspaceMembersRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x04R\vworkspaceId\"\x88\x01\n" +
	"\x1cListWorkspaceMembersResponse\x122\n" +
	"\tworkspace\x18\x01 \x01(\v2\x14.scribe.v1.WorkspaceR\tworkspace\x124\n" +
	"\amembers\x18\x02 \x03(\v2\x1a.scribe.v1.WorkspaceMemberR\amembers\"h\n" +
	"\x19AddWorkspaceMemberRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x04R\vworkspaceId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"P\n" +
	"\x1aAddWorkspaceMemberResponse\x122\n" +
	"\x06member\x18\x01 \x01(\v2\x1a.scribe.v1.WorkspaceMemberR\x06member\"n\n" +
	"\x1cUpdateWorkspaceMemberRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x04R\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"S\n" +
	"\x1dUpdateWorkspaceMemberResponse\x122\n" +
	"\x06member\x18\x01 \x01(\v2\x1a.scribe.v1.WorkspaceMemberR\x06member\"Z\n" +
	"\x1cDeleteWorkspaceMemberRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\x04R\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"\x1f\n" +
	"\x1dDeleteWorkspaceMemberResponse2\xcf\x06\n" +
	"\x10WorkspaceService\x12_\n" +
	"\x0eListWorkspaces\x12 .scribe.v1.ListWorkspacesRequest\x1a!.scribe.v1.ListWorkspacesResponse\"\b\x92\xb5\x18\x04\x10\x02\x18\x01\x12b\n" +
	"\x0fCreateWorkspace\x12!.scribe.v1.CreateWorkspaceRequest\x1a\".scribe.v1.CreateWorkspaceResponse\"\b\x92\xb5\x18\x04\x10\x02\x18\x02\x12p\n" +
	"\x0fUpdateWorkspace\x12!.scribe.v1.UpdateWorkspaceRequest\x1a\".scribe.v1.UpdateWorkspaceResponse\"\x16\x92\xb5\x18\x12\x10\a\x18\x03\"\fworkspace_id\x12\x7f\n" +
	"\x14ListWorkspaceMembers\x12&.scribe.v1.ListWorkspaceMembersRequest\x1a'.scribe.v1.ListWorkspaceMembersResponse\"\x16\x92\xb5\x18\x12\x10\a\x18\x01\"\fworkspace_id\x12y\n" +
	"\x12AddWorkspaceMember\x12$.scribe.v1.AddWorkspaceMemberRequest\x1a%.scribe.v1.AddWorkspaceMemberResponse\"\x16\x92\xb5\x18\x12\x10\a\x18\x03\"\fworkspace_id\x12\x82\x01\n" +
	"\x15UpdateWorkspaceMember\x12'.scribe.v1.UpdateWorkspaceMemberRequest\x1a(.scribe.v1.UpdateWorkspaceMemberResponse\"\x16\x92\xb5\x18\x12\x10\a\x18\x03\"\fworkspace_id\x12\x82\x01\n" +
	"\x15DeleteWorkspaceMember\x12'.scribe.v1.DeleteWorkspaceMemberRequest\x1a(.scribe.v1.DeleteWorkspaceMemberResponse\"\x16\x92\xb5\x18\x12\x10\a\x18\x03\"\fworkspace_idB\xac\x01\n" +
	"\rcom.scribe.v1B\x0eWorkspaceProtoP\x01ZFgithub.com/lehigh-university-libraries/scribe/proto/scribe/v1;scribev1\xa2\x02\x03SXX\xaa\x02\tScribe.V1\xca\x02\tScribe\\V1\xe2\x02\x15Scribe\\V1\\GPBMetadata\xea\x02\n" +
	"Scribe::V1b\x06proto3"

var (
	file_scribe_v1_workspace_proto_rawDescOnce sync.Once
	file_scribe_v1_workspace_proto_rawDescData []byte
)

func file_scribe_v1_workspace_proto_rawDescGZIP() []byte {
	file_scribe_v1_workspace_proto_rawDescOnce.Do(func() {
		file_scribe_v1_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scribe_v1_workspace_proto_rawDesc), len(file_scribe_v1_workspace_proto_rawDesc)))
	})
	return file_scribe_v1_workspace_proto_rawDescData
}

var file_scribe_v1_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_scribe_v1_workspace_proto_goTypes = []any{
	(*UserProfile)(nil),                   // 0: scribe.v1.UserProfile
	(*Workspace)(nil),                     // 1: scribe.v1.Workspace
	(*WorkspaceAccess)(nil),               // 2: scribe.v1.WorkspaceAccess
	(*WorkspaceMember)(nil),               // 3: scribe.v1.WorkspaceMember
	(*ListWorkspacesRequest)(nil),         // 4: scribe.v1.ListWorkspacesRequest
	(*ListWorkspacesResponse)(nil),        // 5: scribe.v1.ListWorkspacesResponse
	(*CreateWorkspaceRequest)(nil),        // 6: scribe.v1.CreateWorkspaceRequest
	(*CreateWorkspaceResponse)(nil),       // 7: scribe.v1.CreateWorkspaceResponse
	(*UpdateWorkspaceRequest)(nil),        // 8: scribe.v1.UpdateWorkspaceRequest
	(*UpdateWorkspaceResponse)(nil),       // 9: scribe.v1.UpdateWorkspaceResponse
	(*ListWorkspaceMembersRequest)(nil),   // 10: scribe.v1.ListWorkspaceMembersRequest
	(*ListWorkspaceMembersResponse)(nil),  // 11: scribe.v1.ListWorkspaceMembersResponse
	(*AddWorkspaceMemberRequest)(nil),     // 12: scribe.v1.AddWorkspaceMemberRequest
	(*AddWorkspaceMemberResponse)(nil),    // 13: scribe.v1.AddWorkspaceMemberResponse
	(*UpdateWorkspaceMemberRequest)(nil),  // 14: scribe.v1.UpdateWorkspaceMemberRequest
	(*UpdateWorkspaceMemberResponse)(nil), // 15: scribe.v1.UpdateWorkspaceMemberResponse
	(*DeleteWorkspaceMemberRequest)(nil),  // 16: scribe.v1.DeleteWorkspaceMemberRequest
	(*DeleteWorkspaceMemberResponse)(nil), // 17: scribe.v1.DeleteWorkspaceMemberResponse
}
var file_scribe_v1_workspace_proto_depIdxs = []int32{
	1,  // 0: scribe.v1.WorkspaceAccess.workspace:type_name -> scribe.v1.Workspace
	0,  // 1: scribe.v1.WorkspaceMember.user:type_name -> scribe.v1.UserProfile
	2,  // 2: scribe.v1.ListWorkspacesResponse.workspaces:type_name -> scribe.v1.WorkspaceAccess
	2,  // 3: scribe.v1.CreateWorkspaceResponse.workspace:type_name -> scribe.v1.WorkspaceAccess
	1,  // 4: scribe.v1.UpdateWorkspaceResponse.workspace:type_name -> scribe.v1.Workspace
	1,  // 5: scribe.v1.ListWorkspaceMembersResponse.workspace:type_name -> scribe.v1.Workspace
	3,  // 6: scribe.v1.ListWorkspaceMembersResponse.members:type_name -> scribe.v1.WorkspaceMember
	3,  // 7: scribe.v1.AddWorkspaceMemberResponse.member:type_name -> scribe.v1.WorkspaceMember
	3,  // 8: scribe.v1.UpdateWorkspaceMemberResponse.member:type_name -> scribe.v1.WorkspaceMember
	4,  // 9: scribe.v1.WorkspaceService.ListWorkspaces:input_type -> scribe.v1.ListWorkspacesRequest
	6,  // 10: scribe.v1.WorkspaceService.CreateWorkspace:input_type -> scribe.v1.CreateWorkspaceRequest
	8,  // 11: scribe.v1.WorkspaceService.UpdateWorkspace:input_type -> scribe.v1.UpdateWorkspaceRequest
	10, // 12: scribe.v1.WorkspaceService.ListWorkspaceMembers:input_type -> scribe.v1.ListWorkspaceMembersRequest
	12, // 13: scribe.v1.WorkspaceService.AddWorkspaceMember:input_type -> scribe.v1.AddWorkspaceMemberRequest
	14, // 14: scribe.v1.WorkspaceService.UpdateWorkspaceMember:input_type -> scribe.v1.UpdateWorkspaceMemberRequest
	16, // 15: scribe.v1.WorkspaceService.DeleteWorkspaceMember:input_type -> scribe.v1.DeleteWorkspaceMemberRequest
	5,  // 16: scribe.v1.WorkspaceService.ListWorkspaces:output_type -> scribe.v1.ListWorkspacesResponse
	7,  // 17: scribe.v1.WorkspaceService.CreateWorkspace:output_type -> scribe.v1.CreateWorkspaceResponse
	9,  // 18: scribe.v1.WorkspaceService.UpdateWorkspace:output_type -> scribe.v1.UpdateWorkspaceResponse
	11, // 19: scribe.v1.WorkspaceService.ListWorkspaceMembers:output_type -> scribe.v1.ListWorkspaceMembersResponse
	13, // 20: scribe.v1.WorkspaceService.AddWorkspaceMember:output_type -> scribe.v1.AddWorkspaceMemberResponse
	15, // 21: scribe.v1.WorkspaceService.UpdateWorkspaceMember:output_type -> scribe.v1.UpdateWorkspaceMemberResponse
	17, // 22: scribe.v1.WorkspaceService.DeleteWorkspaceMember:output_type -> scribe.v1.DeleteWorkspaceMemberResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_scribe_v1_workspace_proto_init() }
func file_scribe_v1_workspace_proto_init() {
	if File_scribe_v1_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scribe_v1_workspace_proto_rawDesc), len(file_scribe_v1_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scribe_v1_workspace_proto_goTypes,
		DependencyIndexes: file_scribe_v1_workspace_proto_depIdxs,
		MessageInfos:      file_scribe_v1_workspace_proto_msgTypes,
	}.Build()
	File_scribe_v1_workspace_proto = out.File
	file_scribe_v1_workspace_proto_goTypes = nil
	file_scribe_v1_workspace_proto_depIdxs = nil
}
