// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: scribe/v1/item.proto

package scribev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/lehigh-university-libraries/scribe/proto/scribe/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ItemServiceName is the fully-qualified name of the ItemService service.
	ItemServiceName = "scribe.v1.ItemService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ItemServiceListItemsProcedure is the fully-qualified name of the ItemService's ListItems RPC.
	ItemServiceListItemsProcedure = "/scribe.v1.ItemService/ListItems"
	// ItemServiceGetItemProcedure is the fully-qualified name of the ItemService's GetItem RPC.
	ItemServiceGetItemProcedure = "/scribe.v1.ItemService/GetItem"
	// ItemServiceCreateItemProcedure is the fully-qualified name of the ItemService's CreateItem RPC.
	ItemServiceCreateItemProcedure = "/scribe.v1.ItemService/CreateItem"
	// ItemServiceUploadItemImageProcedure is the fully-qualified name of the ItemService's
	// UploadItemImage RPC.
	ItemServiceUploadItemImageProcedure = "/scribe.v1.ItemService/UploadItemImage"
	// ItemServiceDeleteItemProcedure is the fully-qualified name of the ItemService's DeleteItem RPC.
	ItemServiceDeleteItemProcedure = "/scribe.v1.ItemService/DeleteItem"
)

// ItemServiceClient is a client for the scribe.v1.ItemService service.
type ItemServiceClient interface {
	ListItems(context.Context, *connect.Request[v1.ListItemsRequest]) (*connect.Response[v1.ListItemsResponse], error)
	GetItem(context.Context, *connect.Request[v1.GetItemRequest]) (*connect.Response[v1.GetItemResponse], error)
	CreateItem(context.Context, *connect.Request[v1.CreateItemRequest]) (*connect.Response[v1.CreateItemResponse], error)
	UploadItemImage(context.Context, *connect.Request[v1.UploadItemImageRequest]) (*connect.Response[v1.UploadItemImageResponse], error)
	DeleteItem(context.Context, *connect.Request[v1.DeleteItemRequest]) (*connect.Response[v1.DeleteItemResponse], error)
}

// NewItemServiceClient constructs a client for the scribe.v1.ItemService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewItemServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ItemServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	itemServiceMethods := v1.File_scribe_v1_item_proto.Services().ByName("ItemService").Methods()
	return &itemServiceClient{
		listItems: connect.NewClient[v1.ListItemsRequest, v1.ListItemsResponse](
			httpClient,
			baseURL+ItemServiceListItemsProcedure,
			connect.WithSchema(itemServiceMethods.ByName("ListItems")),
			connect.WithClientOptions(opts...),
		),
		getItem: connect.NewClient[v1.GetItemRequest, v1.GetItemResponse](
			httpClient,
			baseURL+ItemServiceGetItemProcedure,
			connect.WithSchema(itemServiceMethods.ByName("GetItem")),
			connect.WithClientOptions(opts...),
		),
		createItem: connect.NewClient[v1.CreateItemRequest, v1.CreateItemResponse](
			httpClient,
			baseURL+ItemServiceCreateItemProcedure,
			connect.WithSchema(itemServiceMethods.ByName("CreateItem")),
			connect.WithClientOptions(opts...),
		),
		uploadItemImage: connect.NewClient[v1.UploadItemImageRequest, v1.UploadItemImageResponse](
			httpClient,
			baseURL+ItemServiceUploadItemImageProcedure,
			connect.WithSchema(itemServiceMethods.ByName("UploadItemImage")),
			connect.WithClientOptions(opts...),
		),
		deleteItem: connect.NewClient[v1.DeleteItemRequest, v1.DeleteItemResponse](
			httpClient,
			baseURL+ItemServiceDeleteItemProcedure,
			connect.WithSchema(itemServiceMethods.ByName("DeleteItem")),
			connect.WithClientOptions(opts...),
		),
	}
}

// itemServiceClient implements ItemServiceClient.
type itemServiceClient struct {
	listItems       *connect.Client[v1.ListItemsRequest, v1.ListItemsResponse]
	getItem         *connect.Client[v1.GetItemRequest, v1.GetItemResponse]
	createItem      *connect.Client[v1.CreateItemRequest, v1.CreateItemResponse]
	uploadItemImage *connect.Client[v1.UploadItemImageRequest, v1.UploadItemImageResponse]
	deleteItem      *connect.Client[v1.DeleteItemRequest, v1.DeleteItemResponse]
}

// ListItems calls scribe.v1.ItemService.ListItems.
func (c *itemServiceClient) ListItems(ctx context.Context, req *connect.Request[v1.ListItemsRequest]) (*connect.Response[v1.ListItemsResponse], error) {
	return c.listItems.CallUnary(ctx, req)
}

// GetItem calls scribe.v1.ItemService.GetItem.
func (c *itemServiceClient) GetItem(ctx context.Context, req *connect.Request[v1.GetItemRequest]) (*connect.Response[v1.GetItemResponse], error) {
	return c.getItem.CallUnary(ctx, req)
}

// CreateItem calls scribe.v1.ItemService.CreateItem.
func (c *itemServiceClient) CreateItem(ctx context.Context, req *connect.Request[v1.CreateItemRequest]) (*connect.Response[v1.CreateItemResponse], error) {
	return c.createItem.CallUnary(ctx, req)
}

// UploadItemImage calls scribe.v1.ItemService.UploadItemImage.
func (c *itemServiceClient) UploadItemImage(ctx context.Context, req *connect.Request[v1.UploadItemImageRequest]) (*connect.Response[v1.UploadItemImageResponse], error) {
	return c.uploadItemImage.CallUnary(ctx, req)
}

// DeleteItem calls scribe.v1.ItemService.DeleteItem.
func (c *itemServiceClient) DeleteItem(ctx context.Context, req *connect.Request[v1.DeleteItemRequest]) (*connect.Response[v1.DeleteItemResponse], error) {
	return c.deleteItem.CallUnary(ctx, req)
}

// ItemServiceHandler is an implementation of the scribe.v1.ItemService service.
type ItemServiceHandler interface {
	ListItems(context.Context, *connect.Request[v1.ListItemsRequest]) (*connect.Response[v1.ListItemsResponse], error)
	GetItem(context.Context, *connect.Request[v1.GetItemRequest]) (*connect.Response[v1.GetItemResponse], error)
	CreateItem(context.Context, *connect.Request[v1.CreateItemRequest]) (*connect.Response[v1.CreateItemResponse], error)
	UploadItemImage(context.Context, *connect.Request[v1.UploadItemImageRequest]) (*connect.Response[v1.UploadItemImageResponse], error)
	DeleteItem(context.Context, *connect.Request[v1.DeleteItemRequest]) (*connect.Response[v1.DeleteItemResponse], error)
}

// NewItemServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewItemServiceHandler(svc ItemServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	itemServiceMethods := v1.File_scribe_v1_item_proto.Services().ByName("ItemService").Methods()
	itemServiceListItemsHandler := connect.NewUnaryHandler(
		ItemServiceListItemsProcedure,
		svc.ListItems,
		connect.WithSchema(itemServiceMethods.ByName("ListItems")),
		connect.WithHandlerOptions(opts...),
	)
	itemServiceGetItemHandler := connect.NewUnaryHandler(
		ItemServiceGetItemProcedure,
		svc.GetItem,
		connect.WithSchema(itemServiceMethods.ByName("GetItem")),
		connect.WithHandlerOptions(opts...),
	)
	itemServiceCreateItemHandler := connect.NewUnaryHandler(
		ItemServiceCreateItemProcedure,
		svc.CreateItem,
		connect.WithSchema(itemServiceMethods.ByName("CreateItem")),
		connect.WithHandlerOptions(opts...),
	)
	itemServiceUploadItemImageHandler := connect.NewUnaryHandler(
		ItemServiceUploadItemImageProcedure,
		svc.UploadItemImage,
		connect.WithSchema(itemServiceMethods.ByName("UploadItemImage")),
		connect.WithHandlerOptions(opts...),
	)
	itemServiceDeleteItemHandler := connect.NewUnaryHandler(
		ItemServiceDeleteItemProcedure,
		svc.DeleteItem,
		connect.WithSchema(itemServiceMethods.ByName("DeleteItem")),
		connect.WithHandlerOptions(opts...),
	)
	return "/scribe.v1.ItemService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ItemServiceListItemsProcedure:
			itemServiceListItemsHandler.ServeHTTP(w, r)
		case ItemServiceGetItemProcedure:
			itemServiceGetItemHandler.ServeHTTP(w, r)
		case ItemServiceCreateItemProcedure:
			itemServiceCreateItemHandler.ServeHTTP(w, r)
		case ItemServiceUploadItemImageProcedure:
			itemServiceUploadItemImageHandler.ServeHTTP(w, r)
		case ItemServiceDeleteItemProcedure:
			itemServiceDeleteItemHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedItemServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedItemServiceHandler struct{}

func (UnimplementedItemServiceHandler) ListItems(context.Context, *connect.Request[v1.ListItemsRequest]) (*connect.Response[v1.ListItemsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scribe.v1.ItemService.ListItems is not implemented"))
}

func (UnimplementedItemServiceHandler) GetItem(context.Context, *connect.Request[v1.GetItemRequest]) (*connect.Response[v1.GetItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scribe.v1.ItemService.GetItem is not implemented"))
}

func (UnimplementedItemServiceHandler) CreateItem(context.Context, *connect.Request[v1.CreateItemRequest]) (*connect.Response[v1.CreateItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scribe.v1.ItemService.CreateItem is not implemented"))
}

func (UnimplementedItemServiceHandler) UploadItemImage(context.Context, *connect.Request[v1.UploadItemImageRequest]) (*connect.Response[v1.UploadItemImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scribe.v1.ItemService.UploadItemImage is not implemented"))
}

func (UnimplementedItemServiceHandler) DeleteItem(context.Context, *connect.Request[v1.DeleteItemRequest]) (*connect.Response[v1.DeleteItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scribe.v1.ItemService.DeleteItem is not implemented"))
}
