// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file scribe/v1/annotation.proto (package scribe.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateAnnotationRequest, CreateAnnotationResponse, DeleteAnnotationRequest, DeleteAnnotationResponse, EnrichAnnotationRequest, EnrichAnnotationResponse, GetAnnotationRequest, GetAnnotationResponse, SearchAnnotationsRequest, SearchAnnotationsResponse, UpdateAnnotationRequest, UpdateAnnotationResponse } from "./annotation_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service scribe.v1.AnnotationService
 */
export const AnnotationService = {
  typeName: "scribe.v1.AnnotationService",
  methods: {
    /**
     * @generated from rpc scribe.v1.AnnotationService.SearchAnnotations
     */
    searchAnnotations: {
      name: "SearchAnnotations",
      I: SearchAnnotationsRequest,
      O: SearchAnnotationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scribe.v1.AnnotationService.GetAnnotation
     */
    getAnnotation: {
      name: "GetAnnotation",
      I: GetAnnotationRequest,
      O: GetAnnotationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scribe.v1.AnnotationService.CreateAnnotation
     */
    createAnnotation: {
      name: "CreateAnnotation",
      I: CreateAnnotationRequest,
      O: CreateAnnotationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scribe.v1.AnnotationService.UpdateAnnotation
     */
    updateAnnotation: {
      name: "UpdateAnnotation",
      I: UpdateAnnotationRequest,
      O: UpdateAnnotationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scribe.v1.AnnotationService.DeleteAnnotation
     */
    deleteAnnotation: {
      name: "DeleteAnnotation",
      I: DeleteAnnotationRequest,
      O: DeleteAnnotationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Improve transcription for one line or a full canvas.
     *
     * @generated from rpc scribe.v1.AnnotationService.EnrichAnnotation
     */
    enrichAnnotation: {
      name: "EnrichAnnotation",
      I: EnrichAnnotationRequest,
      O: EnrichAnnotationResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

