// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file scribe/v1/annotation.proto (package scribe.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message scribe.v1.SearchAnnotationsRequest
 */
export class SearchAnnotationsRequest extends Message<SearchAnnotationsRequest> {
  /**
   * @generated from field: string canvas_uri = 1;
   */
  canvasUri = "";

  constructor(data?: PartialMessage<SearchAnnotationsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "scribe.v1.SearchAnnotationsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "canvas_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchAnnotationsRequest {
    return new SearchAnnotationsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchAnnotationsRequest {
    return new SearchAnnotationsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchAnnotationsRequest {
    return new SearchAnnotationsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SearchAnnotationsRequest | PlainMessage<SearchAnnotationsRequest> | undefined, b: SearchAnnotationsRequest | PlainMessage<SearchAnnotationsRequest> | undefined): boolean {
    return proto3.util.equals(SearchAnnotationsRequest, a, b);
  }
}

/**
 * @generated from message scribe.v1.SearchAnnotationsResponse
 */
export class SearchAnnotationsResponse extends Message<SearchAnnotationsResponse> {
  /**
   * Full IIIF AnnotationPage JSON, serialised as string for round-trip fidelity.
   *
   * @generated from field: string annotation_page_json = 1;
   */
  annotationPageJson = "";

  constructor(data?: PartialMessage<SearchAnnotationsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "scribe.v1.SearchAnnotationsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "annotation_page_json", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchAnnotationsResponse {
    return new SearchAnnotationsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchAnnotationsResponse {
    return new SearchAnnotationsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchAnnotationsResponse {
    return new SearchAnnotationsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SearchAnnotationsResponse | PlainMessage<SearchAnnotationsResponse> | undefined, b: SearchAnnotationsResponse | PlainMessage<SearchAnnotationsResponse> | undefined): boolean {
    return proto3.util.equals(SearchAnnotationsResponse, a, b);
  }
}

/**
 * @generated from message scribe.v1.GetAnnotationRequest
 */
export class GetAnnotationRequest extends Message<GetAnnotationRequest> {
  /**
   * Bare ID suffix (the part after /v1/annotations/3/item/)
   *
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<GetAnnotationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "scribe.v1.GetAnnotationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAnnotationRequest {
    return new GetAnnotationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAnnotationRequest {
    return new GetAnnotationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAnnotationRequest {
    return new GetAnnotationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetAnnotationRequest | PlainMessage<GetAnnotationRequest> | undefined, b: GetAnnotationRequest | PlainMessage<GetAnnotationRequest> | undefined): boolean {
    return proto3.util.equals(GetAnnotationRequest, a, b);
  }
}

/**
 * @generated from message scribe.v1.GetAnnotationResponse
 */
export class GetAnnotationResponse extends Message<GetAnnotationResponse> {
  /**
   * @generated from field: string annotation_json = 1;
   */
  annotationJson = "";

  constructor(data?: PartialMessage<GetAnnotationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "scribe.v1.GetAnnotationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "annotation_json", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAnnotationResponse {
    return new GetAnnotationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAnnotationResponse {
    return new GetAnnotationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAnnotationResponse {
    return new GetAnnotationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetAnnotationResponse | PlainMessage<GetAnnotationResponse> | undefined, b: GetAnnotationResponse | PlainMessage<GetAnnotationResponse> | undefined): boolean {
    return proto3.util.equals(GetAnnotationResponse, a, b);
  }
}

/**
 * @generated from message scribe.v1.CreateAnnotationRequest
 */
export class CreateAnnotationRequest extends Message<CreateAnnotationRequest> {
  /**
   * @generated from field: string annotation_json = 1;
   */
  annotationJson = "";

  constructor(data?: PartialMessage<CreateAnnotationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "scribe.v1.CreateAnnotationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "annotation_json", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateAnnotationRequest {
    return new CreateAnnotationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateAnnotationRequest {
    return new CreateAnnotationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateAnnotationRequest {
    return new CreateAnnotationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateAnnotationRequest | PlainMessage<CreateAnnotationRequest> | undefined, b: CreateAnnotationRequest | PlainMessage<CreateAnnotationRequest> | undefined): boolean {
    return proto3.util.equals(CreateAnnotationRequest, a, b);
  }
}

/**
 * @generated from message scribe.v1.CreateAnnotationResponse
 */
export class CreateAnnotationResponse extends Message<CreateAnnotationResponse> {
  /**
   * @generated from field: string annotation_json = 1;
   */
  annotationJson = "";

  constructor(data?: PartialMessage<CreateAnnotationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "scribe.v1.CreateAnnotationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "annotation_json", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateAnnotationResponse {
    return new CreateAnnotationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateAnnotationResponse {
    return new CreateAnnotationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateAnnotationResponse {
    return new CreateAnnotationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateAnnotationResponse | PlainMessage<CreateAnnotationResponse> | undefined, b: CreateAnnotationResponse | PlainMessage<CreateAnnotationResponse> | undefined): boolean {
    return proto3.util.equals(CreateAnnotationResponse, a, b);
  }
}

/**
 * @generated from message scribe.v1.UpdateAnnotationRequest
 */
export class UpdateAnnotationRequest extends Message<UpdateAnnotationRequest> {
  /**
   * @generated from field: string annotation_json = 1;
   */
  annotationJson = "";

  constructor(data?: PartialMessage<UpdateAnnotationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "scribe.v1.UpdateAnnotationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "annotation_json", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateAnnotationRequest {
    return new UpdateAnnotationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateAnnotationRequest {
    return new UpdateAnnotationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateAnnotationRequest {
    return new UpdateAnnotationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateAnnotationRequest | PlainMessage<UpdateAnnotationRequest> | undefined, b: UpdateAnnotationRequest | PlainMessage<UpdateAnnotationRequest> | undefined): boolean {
    return proto3.util.equals(UpdateAnnotationRequest, a, b);
  }
}

/**
 * @generated from message scribe.v1.UpdateAnnotationResponse
 */
export class UpdateAnnotationResponse extends Message<UpdateAnnotationResponse> {
  /**
   * @generated from field: string annotation_json = 1;
   */
  annotationJson = "";

  constructor(data?: PartialMessage<UpdateAnnotationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "scribe.v1.UpdateAnnotationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "annotation_json", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateAnnotationResponse {
    return new UpdateAnnotationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateAnnotationResponse {
    return new UpdateAnnotationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateAnnotationResponse {
    return new UpdateAnnotationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateAnnotationResponse | PlainMessage<UpdateAnnotationResponse> | undefined, b: UpdateAnnotationResponse | PlainMessage<UpdateAnnotationResponse> | undefined): boolean {
    return proto3.util.equals(UpdateAnnotationResponse, a, b);
  }
}

/**
 * @generated from message scribe.v1.DeleteAnnotationRequest
 */
export class DeleteAnnotationRequest extends Message<DeleteAnnotationRequest> {
  /**
   * @generated from field: string uri = 1;
   */
  uri = "";

  constructor(data?: PartialMessage<DeleteAnnotationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "scribe.v1.DeleteAnnotationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteAnnotationRequest {
    return new DeleteAnnotationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteAnnotationRequest {
    return new DeleteAnnotationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteAnnotationRequest {
    return new DeleteAnnotationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteAnnotationRequest | PlainMessage<DeleteAnnotationRequest> | undefined, b: DeleteAnnotationRequest | PlainMessage<DeleteAnnotationRequest> | undefined): boolean {
    return proto3.util.equals(DeleteAnnotationRequest, a, b);
  }
}

/**
 * @generated from message scribe.v1.DeleteAnnotationResponse
 */
export class DeleteAnnotationResponse extends Message<DeleteAnnotationResponse> {
  constructor(data?: PartialMessage<DeleteAnnotationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "scribe.v1.DeleteAnnotationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteAnnotationResponse {
    return new DeleteAnnotationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteAnnotationResponse {
    return new DeleteAnnotationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteAnnotationResponse {
    return new DeleteAnnotationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteAnnotationResponse | PlainMessage<DeleteAnnotationResponse> | undefined, b: DeleteAnnotationResponse | PlainMessage<DeleteAnnotationResponse> | undefined): boolean {
    return proto3.util.equals(DeleteAnnotationResponse, a, b);
  }
}

/**
 * EnrichAnnotationRequest sends a IIIF annotation (one line or an entire
 * AnnotationPage) to Scribe's transcription service for improvement.
 * The caller provides the raw JSON and specifies the scope.
 *
 * @generated from message scribe.v1.EnrichAnnotationRequest
 */
export class EnrichAnnotationRequest extends Message<EnrichAnnotationRequest> {
  /**
   * "line" = single Annotation JSON; "page" = full AnnotationPage JSON
   *
   * @generated from field: string scope = 1;
   */
  scope = "";

  /**
   * @generated from field: string annotation_json = 2;
   */
  annotationJson = "";

  /**
   * Optional: override context used for transcription
   *
   * @generated from field: uint64 context_id = 3;
   */
  contextId = protoInt64.zero;

  constructor(data?: PartialMessage<EnrichAnnotationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "scribe.v1.EnrichAnnotationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "scope", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "annotation_json", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "context_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnrichAnnotationRequest {
    return new EnrichAnnotationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnrichAnnotationRequest {
    return new EnrichAnnotationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnrichAnnotationRequest {
    return new EnrichAnnotationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: EnrichAnnotationRequest | PlainMessage<EnrichAnnotationRequest> | undefined, b: EnrichAnnotationRequest | PlainMessage<EnrichAnnotationRequest> | undefined): boolean {
    return proto3.util.equals(EnrichAnnotationRequest, a, b);
  }
}

/**
 * @generated from message scribe.v1.EnrichAnnotationResponse
 */
export class EnrichAnnotationResponse extends Message<EnrichAnnotationResponse> {
  /**
   * @generated from field: string annotation_json = 1;
   */
  annotationJson = "";

  constructor(data?: PartialMessage<EnrichAnnotationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "scribe.v1.EnrichAnnotationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "annotation_json", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnrichAnnotationResponse {
    return new EnrichAnnotationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnrichAnnotationResponse {
    return new EnrichAnnotationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnrichAnnotationResponse {
    return new EnrichAnnotationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: EnrichAnnotationResponse | PlainMessage<EnrichAnnotationResponse> | undefined, b: EnrichAnnotationResponse | PlainMessage<EnrichAnnotationResponse> | undefined): boolean {
    return proto3.util.equals(EnrichAnnotationResponse, a, b);
  }
}

