// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file scribe/v1/context.proto (package scribe.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateContextRequest, CreateContextResponse, CreateSelectionRuleRequest, CreateSelectionRuleResponse, DeleteContextRequest, DeleteContextResponse, DeleteSelectionRuleRequest, DeleteSelectionRuleResponse, GetContextRequest, GetContextResponse, ListContextsRequest, ListContextsResponse, ListSelectionRulesRequest, ListSelectionRulesResponse, ResolveContextRequest, ResolveContextResponse, UpdateContextRequest, UpdateContextResponse } from "./context_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service scribe.v1.ContextService
 */
export const ContextService = {
  typeName: "scribe.v1.ContextService",
  methods: {
    /**
     * @generated from rpc scribe.v1.ContextService.ListContexts
     */
    listContexts: {
      name: "ListContexts",
      I: ListContextsRequest,
      O: ListContextsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scribe.v1.ContextService.GetContext
     */
    getContext: {
      name: "GetContext",
      I: GetContextRequest,
      O: GetContextResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scribe.v1.ContextService.CreateContext
     */
    createContext: {
      name: "CreateContext",
      I: CreateContextRequest,
      O: CreateContextResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scribe.v1.ContextService.UpdateContext
     */
    updateContext: {
      name: "UpdateContext",
      I: UpdateContextRequest,
      O: UpdateContextResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scribe.v1.ContextService.DeleteContext
     */
    deleteContext: {
      name: "DeleteContext",
      I: DeleteContextRequest,
      O: DeleteContextResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scribe.v1.ContextService.ListSelectionRules
     */
    listSelectionRules: {
      name: "ListSelectionRules",
      I: ListSelectionRulesRequest,
      O: ListSelectionRulesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scribe.v1.ContextService.CreateSelectionRule
     */
    createSelectionRule: {
      name: "CreateSelectionRule",
      I: CreateSelectionRuleRequest,
      O: CreateSelectionRuleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scribe.v1.ContextService.DeleteSelectionRule
     */
    deleteSelectionRule: {
      name: "DeleteSelectionRule",
      I: DeleteSelectionRuleRequest,
      O: DeleteSelectionRuleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc scribe.v1.ContextService.ResolveContext
     */
    resolveContext: {
      name: "ResolveContext",
      I: ResolveContextRequest,
      O: ResolveContextResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

