// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file scribe/v1/options/v1/auth.proto (package scribe.v1.options.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { MethodOptions } from "../../../../google/protobuf/descriptor_pb";
import { file_google_protobuf_descriptor } from "../../../../google/protobuf/descriptor_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file scribe/v1/options/v1/auth.proto.
 */
export const file_scribe_v1_options_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("Ch9zY3JpYmUvdjEvb3B0aW9ucy92MS9hdXRoLnByb3RvEhRzY3JpYmUudjEub3B0aW9ucy52MSK9AQoJQXV0aHpSdWxlEhcKD2FsbG93X2Fub255bW91cxgBIAEoCBI0CghyZXNvdXJjZRgCIAEoDjIiLnNjcmliZS52MS5vcHRpb25zLnYxLlJlc291cmNlVHlwZRIwCgVsZXZlbBgDIAEoDjIhLnNjcmliZS52MS5vcHRpb25zLnYxLkFjY2Vzc0xldmVsEhkKEXJlc291cmNlX2lkX2ZpZWxkGAQgASgJEhQKDHNlc3Npb25fb25seRgFIAEoCCryAgoMUmVzb3VyY2VUeXBlEh0KGVJFU09VUkNFX1RZUEVfVU5TUEVDSUZJRUQQABIYChRSRVNPVVJDRV9UWVBFX1NZU1RFTRABEhYKElJFU09VUkNFX1RZUEVfVVNFUhACEhYKElJFU09VUkNFX1RZUEVfSVRFTRADEhwKGFJFU09VUkNFX1RZUEVfSVRFTV9JTUFHRRAEEhkKFVJFU09VUkNFX1RZUEVfQ09OVEVYVBAFEiMKH1JFU09VUkNFX1RZUEVfVFJBTlNDUklQVElPTl9KT0IQBhIbChdSRVNPVVJDRV9UWVBFX1dPUktTUEFDRRAHEh4KGlJFU09VUkNFX1RZUEVfVVBMT0FEX0JBVENIEAgSIAocUkVTT1VSQ0VfVFlQRV9TRUxFQ1RJT05fUlVMRRAJEhkKFVJFU09VUkNFX1RZUEVfQVBJX0tFWRAKEiEKHVJFU09VUkNFX1RZUEVfUFJPVklERVJfU0VDUkVUEAsqcgoLQWNjZXNzTGV2ZWwSHAoYQUNDRVNTX0xFVkVMX1VOU1BFQ0lGSUVEEAASFQoRQUNDRVNTX0xFVkVMX1JFQUQQARIWChJBQ0NFU1NfTEVWRUxfV1JJVEUQAhIWChJBQ0NFU1NfTEVWRUxfQURNSU4QAzpXCgVhdXRoehIeLmdvb2dsZS5wcm90b2J1Zi5NZXRob2RPcHRpb25zGNKGAyABKAsyHy5zY3JpYmUudjEub3B0aW9ucy52MS5BdXRoelJ1bGVSBWF1dGh6QuwBChhjb20uc2NyaWJlLnYxLm9wdGlvbnMudjFCCUF1dGhQcm90b1ABWlJnaXRodWIuY29tL2xlaGlnaC11bml2ZXJzaXR5LWxpYnJhcmllcy9zY3JpYmUvcHJvdG8vc2NyaWJlL3YxL29wdGlvbnMvdjE7b3B0aW9uc3YxogIDU1ZPqgIUU2NyaWJlLlYxLk9wdGlvbnMuVjHKAhRTY3JpYmVcVjFcT3B0aW9uc1xWMeICIFNjcmliZVxWMVxPcHRpb25zXFYxXEdQQk1ldGFkYXRh6gIXU2NyaWJlOjpWMTo6T3B0aW9uczo6VjFiBnByb3RvMw", [file_google_protobuf_descriptor]);

/**
 * @generated from message scribe.v1.options.v1.AuthzRule
 */
export type AuthzRule = Message<"scribe.v1.options.v1.AuthzRule"> & {
  /**
   * @generated from field: bool allow_anonymous = 1;
   */
  allowAnonymous: boolean;

  /**
   * @generated from field: scribe.v1.options.v1.ResourceType resource = 2;
   */
  resource: ResourceType;

  /**
   * @generated from field: scribe.v1.options.v1.AccessLevel level = 3;
   */
  level: AccessLevel;

  /**
   * @generated from field: string resource_id_field = 4;
   */
  resourceIdField: string;

  /**
   * Restricts browser account/workspace administration to an interactive
   * session. Delegated API keys and external JWTs cannot authorize the RPC.
   *
   * @generated from field: bool session_only = 5;
   */
  sessionOnly: boolean;
};

/**
 * Describes the message scribe.v1.options.v1.AuthzRule.
 * Use `create(AuthzRuleSchema)` to create a new message.
 */
export const AuthzRuleSchema: GenMessage<AuthzRule> = /*@__PURE__*/
  messageDesc(file_scribe_v1_options_v1_auth, 0);

/**
 * @generated from enum scribe.v1.options.v1.ResourceType
 */
export enum ResourceType {
  /**
   * @generated from enum value: RESOURCE_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: RESOURCE_TYPE_SYSTEM = 1;
   */
  SYSTEM = 1,

  /**
   * @generated from enum value: RESOURCE_TYPE_USER = 2;
   */
  USER = 2,

  /**
   * @generated from enum value: RESOURCE_TYPE_ITEM = 3;
   */
  ITEM = 3,

  /**
   * @generated from enum value: RESOURCE_TYPE_ITEM_IMAGE = 4;
   */
  ITEM_IMAGE = 4,

  /**
   * @generated from enum value: RESOURCE_TYPE_CONTEXT = 5;
   */
  CONTEXT = 5,

  /**
   * @generated from enum value: RESOURCE_TYPE_TRANSCRIPTION_JOB = 6;
   */
  TRANSCRIPTION_JOB = 6,

  /**
   * @generated from enum value: RESOURCE_TYPE_WORKSPACE = 7;
   */
  WORKSPACE = 7,

  /**
   * @generated from enum value: RESOURCE_TYPE_UPLOAD_BATCH = 8;
   */
  UPLOAD_BATCH = 8,

  /**
   * @generated from enum value: RESOURCE_TYPE_SELECTION_RULE = 9;
   */
  SELECTION_RULE = 9,

  /**
   * @generated from enum value: RESOURCE_TYPE_API_KEY = 10;
   */
  API_KEY = 10,

  /**
   * @generated from enum value: RESOURCE_TYPE_PROVIDER_SECRET = 11;
   */
  PROVIDER_SECRET = 11,
}

/**
 * Describes the enum scribe.v1.options.v1.ResourceType.
 */
export const ResourceTypeSchema: GenEnum<ResourceType> = /*@__PURE__*/
  enumDesc(file_scribe_v1_options_v1_auth, 0);

/**
 * @generated from enum scribe.v1.options.v1.AccessLevel
 */
export enum AccessLevel {
  /**
   * @generated from enum value: ACCESS_LEVEL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ACCESS_LEVEL_READ = 1;
   */
  READ = 1,

  /**
   * @generated from enum value: ACCESS_LEVEL_WRITE = 2;
   */
  WRITE = 2,

  /**
   * @generated from enum value: ACCESS_LEVEL_ADMIN = 3;
   */
  ADMIN = 3,
}

/**
 * Describes the enum scribe.v1.options.v1.AccessLevel.
 */
export const AccessLevelSchema: GenEnum<AccessLevel> = /*@__PURE__*/
  enumDesc(file_scribe_v1_options_v1_auth, 1);

/**
 * @generated from extension: scribe.v1.options.v1.AuthzRule authz = 50002;
 */
export const authz: GenExtension<MethodOptions, AuthzRule> = /*@__PURE__*/
  extDesc(file_scribe_v1_options_v1_auth, 0);

