# syntax=docker/dockerfile:1.28@sha256:bb22d9815c728170f72750f4e5b0d672e06176142e1d602c7e66c050100b7e5b
FROM golang:1.27.2-alpine@sha256:f92b6ef800e499660581efdabdf25d9d817a9d124eaf900924f0504e7e27e12d AS builder
WORKDIR /src
COPY cmd/cloudsql/main.go ./main.go
RUN CGO_ENABLED=0 go build -o /scribe-cloudsql ./main.go
FROM gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.26.0@sha256:86e4f3cc266020e7ee07740df78d7511e2c340c274b56f84d80b7251913af9ad AS cloudsql
FROM ghcr.io/libops/triplet:v1.2.4@sha256:1a1abbae387129c6a157005fdab43f0256adc6a1652a0144df58cdcce825cd20
COPY --from=builder /scribe-cloudsql /app/scribe-cloudsql
COPY --from=cloudsql /cloud-sql-proxy /cloud-sql-proxy
COPY config/triplet-cloud-run.yaml /etc/triplet/cloud-run.yaml
CMD ["-config", "/etc/triplet/cloud-run.yaml"]
