# syntax=docker/dockerfile:1.27@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e
FROM python:3.14.7-slim-bookworm@sha256:9ab8d9c8514b44f90cf0029dd42fdd7e9e211e639c8b995304cc04568dee900f

COPY requirements-docs.txt /tmp/requirements-docs.txt
RUN python -m pip install --disable-pip-version-check --no-cache-dir --require-hashes -r /tmp/requirements-docs.txt

WORKDIR /workspace
ENTRYPOINT ["zensical"]
