# syntax=docker/dockerfile:1.25@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12
FROM python:3.14.6-slim-bookworm@sha256:86f975aca15cf04a40b399eebede9aea7c82eae084d1f1a0a6ef6bcaae871a30

COPY requirements-docs.txt /tmp/requirements-docs.txt
RUN python -m pip install --disable-pip-version-check --no-cache-dir --require-hashes -r /tmp/requirements-docs.txt

WORKDIR /workspace
ENTRYPOINT ["zensical"]
