# syntax=docker/dockerfile:1.27@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e
FROM golang:1.27.1-alpine@sha256:8a5910f31396cd4d89662f56c68b3ae31d374308270a1c3bd96672ee5ed43414 AS builder
WORKDIR /src
COPY cmd/cloudsql/main.go ./main.go
RUN CGO_ENABLED=0 go build -o /scribe-cloudsql ./main.go
FROM gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.18.3@sha256:4f9071e7fb8bc0acc0c66dbbaa292d7c0e6337003ccd29f75e1431f8f8c3fce6 AS cloudsql
FROM ghcr.io/libops/triplet:v1.2.4@sha256:1a1abbae387129c6a157005fdab43f0256adc6a1652a0144df58cdcce825cd20
COPY --from=builder /scribe-cloudsql /app/scribe-cloudsql
COPY --from=cloudsql /cloud-sql-proxy /cloud-sql-proxy
COPY config/triplet-cloud-run.yaml /etc/triplet/cloud-run.yaml
CMD ["-config", "/etc/triplet/cloud-run.yaml"]
