CREATE TABLE IF NOT EXISTS ocr_runs (
  session_id VARCHAR(128) PRIMARY KEY,
  image_url TEXT NOT NULL,
  model VARCHAR(255) NOT NULL,
  original_hocr LONGTEXT NOT NULL,
  original_text LONGTEXT NOT NULL,
  corrected_hocr LONGTEXT NULL,
  corrected_text LONGTEXT NULL,
  edit_count INT NOT NULL DEFAULT 0,
  levenshtein_distance INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
