ALTER TABLE ocr_runs
  ADD COLUMN IF NOT EXISTS box_edit_count INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS boxes_added INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS boxes_deleted INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS box_change_score DOUBLE NOT NULL DEFAULT 0;
