CREATE TABLE IF NOT EXISTS annotations (
  id VARCHAR(512) PRIMARY KEY,
  canvas_uri VARCHAR(1024) NOT NULL,
  payload LONGTEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_annotations_canvas_uri (canvas_uri(255))
);
