[Unit]
RequiresMountsFor=/mnt/disks/backups
ConditionPathIsMountPoint=/mnt/disks/backups

[Service]
Environment=MARIADB_BACKUP_ROOT=/mnt/disks/backups/mariadb
Environment=SCRIBE_MARIADB_BACKUP_RETAIN_COMPLETED=1
ExecStartPre=/bin/bash /home/cloud-compose/scribe-prune-mariadb-backups.sh
ExecStartPost=/bin/bash /home/cloud-compose/scribe-mark-mariadb-backup.sh
ExecStartPost=/bin/bash /home/cloud-compose/scribe-prune-mariadb-backups.sh
