// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotation_publications.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getPublishedAnnotationPage = `-- name: GetPublishedAnnotationPage :one
SELECT
  workspace_id,
  item_image_id,
  page_id,
  canvas_uri,
  payload,
  published_revision,
  published_by_user_id,
  published_at,
  created_at,
  updated_at
FROM published_annotation_pages
WHERE item_image_id = ?
LIMIT 1
`

func (q *Queries) GetPublishedAnnotationPage(ctx context.Context, itemImageID uint64) (PublishedAnnotationPage, error) {
	row := q.db.QueryRowContext(ctx, getPublishedAnnotationPage, itemImageID)
	var i PublishedAnnotationPage
	err := row.Scan(
		&i.WorkspaceID,
		&i.ItemImageID,
		&i.PageID,
		&i.CanvasUri,
		&i.Payload,
		&i.PublishedRevision,
		&i.PublishedByUserID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedAnnotationPageForUpdate = `-- name: GetPublishedAnnotationPageForUpdate :one
SELECT
  workspace_id,
  item_image_id,
  page_id,
  canvas_uri,
  payload,
  published_revision,
  published_by_user_id,
  published_at,
  created_at,
  updated_at
FROM published_annotation_pages
WHERE workspace_id = ?
  AND item_image_id = ?
LIMIT 1
FOR UPDATE
`

type GetPublishedAnnotationPageForUpdateParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	ItemImageID uint64 `json:"item_image_id"`
}

func (q *Queries) GetPublishedAnnotationPageForUpdate(ctx context.Context, arg GetPublishedAnnotationPageForUpdateParams) (PublishedAnnotationPage, error) {
	row := q.db.QueryRowContext(ctx, getPublishedAnnotationPageForUpdate, arg.WorkspaceID, arg.ItemImageID)
	var i PublishedAnnotationPage
	err := row.Scan(
		&i.WorkspaceID,
		&i.ItemImageID,
		&i.PageID,
		&i.CanvasUri,
		&i.Payload,
		&i.PublishedRevision,
		&i.PublishedByUserID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPublishedAnnotationPage = `-- name: InsertPublishedAnnotationPage :exec
INSERT INTO published_annotation_pages (
  workspace_id,
  item_image_id,
  page_id,
  canvas_uri,
  payload,
  published_revision,
  published_by_user_id,
  published_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
`

type InsertPublishedAnnotationPageParams struct {
	WorkspaceID       uint64        `json:"workspace_id"`
	ItemImageID       uint64        `json:"item_image_id"`
	PageID            string        `json:"page_id"`
	CanvasUri         string        `json:"canvas_uri"`
	Payload           string        `json:"payload"`
	PublishedRevision uint64        `json:"published_revision"`
	PublishedByUserID sql.NullInt64 `json:"published_by_user_id"`
	PublishedAt       time.Time     `json:"published_at"`
}

func (q *Queries) InsertPublishedAnnotationPage(ctx context.Context, arg InsertPublishedAnnotationPageParams) error {
	_, err := q.db.ExecContext(ctx, insertPublishedAnnotationPage,
		arg.WorkspaceID,
		arg.ItemImageID,
		arg.PageID,
		arg.CanvasUri,
		arg.Payload,
		arg.PublishedRevision,
		arg.PublishedByUserID,
		arg.PublishedAt,
	)
	return err
}

const listPublishedItemAnnotationManifestReferences = `-- name: ListPublishedItemAnnotationManifestReferences :many
SELECT
  pap.workspace_id,
  pap.item_image_id,
  pap.page_id,
  pap.canvas_uri,
  pap.published_revision,
  pap.published_at
FROM items i
JOIN item_images ii
  ON ii.item_id = i.id
JOIN published_annotation_pages pap
  ON pap.workspace_id = i.workspace_id
 AND pap.item_image_id = ii.id
WHERE i.id = ?
ORDER BY ii.sequence ASC, ii.id ASC
`

type ListPublishedItemAnnotationManifestReferencesRow struct {
	WorkspaceID       uint64    `json:"workspace_id"`
	ItemImageID       uint64    `json:"item_image_id"`
	PageID            string    `json:"page_id"`
	CanvasUri         string    `json:"canvas_uri"`
	PublishedRevision uint64    `json:"published_revision"`
	PublishedAt       time.Time `json:"published_at"`
}

func (q *Queries) ListPublishedItemAnnotationManifestReferences(ctx context.Context, itemID string) ([]ListPublishedItemAnnotationManifestReferencesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedItemAnnotationManifestReferences, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedItemAnnotationManifestReferencesRow{}
	for rows.Next() {
		var i ListPublishedItemAnnotationManifestReferencesRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ItemImageID,
			&i.PageID,
			&i.CanvasUri,
			&i.PublishedRevision,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAnnotationPageForPublication = `-- name: LockAnnotationPageForPublication :one
SELECT
  workspace_id,
  item_image_id,
  page_id,
  canvas_uri,
  payload,
  revision,
  updated_by_user_id,
  created_at,
  updated_at
FROM annotation_pages
WHERE workspace_id = ?
  AND item_image_id = ?
LIMIT 1
FOR UPDATE
`

type LockAnnotationPageForPublicationParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	ItemImageID uint64 `json:"item_image_id"`
}

func (q *Queries) LockAnnotationPageForPublication(ctx context.Context, arg LockAnnotationPageForPublicationParams) (AnnotationPage, error) {
	row := q.db.QueryRowContext(ctx, lockAnnotationPageForPublication, arg.WorkspaceID, arg.ItemImageID)
	var i AnnotationPage
	err := row.Scan(
		&i.WorkspaceID,
		&i.ItemImageID,
		&i.PageID,
		&i.CanvasUri,
		&i.Payload,
		&i.Revision,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const publishedImageURLExists = `-- name: PublishedImageURLExists :one
SELECT EXISTS(
  SELECT 1
  FROM item_images ii
  JOIN items i
    ON i.id = ii.item_id
   AND i.workspace_id = ii.workspace_id
  JOIN workspaces w
    ON w.id = ii.workspace_id
  JOIN published_annotation_pages pap
    ON pap.item_image_id = ii.id
   AND pap.workspace_id = ii.workspace_id
  WHERE ii.image_url = ?
) AS is_published
`

func (q *Queries) PublishedImageURLExists(ctx context.Context, imageUrl string) (bool, error) {
	row := q.db.QueryRowContext(ctx, publishedImageURLExists, imageUrl)
	var is_published bool
	err := row.Scan(&is_published)
	return is_published, err
}

const updatePublishedAnnotationPage = `-- name: UpdatePublishedAnnotationPage :execrows
UPDATE published_annotation_pages
SET
  page_id = ?,
  canvas_uri = ?,
  payload = ?,
  published_revision = ?,
  published_by_user_id = ?,
  published_at = ?,
  updated_at = CURRENT_TIMESTAMP(6)
WHERE workspace_id = ?
  AND item_image_id = ?
`

type UpdatePublishedAnnotationPageParams struct {
	PageID            string        `json:"page_id"`
	CanvasUri         string        `json:"canvas_uri"`
	Payload           string        `json:"payload"`
	PublishedRevision uint64        `json:"published_revision"`
	PublishedByUserID sql.NullInt64 `json:"published_by_user_id"`
	PublishedAt       time.Time     `json:"published_at"`
	WorkspaceID       uint64        `json:"workspace_id"`
	ItemImageID       uint64        `json:"item_image_id"`
}

func (q *Queries) UpdatePublishedAnnotationPage(ctx context.Context, arg UpdatePublishedAnnotationPageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePublishedAnnotationPage,
		arg.PageID,
		arg.CanvasUri,
		arg.Payload,
		arg.PublishedRevision,
		arg.PublishedByUserID,
		arg.PublishedAt,
		arg.WorkspaceID,
		arg.ItemImageID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
