// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: annotations.sql

package db

import (
	"context"
	"database/sql"
)

const deleteAnnotationManual = `-- name: DeleteAnnotationManual :exec
DELETE FROM annotations
WHERE id = ?
`

func (q *Queries) DeleteAnnotationManual(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAnnotationManual, id)
	return err
}

const deleteAnnotationsByCanvasManual = `-- name: DeleteAnnotationsByCanvasManual :exec
DELETE FROM annotations
WHERE canvas_uri = ?
`

func (q *Queries) DeleteAnnotationsByCanvasManual(ctx context.Context, canvasUri string) error {
	_, err := q.db.ExecContext(ctx, deleteAnnotationsByCanvasManual, canvasUri)
	return err
}

const getAnnotationManual = `-- name: GetAnnotationManual :one
SELECT
  id,
  canvas_uri,
  payload,
  created_at,
  updated_at
FROM annotations
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAnnotationManual(ctx context.Context, id string) (Annotation, error) {
	row := q.db.QueryRowContext(ctx, getAnnotationManual, id)
	var i Annotation
	err := row.Scan(
		&i.ID,
		&i.CanvasUri,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchAnnotationsByCanvasManual = `-- name: SearchAnnotationsByCanvasManual :many
SELECT
  id,
  canvas_uri,
  payload,
  created_at,
  updated_at
FROM annotations
WHERE canvas_uri IN (?, ?)
ORDER BY updated_at ASC
`

type SearchAnnotationsByCanvasManualParams struct {
	CanvasUri           string `json:"canvas_uri"`
	NormalizedCanvasUri string `json:"normalized_canvas_uri"`
}

func (q *Queries) SearchAnnotationsByCanvasManual(ctx context.Context, arg SearchAnnotationsByCanvasManualParams) ([]Annotation, error) {
	rows, err := q.db.QueryContext(ctx, searchAnnotationsByCanvasManual, arg.CanvasUri, arg.NormalizedCanvasUri)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Annotation{}
	for rows.Next() {
		var i Annotation
		if err := rows.Scan(
			&i.ID,
			&i.CanvasUri,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnotationManual = `-- name: UpdateAnnotationManual :execresult
UPDATE annotations
SET
  canvas_uri = ?,
  payload = ?
WHERE id = ?
`

type UpdateAnnotationManualParams struct {
	CanvasUri string `json:"canvas_uri"`
	Payload   string `json:"payload"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateAnnotationManual(ctx context.Context, arg UpdateAnnotationManualParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateAnnotationManual, arg.CanvasUri, arg.Payload, arg.ID)
}

const upsertAnnotationManual = `-- name: UpsertAnnotationManual :exec
INSERT INTO annotations (id, canvas_uri, payload)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE
  canvas_uri = VALUES(canvas_uri),
  payload = VALUES(payload)
`

type UpsertAnnotationManualParams struct {
	ID        string `json:"id"`
	CanvasUri string `json:"canvas_uri"`
	Payload   string `json:"payload"`
}

func (q *Queries) UpsertAnnotationManual(ctx context.Context, arg UpsertAnnotationManualParams) error {
	_, err := q.db.ExecContext(ctx, upsertAnnotationManual, arg.ID, arg.CanvasUri, arg.Payload)
	return err
}
