// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const acquireIdentityConvergenceLockManual = `-- name: AcquireIdentityConvergenceLockManual :one
SELECT GET_LOCK(?, 30)
`

// Name-locking is connection scoped and intentionally wraps the entire
// identity transaction. The caller hashes subject/email values before use so
// lock names never expose identity data through MariaDB diagnostics.
func (q *Queries) AcquireIdentityConvergenceLockManual(ctx context.Context, lockName string) (bool, error) {
	row := q.db.QueryRowContext(ctx, acquireIdentityConvergenceLockManual, lockName)
	var get_lock bool
	err := row.Scan(&get_lock)
	return get_lock, err
}

const addWorkspaceMemberManual = `-- name: AddWorkspaceMemberManual :exec
INSERT INTO workspace_members (
  workspace_id,
  user_id,
  role
) VALUES (
  ?,
  ?,
  ?
)
`

type AddWorkspaceMemberManualParams struct {
	WorkspaceID uint64               `json:"workspace_id"`
	UserID      uint64               `json:"user_id"`
	Role        WorkspaceMembersRole `json:"role"`
}

func (q *Queries) AddWorkspaceMemberManual(ctx context.Context, arg AddWorkspaceMemberManualParams) error {
	_, err := q.db.ExecContext(ctx, addWorkspaceMemberManual, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const countAuthSessionsForUserManual = `-- name: CountAuthSessionsForUserManual :one
SELECT COUNT(*) FROM auth_sessions WHERE user_id = ?
`

func (q *Queries) CountAuthSessionsForUserManual(ctx context.Context, userID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuthSessionsForUserManual, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspaceAccessByUserManual = `-- name: CountWorkspaceAccessByUserManual :one
SELECT COUNT(*) FROM workspace_members WHERE user_id = ?
`

func (q *Queries) CountWorkspaceAccessByUserManual(ctx context.Context, userID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkspaceAccessByUserManual, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspaceAdminsManual = `-- name: CountWorkspaceAdminsManual :one
SELECT COUNT(*)
FROM workspace_members
WHERE workspace_id = ?
  AND role = 'admin'
`

func (q *Queries) CountWorkspaceAdminsManual(ctx context.Context, workspaceID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkspaceAdminsManual, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspaceMembersManual = `-- name: CountWorkspaceMembersManual :one
SELECT COUNT(*) FROM workspace_members WHERE workspace_id = ?
`

func (q *Queries) CountWorkspaceMembersManual(ctx context.Context, workspaceID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkspaceMembersManual, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthSessionManual = `-- name: CreateAuthSessionManual :exec
INSERT INTO auth_sessions (
  token_hash,
  user_id,
  expires_at,
  user_agent,
  ip_address
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?
)
`

type CreateAuthSessionManualParams struct {
	TokenHash string         `json:"token_hash"`
	UserID    uint64         `json:"user_id"`
	ExpiresAt time.Time      `json:"expires_at"`
	UserAgent sql.NullString `json:"user_agent"`
	IpAddress sql.NullString `json:"ip_address"`
}

func (q *Queries) CreateAuthSessionManual(ctx context.Context, arg CreateAuthSessionManualParams) error {
	_, err := q.db.ExecContext(ctx, createAuthSessionManual,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	return err
}

const createUserManual = `-- name: CreateUserManual :execresult
INSERT INTO users (
  name,
  email,
  google_subject,
  picture_url,
  is_admin,
  last_login_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  NOW()
)
`

type CreateUserManualParams struct {
	Name          string         `json:"name"`
	Email         sql.NullString `json:"email"`
	GoogleSubject sql.NullString `json:"google_subject"`
	PictureUrl    sql.NullString `json:"picture_url"`
	IsAdmin       bool           `json:"is_admin"`
}

func (q *Queries) CreateUserManual(ctx context.Context, arg CreateUserManualParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUserManual,
		arg.Name,
		arg.Email,
		arg.GoogleSubject,
		arg.PictureUrl,
		arg.IsAdmin,
	)
}

const createWorkspaceManual = `-- name: CreateWorkspaceManual :execresult
INSERT INTO workspaces (
  owner_user_id,
  name,
  slug,
  is_personal,
  created_by_user_id
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?
)
`

type CreateWorkspaceManualParams struct {
	OwnerUserID     sql.NullInt64 `json:"owner_user_id"`
	Name            string        `json:"name"`
	Slug            string        `json:"slug"`
	IsPersonal      bool          `json:"is_personal"`
	CreatedByUserID sql.NullInt64 `json:"created_by_user_id"`
}

func (q *Queries) CreateWorkspaceManual(ctx context.Context, arg CreateWorkspaceManualParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createWorkspaceManual,
		arg.OwnerUserID,
		arg.Name,
		arg.Slug,
		arg.IsPersonal,
		arg.CreatedByUserID,
	)
}

const createWorkspaceMemberManual = `-- name: CreateWorkspaceMemberManual :exec
INSERT IGNORE INTO workspace_members (
  workspace_id,
  user_id,
  role
) VALUES (
  ?,
  ?,
  ?
)
`

type CreateWorkspaceMemberManualParams struct {
	WorkspaceID uint64               `json:"workspace_id"`
	UserID      uint64               `json:"user_id"`
	Role        WorkspaceMembersRole `json:"role"`
}

func (q *Queries) CreateWorkspaceMemberManual(ctx context.Context, arg CreateWorkspaceMemberManualParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspaceMemberManual, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const deleteAuthSessionByTokenHashManual = `-- name: DeleteAuthSessionByTokenHashManual :exec
DELETE FROM auth_sessions
WHERE token_hash = ?
`

func (q *Queries) DeleteAuthSessionByTokenHashManual(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthSessionByTokenHashManual, tokenHash)
	return err
}

const deleteExpiredAuthSessionsBatchManual = `-- name: DeleteExpiredAuthSessionsBatchManual :execresult
DELETE FROM auth_sessions
WHERE expires_at <= ?
ORDER BY expires_at ASC, id ASC
LIMIT 1000
`

func (q *Queries) DeleteExpiredAuthSessionsBatchManual(ctx context.Context, cutoff time.Time) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteExpiredAuthSessionsBatchManual, cutoff)
}

const deleteExpiredAuthSessionsForUserManual = `-- name: DeleteExpiredAuthSessionsForUserManual :exec
DELETE FROM auth_sessions
WHERE user_id = ? AND expires_at <= NOW()
`

func (q *Queries) DeleteExpiredAuthSessionsForUserManual(ctx context.Context, userID uint64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAuthSessionsForUserManual, userID)
	return err
}

const deleteOldestAuthSessionForUserManual = `-- name: DeleteOldestAuthSessionForUserManual :execresult
DELETE FROM auth_sessions
WHERE user_id = ?
ORDER BY created_at ASC, id ASC
LIMIT 1
`

func (q *Queries) DeleteOldestAuthSessionForUserManual(ctx context.Context, userID uint64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteOldestAuthSessionForUserManual, userID)
}

const deleteWorkspaceMemberManual = `-- name: DeleteWorkspaceMemberManual :execresult
DELETE FROM workspace_members
WHERE workspace_id = ?
  AND user_id = ?
`

type DeleteWorkspaceMemberManualParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	UserID      uint64 `json:"user_id"`
}

func (q *Queries) DeleteWorkspaceMemberManual(ctx context.Context, arg DeleteWorkspaceMemberManualParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteWorkspaceMemberManual, arg.WorkspaceID, arg.UserID)
}

const getAuthSessionByTokenHashManual = `-- name: GetAuthSessionByTokenHashManual :one
SELECT
  id,
  token_hash,
  user_id,
  expires_at,
  user_agent,
  ip_address,
  created_at
FROM auth_sessions
WHERE token_hash = ?
LIMIT 1
`

func (q *Queries) GetAuthSessionByTokenHashManual(ctx context.Context, tokenHash string) (AuthSession, error) {
	row := q.db.QueryRowContext(ctx, getAuthSessionByTokenHashManual, tokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonalWorkspaceByUserIDManual = `-- name: GetPersonalWorkspaceByUserIDManual :one
SELECT
  id,
  owner_user_id,
  name,
  slug,
  is_personal,
  created_by_user_id,
  created_at,
  updated_at
FROM workspaces
WHERE owner_user_id = ?
  AND is_personal = TRUE
LIMIT 1
`

func (q *Queries) GetPersonalWorkspaceByUserIDManual(ctx context.Context, userID sql.NullInt64) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getPersonalWorkspaceByUserIDManual, userID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.IsPersonal,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailManual = `-- name: GetUserByEmailManual :one
SELECT
  id,
  name,
  email,
  google_subject,
  picture_url,
  is_admin,
  last_login_at,
  created_at,
  updated_at
FROM users
WHERE email = ?
LIMIT 1
`

type GetUserByEmailManualRow struct {
	ID            uint64         `json:"id"`
	Name          string         `json:"name"`
	Email         sql.NullString `json:"email"`
	GoogleSubject sql.NullString `json:"google_subject"`
	PictureUrl    sql.NullString `json:"picture_url"`
	IsAdmin       bool           `json:"is_admin"`
	LastLoginAt   sql.NullTime   `json:"last_login_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

func (q *Queries) GetUserByEmailManual(ctx context.Context, email sql.NullString) (GetUserByEmailManualRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailManual, email)
	var i GetUserByEmailManualRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.GoogleSubject,
		&i.PictureUrl,
		&i.IsAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleSubjectManual = `-- name: GetUserByGoogleSubjectManual :one
SELECT
  id,
  name,
  email,
  google_subject,
  picture_url,
  is_admin,
  last_login_at,
  created_at,
  updated_at
FROM users
WHERE google_subject = ?
LIMIT 1
`

type GetUserByGoogleSubjectManualRow struct {
	ID            uint64         `json:"id"`
	Name          string         `json:"name"`
	Email         sql.NullString `json:"email"`
	GoogleSubject sql.NullString `json:"google_subject"`
	PictureUrl    sql.NullString `json:"picture_url"`
	IsAdmin       bool           `json:"is_admin"`
	LastLoginAt   sql.NullTime   `json:"last_login_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

func (q *Queries) GetUserByGoogleSubjectManual(ctx context.Context, googleSubject sql.NullString) (GetUserByGoogleSubjectManualRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleSubjectManual, googleSubject)
	var i GetUserByGoogleSubjectManualRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.GoogleSubject,
		&i.PictureUrl,
		&i.IsAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserManual = `-- name: GetUserManual :one
SELECT
  id,
  name,
  email,
  google_subject,
  picture_url,
  is_admin,
  last_login_at,
  created_at,
  updated_at
FROM users
WHERE id = ?
`

type GetUserManualRow struct {
	ID            uint64         `json:"id"`
	Name          string         `json:"name"`
	Email         sql.NullString `json:"email"`
	GoogleSubject sql.NullString `json:"google_subject"`
	PictureUrl    sql.NullString `json:"picture_url"`
	IsAdmin       bool           `json:"is_admin"`
	LastLoginAt   sql.NullTime   `json:"last_login_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

func (q *Queries) GetUserManual(ctx context.Context, id uint64) (GetUserManualRow, error) {
	row := q.db.QueryRowContext(ctx, getUserManual, id)
	var i GetUserManualRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.GoogleSubject,
		&i.PictureUrl,
		&i.IsAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceAccessManual = `-- name: GetWorkspaceAccessManual :one
SELECT w.id, w.owner_user_id, w.name, w.slug, w.is_personal, w.created_by_user_id, w.created_at, w.updated_at, wm.role
FROM workspaces w
JOIN workspace_members wm ON wm.workspace_id = w.id
WHERE w.id = ?
  AND wm.user_id = ?
LIMIT 1
`

type GetWorkspaceAccessManualParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	UserID      uint64 `json:"user_id"`
}

type GetWorkspaceAccessManualRow struct {
	Workspace Workspace            `json:"workspace"`
	Role      WorkspaceMembersRole `json:"role"`
}

func (q *Queries) GetWorkspaceAccessManual(ctx context.Context, arg GetWorkspaceAccessManualParams) (GetWorkspaceAccessManualRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceAccessManual, arg.WorkspaceID, arg.UserID)
	var i GetWorkspaceAccessManualRow
	err := row.Scan(
		&i.Workspace.ID,
		&i.Workspace.OwnerUserID,
		&i.Workspace.Name,
		&i.Workspace.Slug,
		&i.Workspace.IsPersonal,
		&i.Workspace.CreatedByUserID,
		&i.Workspace.CreatedAt,
		&i.Workspace.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getWorkspaceManual = `-- name: GetWorkspaceManual :one
SELECT
  id,
  owner_user_id,
  name,
  slug,
  is_personal,
  created_by_user_id,
  created_at,
  updated_at
FROM workspaces
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetWorkspaceManual(ctx context.Context, id uint64) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceManual, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.IsPersonal,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceMemberManual = `-- name: GetWorkspaceMemberManual :one
SELECT
  wm.workspace_id,
  wm.role,
  wm.created_at,
  u.id, u.name, u.email, u.google_subject, u.picture_url, u.is_admin, u.created_at, u.last_login_at, u.updated_at
FROM workspace_members wm
JOIN users u ON u.id = wm.user_id
WHERE wm.workspace_id = ?
  AND wm.user_id = ?
LIMIT 1
`

type GetWorkspaceMemberManualParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	UserID      uint64 `json:"user_id"`
}

type GetWorkspaceMemberManualRow struct {
	WorkspaceID uint64               `json:"workspace_id"`
	Role        WorkspaceMembersRole `json:"role"`
	CreatedAt   time.Time            `json:"created_at"`
	User        User                 `json:"user"`
}

func (q *Queries) GetWorkspaceMemberManual(ctx context.Context, arg GetWorkspaceMemberManualParams) (GetWorkspaceMemberManualRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceMemberManual, arg.WorkspaceID, arg.UserID)
	var i GetWorkspaceMemberManualRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.Role,
		&i.CreatedAt,
		&i.User.ID,
		&i.User.Name,
		&i.User.Email,
		&i.User.GoogleSubject,
		&i.User.PictureUrl,
		&i.User.IsAdmin,
		&i.User.CreatedAt,
		&i.User.LastLoginAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const listWorkspaceAccessByUserManual = `-- name: ListWorkspaceAccessByUserManual :many
SELECT w.id, w.owner_user_id, w.name, w.slug, w.is_personal, w.created_by_user_id, w.created_at, w.updated_at, wm.role
FROM workspaces w
JOIN workspace_members wm ON wm.workspace_id = w.id
WHERE wm.user_id = ?
ORDER BY w.is_personal DESC, w.name ASC
LIMIT 50
`

type ListWorkspaceAccessByUserManualRow struct {
	Workspace Workspace            `json:"workspace"`
	Role      WorkspaceMembersRole `json:"role"`
}

func (q *Queries) ListWorkspaceAccessByUserManual(ctx context.Context, userID uint64) ([]ListWorkspaceAccessByUserManualRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceAccessByUserManual, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceAccessByUserManualRow{}
	for rows.Next() {
		var i ListWorkspaceAccessByUserManualRow
		if err := rows.Scan(
			&i.Workspace.ID,
			&i.Workspace.OwnerUserID,
			&i.Workspace.Name,
			&i.Workspace.Slug,
			&i.Workspace.IsPersonal,
			&i.Workspace.CreatedByUserID,
			&i.Workspace.CreatedAt,
			&i.Workspace.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembersManual = `-- name: ListWorkspaceMembersManual :many
SELECT
  wm.workspace_id,
  wm.role,
  wm.created_at,
  u.id, u.name, u.email, u.google_subject, u.picture_url, u.is_admin, u.created_at, u.last_login_at, u.updated_at
FROM workspace_members wm
JOIN users u ON u.id = wm.user_id
WHERE wm.workspace_id = ?
ORDER BY FIELD(wm.role, 'admin', 'write', 'create', 'read'), LOWER(u.name), LOWER(COALESCE(u.email, ''))
LIMIT 100
`

type ListWorkspaceMembersManualRow struct {
	WorkspaceID uint64               `json:"workspace_id"`
	Role        WorkspaceMembersRole `json:"role"`
	CreatedAt   time.Time            `json:"created_at"`
	User        User                 `json:"user"`
}

func (q *Queries) ListWorkspaceMembersManual(ctx context.Context, workspaceID uint64) ([]ListWorkspaceMembersManualRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceMembersManual, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersManualRow{}
	for rows.Next() {
		var i ListWorkspaceMembersManualRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Role,
			&i.CreatedAt,
			&i.User.ID,
			&i.User.Name,
			&i.User.Email,
			&i.User.GoogleSubject,
			&i.User.PictureUrl,
			&i.User.IsAdmin,
			&i.User.CreatedAt,
			&i.User.LastLoginAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserByEmailForIdentityManual = `-- name: LockUserByEmailForIdentityManual :one
SELECT u.id, u.name, u.email, u.google_subject, u.picture_url, u.is_admin, u.created_at, u.last_login_at, u.updated_at
FROM users u
WHERE u.email = ?
LIMIT 1
FOR UPDATE
`

type LockUserByEmailForIdentityManualRow struct {
	User User `json:"user"`
}

func (q *Queries) LockUserByEmailForIdentityManual(ctx context.Context, email sql.NullString) (LockUserByEmailForIdentityManualRow, error) {
	row := q.db.QueryRowContext(ctx, lockUserByEmailForIdentityManual, email)
	var i LockUserByEmailForIdentityManualRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Name,
		&i.User.Email,
		&i.User.GoogleSubject,
		&i.User.PictureUrl,
		&i.User.IsAdmin,
		&i.User.CreatedAt,
		&i.User.LastLoginAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const lockUserByGoogleSubjectForIdentityManual = `-- name: LockUserByGoogleSubjectForIdentityManual :one
SELECT u.id, u.name, u.email, u.google_subject, u.picture_url, u.is_admin, u.created_at, u.last_login_at, u.updated_at
FROM users u
WHERE u.google_subject = ?
LIMIT 1
FOR UPDATE
`

type LockUserByGoogleSubjectForIdentityManualRow struct {
	User User `json:"user"`
}

func (q *Queries) LockUserByGoogleSubjectForIdentityManual(ctx context.Context, googleSubject sql.NullString) (LockUserByGoogleSubjectForIdentityManualRow, error) {
	row := q.db.QueryRowContext(ctx, lockUserByGoogleSubjectForIdentityManual, googleSubject)
	var i LockUserByGoogleSubjectForIdentityManualRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Name,
		&i.User.Email,
		&i.User.GoogleSubject,
		&i.User.PictureUrl,
		&i.User.IsAdmin,
		&i.User.CreatedAt,
		&i.User.LastLoginAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const lockUserForIdentityAdmissionManual = `-- name: LockUserForIdentityAdmissionManual :one
SELECT id FROM users WHERE id = ? FOR UPDATE
`

func (q *Queries) LockUserForIdentityAdmissionManual(ctx context.Context, userID uint64) (uint64, error) {
	row := q.db.QueryRowContext(ctx, lockUserForIdentityAdmissionManual, userID)
	var id uint64
	err := row.Scan(&id)
	return id, err
}

const lockWorkspaceForUseManual = `-- name: LockWorkspaceForUseManual :one
SELECT id
FROM workspaces
WHERE id = ?
LOCK IN SHARE MODE
`

func (q *Queries) LockWorkspaceForUseManual(ctx context.Context, id uint64) (uint64, error) {
	row := q.db.QueryRowContext(ctx, lockWorkspaceForUseManual, id)
	var id_2 uint64
	err := row.Scan(&id_2)
	return id_2, err
}

const lockWorkspaceManual = `-- name: LockWorkspaceManual :one
SELECT
  id,
  owner_user_id,
  name,
  slug,
  is_personal,
  created_by_user_id,
  created_at,
  updated_at
FROM workspaces
WHERE id = ?
FOR UPDATE
`

func (q *Queries) LockWorkspaceManual(ctx context.Context, id uint64) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, lockWorkspaceManual, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.IsPersonal,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockWorkspaceMemberRoleManual = `-- name: LockWorkspaceMemberRoleManual :one
SELECT role
FROM workspace_members
WHERE workspace_id = ?
  AND user_id = ?
FOR UPDATE
`

type LockWorkspaceMemberRoleManualParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	UserID      uint64 `json:"user_id"`
}

func (q *Queries) LockWorkspaceMemberRoleManual(ctx context.Context, arg LockWorkspaceMemberRoleManualParams) (WorkspaceMembersRole, error) {
	row := q.db.QueryRowContext(ctx, lockWorkspaceMemberRoleManual, arg.WorkspaceID, arg.UserID)
	var role WorkspaceMembersRole
	err := row.Scan(&role)
	return role, err
}

const releaseIdentityConvergenceLockManual = `-- name: ReleaseIdentityConvergenceLockManual :one
SELECT RELEASE_LOCK(?)
`

func (q *Queries) ReleaseIdentityConvergenceLockManual(ctx context.Context, lockName string) (bool, error) {
	row := q.db.QueryRowContext(ctx, releaseIdentityConvergenceLockManual, lockName)
	var release_lock bool
	err := row.Scan(&release_lock)
	return release_lock, err
}

const updateUserAuthProfileManual = `-- name: UpdateUserAuthProfileManual :exec
UPDATE users
SET
  name = ?,
  email = ?,
  google_subject = ?,
  picture_url = ?,
  is_admin = ?,
  last_login_at = NOW()
WHERE id = ?
`

type UpdateUserAuthProfileManualParams struct {
	Name          string         `json:"name"`
	Email         sql.NullString `json:"email"`
	GoogleSubject sql.NullString `json:"google_subject"`
	PictureUrl    sql.NullString `json:"picture_url"`
	IsAdmin       bool           `json:"is_admin"`
	ID            uint64         `json:"id"`
}

func (q *Queries) UpdateUserAuthProfileManual(ctx context.Context, arg UpdateUserAuthProfileManualParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAuthProfileManual,
		arg.Name,
		arg.Email,
		arg.GoogleSubject,
		arg.PictureUrl,
		arg.IsAdmin,
		arg.ID,
	)
	return err
}

const updateWorkspaceMemberRoleManual = `-- name: UpdateWorkspaceMemberRoleManual :execresult
UPDATE workspace_members
SET role = ?
WHERE workspace_id = ?
  AND user_id = ?
`

type UpdateWorkspaceMemberRoleManualParams struct {
	Role        WorkspaceMembersRole `json:"role"`
	WorkspaceID uint64               `json:"workspace_id"`
	UserID      uint64               `json:"user_id"`
}

func (q *Queries) UpdateWorkspaceMemberRoleManual(ctx context.Context, arg UpdateWorkspaceMemberRoleManualParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateWorkspaceMemberRoleManual, arg.Role, arg.WorkspaceID, arg.UserID)
}

const updateWorkspaceNameManual = `-- name: UpdateWorkspaceNameManual :execresult
UPDATE workspaces
SET name = ?
WHERE id = ?
`

type UpdateWorkspaceNameManualParams struct {
	Name string `json:"name"`
	ID   uint64 `json:"id"`
}

func (q *Queries) UpdateWorkspaceNameManual(ctx context.Context, arg UpdateWorkspaceNameManualParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateWorkspaceNameManual, arg.Name, arg.ID)
}
