// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createAuthSessionManual = `-- name: CreateAuthSessionManual :exec
INSERT INTO auth_sessions (
  token_hash,
  user_id,
  expires_at,
  user_agent,
  ip_address,
  last_seen_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  NOW()
)
`

type CreateAuthSessionManualParams struct {
	TokenHash string         `json:"token_hash"`
	UserID    uint64         `json:"user_id"`
	ExpiresAt time.Time      `json:"expires_at"`
	UserAgent sql.NullString `json:"user_agent"`
	IpAddress sql.NullString `json:"ip_address"`
}

func (q *Queries) CreateAuthSessionManual(ctx context.Context, arg CreateAuthSessionManualParams) error {
	_, err := q.db.ExecContext(ctx, createAuthSessionManual,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	return err
}

const createUserManual = `-- name: CreateUserManual :execresult
INSERT INTO users (
  name,
  email,
  google_subject,
  picture_url,
  is_admin,
  last_login_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  NOW()
)
`

type CreateUserManualParams struct {
	Name          string         `json:"name"`
	Email         sql.NullString `json:"email"`
	GoogleSubject sql.NullString `json:"google_subject"`
	PictureUrl    sql.NullString `json:"picture_url"`
	IsAdmin       bool           `json:"is_admin"`
}

func (q *Queries) CreateUserManual(ctx context.Context, arg CreateUserManualParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUserManual,
		arg.Name,
		arg.Email,
		arg.GoogleSubject,
		arg.PictureUrl,
		arg.IsAdmin,
	)
}

const createWorkspaceManual = `-- name: CreateWorkspaceManual :execresult
INSERT INTO workspaces (
  organization_id,
  owner_user_id,
  name,
  slug,
  is_personal,
  created_by_user_id
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
`

type CreateWorkspaceManualParams struct {
	OrganizationID  sql.NullInt64 `json:"organization_id"`
	OwnerUserID     sql.NullInt64 `json:"owner_user_id"`
	Name            string        `json:"name"`
	Slug            string        `json:"slug"`
	IsPersonal      bool          `json:"is_personal"`
	CreatedByUserID sql.NullInt64 `json:"created_by_user_id"`
}

func (q *Queries) CreateWorkspaceManual(ctx context.Context, arg CreateWorkspaceManualParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createWorkspaceManual,
		arg.OrganizationID,
		arg.OwnerUserID,
		arg.Name,
		arg.Slug,
		arg.IsPersonal,
		arg.CreatedByUserID,
	)
}

const createWorkspaceMemberManual = `-- name: CreateWorkspaceMemberManual :exec
INSERT IGNORE INTO workspace_members (
  workspace_id,
  user_id,
  role
) VALUES (
  ?,
  ?,
  ?
)
`

type CreateWorkspaceMemberManualParams struct {
	WorkspaceID uint64               `json:"workspace_id"`
	UserID      uint64               `json:"user_id"`
	Role        WorkspaceMembersRole `json:"role"`
}

func (q *Queries) CreateWorkspaceMemberManual(ctx context.Context, arg CreateWorkspaceMemberManualParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspaceMemberManual, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const deleteAuthSessionByTokenHashManual = `-- name: DeleteAuthSessionByTokenHashManual :exec
DELETE FROM auth_sessions
WHERE token_hash = ?
`

func (q *Queries) DeleteAuthSessionByTokenHashManual(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthSessionByTokenHashManual, tokenHash)
	return err
}

const getAuthSessionByTokenHashManual = `-- name: GetAuthSessionByTokenHashManual :one
SELECT
  id,
  token_hash,
  user_id,
  expires_at,
  user_agent,
  ip_address,
  last_seen_at,
  created_at
FROM auth_sessions
WHERE token_hash = ?
LIMIT 1
`

func (q *Queries) GetAuthSessionByTokenHashManual(ctx context.Context, tokenHash string) (AuthSession, error) {
	row := q.db.QueryRowContext(ctx, getAuthSessionByTokenHashManual, tokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonalWorkspaceByUserIDManual = `-- name: GetPersonalWorkspaceByUserIDManual :one
SELECT
  id,
  organization_id,
  owner_user_id,
  name,
  slug,
  is_personal,
  created_by_user_id,
  created_at,
  updated_at
FROM workspaces
WHERE owner_user_id = ?
  AND is_personal = TRUE
LIMIT 1
`

func (q *Queries) GetPersonalWorkspaceByUserIDManual(ctx context.Context, userID sql.NullInt64) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getPersonalWorkspaceByUserIDManual, userID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.IsPersonal,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailManual = `-- name: GetUserByEmailManual :one
SELECT
  id,
  name,
  email,
  google_subject,
  picture_url,
  is_admin,
  last_login_at,
  created_at,
  updated_at
FROM users
WHERE email = ?
LIMIT 1
`

type GetUserByEmailManualRow struct {
	ID            uint64         `json:"id"`
	Name          string         `json:"name"`
	Email         sql.NullString `json:"email"`
	GoogleSubject sql.NullString `json:"google_subject"`
	PictureUrl    sql.NullString `json:"picture_url"`
	IsAdmin       bool           `json:"is_admin"`
	LastLoginAt   sql.NullTime   `json:"last_login_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

func (q *Queries) GetUserByEmailManual(ctx context.Context, email sql.NullString) (GetUserByEmailManualRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailManual, email)
	var i GetUserByEmailManualRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.GoogleSubject,
		&i.PictureUrl,
		&i.IsAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleSubjectManual = `-- name: GetUserByGoogleSubjectManual :one
SELECT
  id,
  name,
  email,
  google_subject,
  picture_url,
  is_admin,
  last_login_at,
  created_at,
  updated_at
FROM users
WHERE google_subject = ?
LIMIT 1
`

type GetUserByGoogleSubjectManualRow struct {
	ID            uint64         `json:"id"`
	Name          string         `json:"name"`
	Email         sql.NullString `json:"email"`
	GoogleSubject sql.NullString `json:"google_subject"`
	PictureUrl    sql.NullString `json:"picture_url"`
	IsAdmin       bool           `json:"is_admin"`
	LastLoginAt   sql.NullTime   `json:"last_login_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

func (q *Queries) GetUserByGoogleSubjectManual(ctx context.Context, googleSubject sql.NullString) (GetUserByGoogleSubjectManualRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleSubjectManual, googleSubject)
	var i GetUserByGoogleSubjectManualRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.GoogleSubject,
		&i.PictureUrl,
		&i.IsAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserManual = `-- name: GetUserManual :one
SELECT
  id,
  name,
  email,
  google_subject,
  picture_url,
  is_admin,
  last_login_at,
  created_at,
  updated_at
FROM users
WHERE id = ?
`

type GetUserManualRow struct {
	ID            uint64         `json:"id"`
	Name          string         `json:"name"`
	Email         sql.NullString `json:"email"`
	GoogleSubject sql.NullString `json:"google_subject"`
	PictureUrl    sql.NullString `json:"picture_url"`
	IsAdmin       bool           `json:"is_admin"`
	LastLoginAt   sql.NullTime   `json:"last_login_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

func (q *Queries) GetUserManual(ctx context.Context, id uint64) (GetUserManualRow, error) {
	row := q.db.QueryRowContext(ctx, getUserManual, id)
	var i GetUserManualRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.GoogleSubject,
		&i.PictureUrl,
		&i.IsAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceAccessManual = `-- name: GetWorkspaceAccessManual :one
SELECT w.id, w.organization_id, w.owner_user_id, w.name, w.slug, w.is_personal, w.created_by_user_id, w.created_at, w.updated_at, wm.role
FROM workspaces w
JOIN workspace_members wm ON wm.workspace_id = w.id
WHERE w.id = ?
  AND wm.user_id = ?
LIMIT 1
`

type GetWorkspaceAccessManualParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	UserID      uint64 `json:"user_id"`
}

type GetWorkspaceAccessManualRow struct {
	Workspace Workspace            `json:"workspace"`
	Role      WorkspaceMembersRole `json:"role"`
}

func (q *Queries) GetWorkspaceAccessManual(ctx context.Context, arg GetWorkspaceAccessManualParams) (GetWorkspaceAccessManualRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceAccessManual, arg.WorkspaceID, arg.UserID)
	var i GetWorkspaceAccessManualRow
	err := row.Scan(
		&i.Workspace.ID,
		&i.Workspace.OrganizationID,
		&i.Workspace.OwnerUserID,
		&i.Workspace.Name,
		&i.Workspace.Slug,
		&i.Workspace.IsPersonal,
		&i.Workspace.CreatedByUserID,
		&i.Workspace.CreatedAt,
		&i.Workspace.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const listWorkspaceAccessByUserManual = `-- name: ListWorkspaceAccessByUserManual :many
SELECT w.id, w.organization_id, w.owner_user_id, w.name, w.slug, w.is_personal, w.created_by_user_id, w.created_at, w.updated_at, wm.role
FROM workspaces w
JOIN workspace_members wm ON wm.workspace_id = w.id
WHERE wm.user_id = ?
ORDER BY w.is_personal DESC, w.name ASC
`

type ListWorkspaceAccessByUserManualRow struct {
	Workspace Workspace            `json:"workspace"`
	Role      WorkspaceMembersRole `json:"role"`
}

func (q *Queries) ListWorkspaceAccessByUserManual(ctx context.Context, userID uint64) ([]ListWorkspaceAccessByUserManualRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceAccessByUserManual, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceAccessByUserManualRow{}
	for rows.Next() {
		var i ListWorkspaceAccessByUserManualRow
		if err := rows.Scan(
			&i.Workspace.ID,
			&i.Workspace.OrganizationID,
			&i.Workspace.OwnerUserID,
			&i.Workspace.Name,
			&i.Workspace.Slug,
			&i.Workspace.IsPersonal,
			&i.Workspace.CreatedByUserID,
			&i.Workspace.CreatedAt,
			&i.Workspace.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAuthSessionManual = `-- name: TouchAuthSessionManual :exec
UPDATE auth_sessions
SET last_seen_at = NOW()
WHERE token_hash = ?
`

func (q *Queries) TouchAuthSessionManual(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, touchAuthSessionManual, tokenHash)
	return err
}

const updateUserAuthProfileManual = `-- name: UpdateUserAuthProfileManual :exec
UPDATE users
SET
  name = ?,
  email = ?,
  google_subject = ?,
  picture_url = ?,
  is_admin = ?,
  last_login_at = NOW()
WHERE id = ?
`

type UpdateUserAuthProfileManualParams struct {
	Name          string         `json:"name"`
	Email         sql.NullString `json:"email"`
	GoogleSubject sql.NullString `json:"google_subject"`
	PictureUrl    sql.NullString `json:"picture_url"`
	IsAdmin       bool           `json:"is_admin"`
	ID            uint64         `json:"id"`
}

func (q *Queries) UpdateUserAuthProfileManual(ctx context.Context, arg UpdateUserAuthProfileManualParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAuthProfileManual,
		arg.Name,
		arg.Email,
		arg.GoogleSubject,
		arg.PictureUrl,
		arg.IsAdmin,
		arg.ID,
	)
	return err
}
