// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countItemImagesByURLManual = `-- name: CountItemImagesByURLManual :one
SELECT COUNT(*)
FROM item_images
WHERE image_url = ?
`

func (q *Queries) CountItemImagesByURLManual(ctx context.Context, imageUrl string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countItemImagesByURLManual, imageUrl)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItemImageManual = `-- name: CreateItemImageManual :execresult
INSERT INTO item_images (
  workspace_id,
  item_id,
  sequence,
  image_url,
  storage_bytes,
  canvas_uri,
  width,
  height,
  label,
  hocr_url
) SELECT
  i.workspace_id,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
FROM items i
WHERE i.id = ?
`

type CreateItemImageManualParams struct {
	ItemID       string         `json:"item_id"`
	Sequence     uint32         `json:"sequence"`
	ImageUrl     string         `json:"image_url"`
	StorageBytes uint64         `json:"storage_bytes"`
	CanvasUri    sql.NullString `json:"canvas_uri"`
	Width        sql.NullInt32  `json:"width"`
	Height       sql.NullInt32  `json:"height"`
	Label        sql.NullString `json:"label"`
	HocrUrl      sql.NullString `json:"hocr_url"`
}

func (q *Queries) CreateItemImageManual(ctx context.Context, arg CreateItemImageManualParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createItemImageManual,
		arg.ItemID,
		arg.Sequence,
		arg.ImageUrl,
		arg.StorageBytes,
		arg.CanvasUri,
		arg.Width,
		arg.Height,
		arg.Label,
		arg.HocrUrl,
		arg.ItemID,
	)
}

const createItemManual = `-- name: CreateItemManual :exec
INSERT INTO items (
  id,
  user_id,
  workspace_id,
  name,
  source_type,
  source_url,
  source_manifest,
  metadata,
  external_reference_id,
  caller_idempotency_key
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
`

type CreateItemManualParams struct {
	ID                   string          `json:"id"`
	UserID               uint64          `json:"user_id"`
	WorkspaceID          uint64          `json:"workspace_id"`
	Name                 string          `json:"name"`
	SourceType           ItemsSourceType `json:"source_type"`
	SourceUrl            sql.NullString  `json:"source_url"`
	SourceManifest       sql.NullString  `json:"source_manifest"`
	Metadata             json.RawMessage `json:"metadata"`
	ExternalReferenceID  string          `json:"external_reference_id"`
	CallerIdempotencyKey string          `json:"caller_idempotency_key"`
}

func (q *Queries) CreateItemManual(ctx context.Context, arg CreateItemManualParams) error {
	_, err := q.db.ExecContext(ctx, createItemManual,
		arg.ID,
		arg.UserID,
		arg.WorkspaceID,
		arg.Name,
		arg.SourceType,
		arg.SourceUrl,
		arg.SourceManifest,
		arg.Metadata,
		arg.ExternalReferenceID,
		arg.CallerIdempotencyKey,
	)
	return err
}

const getItemImageManual = `-- name: GetItemImageManual :one
SELECT
  id,
  workspace_id,
  item_id,
  sequence,
  image_url,
  storage_bytes,
  canvas_uri,
  width,
  height,
  label,
  hocr_url,
  created_at,
  updated_at
FROM item_images
WHERE id = ?
`

func (q *Queries) GetItemImageManual(ctx context.Context, id uint64) (ItemImage, error) {
	row := q.db.QueryRowContext(ctx, getItemImageManual, id)
	var i ItemImage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ItemID,
		&i.Sequence,
		&i.ImageUrl,
		&i.StorageBytes,
		&i.CanvasUri,
		&i.Width,
		&i.Height,
		&i.Label,
		&i.HocrUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemManual = `-- name: GetItemManual :one
SELECT
  id,
  user_id,
  workspace_id,
  name,
  source_type,
  source_url,
  source_manifest,
  COALESCE(metadata, JSON_OBJECT()) AS metadata,
  external_reference_id,
  caller_idempotency_key,
  created_at,
  updated_at
FROM items
WHERE id = ?
`

type GetItemManualRow struct {
	ID                   string          `json:"id"`
	UserID               uint64          `json:"user_id"`
	WorkspaceID          uint64          `json:"workspace_id"`
	Name                 string          `json:"name"`
	SourceType           ItemsSourceType `json:"source_type"`
	SourceUrl            sql.NullString  `json:"source_url"`
	SourceManifest       sql.NullString  `json:"source_manifest"`
	Metadata             json.RawMessage `json:"metadata"`
	ExternalReferenceID  string          `json:"external_reference_id"`
	CallerIdempotencyKey string          `json:"caller_idempotency_key"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
}

func (q *Queries) GetItemManual(ctx context.Context, id string) (GetItemManualRow, error) {
	row := q.db.QueryRowContext(ctx, getItemManual, id)
	var i GetItemManualRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Name,
		&i.SourceType,
		&i.SourceUrl,
		&i.SourceManifest,
		&i.Metadata,
		&i.ExternalReferenceID,
		&i.CallerIdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItemImagesManual = `-- name: ListItemImagesManual :many
SELECT
  id,
  workspace_id,
  item_id,
  sequence,
  image_url,
  storage_bytes,
  canvas_uri,
  width,
  height,
  label,
  hocr_url,
  created_at,
  updated_at
FROM item_images
WHERE item_id = ?
ORDER BY sequence ASC
`

func (q *Queries) ListItemImagesManual(ctx context.Context, itemID string) ([]ItemImage, error) {
	rows, err := q.db.QueryContext(ctx, listItemImagesManual, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemImage{}
	for rows.Next() {
		var i ItemImage
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ItemID,
			&i.Sequence,
			&i.ImageUrl,
			&i.StorageBytes,
			&i.CanvasUri,
			&i.Width,
			&i.Height,
			&i.Label,
			&i.HocrUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemPreviewsForItemsPageManual = `-- name: ListItemPreviewsForItemsPageManual :many
SELECT
  ranked.id,
  ranked.workspace_id,
  ranked.item_id,
  ranked.sequence,
  ranked.image_url,
  ranked.storage_bytes,
  ranked.canvas_uri,
  ranked.width,
  ranked.height,
  ranked.label,
  ranked.hocr_url,
  ranked.created_at,
  ranked.updated_at,
  ranked.image_count
FROM (
  SELECT
    ii.id,
    ii.workspace_id,
    ii.item_id,
    ii.sequence,
    ii.image_url,
    ii.storage_bytes,
    ii.canvas_uri,
    ii.width,
    ii.height,
    ii.label,
    ii.hocr_url,
    ii.created_at,
    ii.updated_at,
    CAST(COUNT(*) OVER (PARTITION BY ii.item_id) AS UNSIGNED) AS image_count,
    ROW_NUMBER() OVER (PARTITION BY ii.item_id ORDER BY ii.sequence ASC, ii.id ASC) AS image_rank
  FROM item_images ii
  JOIN (
    SELECT i.id
    FROM items i
    WHERE i.workspace_id = ?
      AND (
        i.name LIKE ? ESCAPE '!'
        OR i.id LIKE ? ESCAPE '!'
        OR i.external_reference_id LIKE ? ESCAPE '!'
        OR CAST(i.source_type AS CHAR) LIKE CAST(? AS CHAR) ESCAPE '!'
      )
      AND (
        ? IS NULL
        OR i.created_at < ?
        OR (
          i.created_at = ?
          AND i.id < ?
        )
      )
    ORDER BY i.created_at DESC, i.id DESC
    LIMIT ?
  ) page ON page.id = ii.item_id
) ranked
WHERE ranked.image_rank = 1
ORDER BY ranked.item_id ASC
`

type ListItemPreviewsForItemsPageManualParams struct {
	WorkspaceID     uint64       `json:"workspace_id"`
	FilterPattern   string       `json:"filter_pattern"`
	CursorCreatedAt sql.NullTime `json:"cursor_created_at"`
	CursorID        string       `json:"cursor_id"`
	Limit           int32        `json:"limit"`
}

type ListItemPreviewsForItemsPageManualRow struct {
	ID           uint64         `json:"id"`
	WorkspaceID  uint64         `json:"workspace_id"`
	ItemID       string         `json:"item_id"`
	Sequence     uint32         `json:"sequence"`
	ImageUrl     string         `json:"image_url"`
	StorageBytes uint64         `json:"storage_bytes"`
	CanvasUri    sql.NullString `json:"canvas_uri"`
	Width        sql.NullInt32  `json:"width"`
	Height       sql.NullInt32  `json:"height"`
	Label        sql.NullString `json:"label"`
	HocrUrl      sql.NullString `json:"hocr_url"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	ImageCount   int64          `json:"image_count"`
}

func (q *Queries) ListItemPreviewsForItemsPageManual(ctx context.Context, arg ListItemPreviewsForItemsPageManualParams) ([]ListItemPreviewsForItemsPageManualRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemPreviewsForItemsPageManual,
		arg.WorkspaceID,
		arg.FilterPattern,
		arg.FilterPattern,
		arg.FilterPattern,
		arg.FilterPattern,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemPreviewsForItemsPageManualRow{}
	for rows.Next() {
		var i ListItemPreviewsForItemsPageManualRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ItemID,
			&i.Sequence,
			&i.ImageUrl,
			&i.StorageBytes,
			&i.CanvasUri,
			&i.Width,
			&i.Height,
			&i.Label,
			&i.HocrUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemSummariesPageManual = `-- name: ListItemSummariesPageManual :many
SELECT
  id,
  name,
  source_type,
  external_reference_id,
  created_at,
  updated_at
FROM items
WHERE workspace_id = ?
  AND (
    name LIKE ? ESCAPE '!'
    OR id LIKE ? ESCAPE '!'
    OR external_reference_id LIKE ? ESCAPE '!'
    OR CAST(source_type AS CHAR) LIKE CAST(? AS CHAR) ESCAPE '!'
  )
  AND (
    ? IS NULL
    OR created_at < ?
    OR (
      created_at = ?
      AND id < ?
    )
  )
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListItemSummariesPageManualParams struct {
	WorkspaceID     uint64       `json:"workspace_id"`
	FilterPattern   string       `json:"filter_pattern"`
	CursorCreatedAt sql.NullTime `json:"cursor_created_at"`
	CursorID        string       `json:"cursor_id"`
	Limit           int32        `json:"limit"`
}

type ListItemSummariesPageManualRow struct {
	ID                  string          `json:"id"`
	Name                string          `json:"name"`
	SourceType          ItemsSourceType `json:"source_type"`
	ExternalReferenceID string          `json:"external_reference_id"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
}

func (q *Queries) ListItemSummariesPageManual(ctx context.Context, arg ListItemSummariesPageManualParams) ([]ListItemSummariesPageManualRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemSummariesPageManual,
		arg.WorkspaceID,
		arg.FilterPattern,
		arg.FilterPattern,
		arg.FilterPattern,
		arg.FilterPattern,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemSummariesPageManualRow{}
	for rows.Next() {
		var i ListItemSummariesPageManualRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SourceType,
			&i.ExternalReferenceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockItemImageIDsByURL = `-- name: LockItemImageIDsByURL :many
SELECT id
FROM item_images
WHERE image_url = ?
ORDER BY id
FOR UPDATE
`

func (q *Queries) LockItemImageIDsByURL(ctx context.Context, imageUrl string) ([]uint64, error) {
	rows, err := q.db.QueryContext(ctx, lockItemImageIDsByURL, imageUrl)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uint64{}
	for rows.Next() {
		var id uint64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setItemImageCanvasURIIfMissingManual = `-- name: SetItemImageCanvasURIIfMissingManual :execrows
UPDATE item_images
SET canvas_uri = ?
WHERE id = ?
  AND (canvas_uri IS NULL OR canvas_uri = '')
`

type SetItemImageCanvasURIIfMissingManualParams struct {
	CanvasUri sql.NullString `json:"canvas_uri"`
	ID        uint64         `json:"id"`
}

func (q *Queries) SetItemImageCanvasURIIfMissingManual(ctx context.Context, arg SetItemImageCanvasURIIfMissingManualParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setItemImageCanvasURIIfMissingManual, arg.CanvasUri, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateItemImageCanvasURIManual = `-- name: UpdateItemImageCanvasURIManual :exec
UPDATE item_images
SET canvas_uri = ?
WHERE id = ?
`

type UpdateItemImageCanvasURIManualParams struct {
	CanvasUri sql.NullString `json:"canvas_uri"`
	ID        uint64         `json:"id"`
}

func (q *Queries) UpdateItemImageCanvasURIManual(ctx context.Context, arg UpdateItemImageCanvasURIManualParams) error {
	_, err := q.db.ExecContext(ctx, updateItemImageCanvasURIManual, arg.CanvasUri, arg.ID)
	return err
}

const updateItemMetadataManual = `-- name: UpdateItemMetadataManual :exec
UPDATE items
SET metadata = ?
WHERE id = ?
`

type UpdateItemMetadataManualParams struct {
	Metadata json.RawMessage `json:"metadata"`
	ID       string          `json:"id"`
}

func (q *Queries) UpdateItemMetadataManual(ctx context.Context, arg UpdateItemMetadataManualParams) error {
	_, err := q.db.ExecContext(ctx, updateItemMetadataManual, arg.Metadata, arg.ID)
	return err
}
