// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items_workspace.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const deleteItemForWorkspaceManual = `-- name: DeleteItemForWorkspaceManual :execresult
DELETE FROM items
WHERE id = ?
  AND workspace_id = ?
`

type DeleteItemForWorkspaceManualParams struct {
	ID          string `json:"id"`
	WorkspaceID uint64 `json:"workspace_id"`
}

func (q *Queries) DeleteItemForWorkspaceManual(ctx context.Context, arg DeleteItemForWorkspaceManualParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteItemForWorkspaceManual, arg.ID, arg.WorkspaceID)
}

const getItemForWorkspaceManual = `-- name: GetItemForWorkspaceManual :one
SELECT
  id,
  user_id,
  workspace_id,
  name,
  source_type,
  source_url,
  metadata,
  created_at,
  updated_at
FROM items
WHERE id = ?
  AND workspace_id = ?
LIMIT 1
`

type GetItemForWorkspaceManualParams struct {
	ID          string `json:"id"`
	WorkspaceID uint64 `json:"workspace_id"`
}

type GetItemForWorkspaceManualRow struct {
	ID          string          `json:"id"`
	UserID      uint64          `json:"user_id"`
	WorkspaceID uint64          `json:"workspace_id"`
	Name        string          `json:"name"`
	SourceType  ItemsSourceType `json:"source_type"`
	SourceUrl   sql.NullString  `json:"source_url"`
	Metadata    json.RawMessage `json:"metadata"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) GetItemForWorkspaceManual(ctx context.Context, arg GetItemForWorkspaceManualParams) (GetItemForWorkspaceManualRow, error) {
	row := q.db.QueryRowContext(ctx, getItemForWorkspaceManual, arg.ID, arg.WorkspaceID)
	var i GetItemForWorkspaceManualRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Name,
		&i.SourceType,
		&i.SourceUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemImageByCanvasURIForWorkspaceManual = `-- name: GetItemImageByCanvasURIForWorkspaceManual :one
SELECT
  ii.id,
  ii.item_id,
  ii.sequence,
  ii.image_url,
  ii.canvas_uri,
  ii.label,
  ii.hocr_url,
  ii.created_at,
  ii.updated_at
FROM item_images ii
JOIN items i ON i.id = ii.item_id
WHERE ii.canvas_uri = ?
  AND i.workspace_id = ?
LIMIT 1
`

type GetItemImageByCanvasURIForWorkspaceManualParams struct {
	CanvasUri   sql.NullString `json:"canvas_uri"`
	WorkspaceID uint64         `json:"workspace_id"`
}

type GetItemImageByCanvasURIForWorkspaceManualRow struct {
	ID        uint64         `json:"id"`
	ItemID    string         `json:"item_id"`
	Sequence  uint32         `json:"sequence"`
	ImageUrl  string         `json:"image_url"`
	CanvasUri sql.NullString `json:"canvas_uri"`
	Label     sql.NullString `json:"label"`
	HocrUrl   sql.NullString `json:"hocr_url"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) GetItemImageByCanvasURIForWorkspaceManual(ctx context.Context, arg GetItemImageByCanvasURIForWorkspaceManualParams) (GetItemImageByCanvasURIForWorkspaceManualRow, error) {
	row := q.db.QueryRowContext(ctx, getItemImageByCanvasURIForWorkspaceManual, arg.CanvasUri, arg.WorkspaceID)
	var i GetItemImageByCanvasURIForWorkspaceManualRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Sequence,
		&i.ImageUrl,
		&i.CanvasUri,
		&i.Label,
		&i.HocrUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemImageForWorkspaceManual = `-- name: GetItemImageForWorkspaceManual :one
SELECT
  ii.id,
  ii.item_id,
  ii.sequence,
  ii.image_url,
  ii.canvas_uri,
  ii.label,
  ii.hocr_url,
  ii.created_at,
  ii.updated_at
FROM item_images ii
JOIN items i ON i.id = ii.item_id
WHERE ii.id = ?
  AND i.workspace_id = ?
LIMIT 1
`

type GetItemImageForWorkspaceManualParams struct {
	ID          uint64 `json:"id"`
	WorkspaceID uint64 `json:"workspace_id"`
}

type GetItemImageForWorkspaceManualRow struct {
	ID        uint64         `json:"id"`
	ItemID    string         `json:"item_id"`
	Sequence  uint32         `json:"sequence"`
	ImageUrl  string         `json:"image_url"`
	CanvasUri sql.NullString `json:"canvas_uri"`
	Label     sql.NullString `json:"label"`
	HocrUrl   sql.NullString `json:"hocr_url"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) GetItemImageForWorkspaceManual(ctx context.Context, arg GetItemImageForWorkspaceManualParams) (GetItemImageForWorkspaceManualRow, error) {
	row := q.db.QueryRowContext(ctx, getItemImageForWorkspaceManual, arg.ID, arg.WorkspaceID)
	var i GetItemImageForWorkspaceManualRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Sequence,
		&i.ImageUrl,
		&i.CanvasUri,
		&i.Label,
		&i.HocrUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItemImagesByWorkspaceManual = `-- name: ListItemImagesByWorkspaceManual :many
SELECT
  ii.id,
  ii.item_id,
  ii.sequence,
  ii.image_url,
  ii.canvas_uri,
  ii.label,
  ii.hocr_url,
  ii.created_at,
  ii.updated_at
FROM item_images ii
JOIN items i ON i.id = ii.item_id
WHERE i.workspace_id = ?
ORDER BY ii.item_id ASC, ii.sequence ASC
`

type ListItemImagesByWorkspaceManualRow struct {
	ID        uint64         `json:"id"`
	ItemID    string         `json:"item_id"`
	Sequence  uint32         `json:"sequence"`
	ImageUrl  string         `json:"image_url"`
	CanvasUri sql.NullString `json:"canvas_uri"`
	Label     sql.NullString `json:"label"`
	HocrUrl   sql.NullString `json:"hocr_url"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) ListItemImagesByWorkspaceManual(ctx context.Context, workspaceID uint64) ([]ListItemImagesByWorkspaceManualRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemImagesByWorkspaceManual, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemImagesByWorkspaceManualRow{}
	for rows.Next() {
		var i ListItemImagesByWorkspaceManualRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Sequence,
			&i.ImageUrl,
			&i.CanvasUri,
			&i.Label,
			&i.HocrUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workspaceOwnsItemImageManual = `-- name: WorkspaceOwnsItemImageManual :one
SELECT EXISTS(
  SELECT 1
  FROM item_images ii
  JOIN items i ON i.id = ii.item_id
  WHERE ii.id = ?
    AND i.workspace_id = ?
) AS owns_item_image
`

type WorkspaceOwnsItemImageManualParams struct {
	ItemImageID uint64 `json:"item_image_id"`
	WorkspaceID uint64 `json:"workspace_id"`
}

func (q *Queries) WorkspaceOwnsItemImageManual(ctx context.Context, arg WorkspaceOwnsItemImageManualParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, workspaceOwnsItemImageManual, arg.ItemImageID, arg.WorkspaceID)
	var owns_item_image bool
	err := row.Scan(&owns_item_image)
	return owns_item_image, err
}

const workspaceOwnsItemManual = `-- name: WorkspaceOwnsItemManual :one
SELECT EXISTS(
  SELECT 1
  FROM items
  WHERE id = ?
    AND workspace_id = ?
) AS owns_item
`

type WorkspaceOwnsItemManualParams struct {
	ItemID      string `json:"item_id"`
	WorkspaceID uint64 `json:"workspace_id"`
}

func (q *Queries) WorkspaceOwnsItemManual(ctx context.Context, arg WorkspaceOwnsItemManualParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, workspaceOwnsItemManual, arg.ItemID, arg.WorkspaceID)
	var owns_item bool
	err := row.Scan(&owns_item)
	return owns_item, err
}
