// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_cleanup_outbox.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const completeFencedUploadResourceCleanup = `-- name: CompleteFencedUploadResourceCleanup :execresult
DELETE FROM resource_cleanup_outbox
WHERE id = ?
  AND generation = ?
  AND kind = 'upload_blob'
  AND delete_fenced_at IS NOT NULL
  AND status = 'processing'
  AND locked_by = ?
`

type CompleteFencedUploadResourceCleanupParams struct {
	ID         uint64         `json:"id"`
	Generation uint64         `json:"generation"`
	LockedBy   sql.NullString `json:"locked_by"`
}

func (q *Queries) CompleteFencedUploadResourceCleanup(ctx context.Context, arg CompleteFencedUploadResourceCleanupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, completeFencedUploadResourceCleanup, arg.ID, arg.Generation, arg.LockedBy)
}

const completeResourceCleanup = `-- name: CompleteResourceCleanup :execresult
DELETE FROM resource_cleanup_outbox
WHERE id = ?
  AND generation = ?
  AND status = 'processing'
  AND locked_by = ?
  AND (kind <> 'upload_blob' OR delete_fenced_at IS NULL)
`

type CompleteResourceCleanupParams struct {
	ID         uint64         `json:"id"`
	Generation uint64         `json:"generation"`
	LockedBy   sql.NullString `json:"locked_by"`
}

func (q *Queries) CompleteResourceCleanup(ctx context.Context, arg CompleteResourceCleanupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, completeResourceCleanup, arg.ID, arg.Generation, arg.LockedBy)
}

const deleteResourceCleanupByKindKey = `-- name: DeleteResourceCleanupByKindKey :execresult
DELETE FROM resource_cleanup_outbox
WHERE kind = ?
  AND resource_key = ?
`

type DeleteResourceCleanupByKindKeyParams struct {
	Kind        ResourceCleanupOutboxKind `json:"kind"`
	ResourceKey string                    `json:"resource_key"`
}

func (q *Queries) DeleteResourceCleanupByKindKey(ctx context.Context, arg DeleteResourceCleanupByKindKeyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteResourceCleanupByKindKey, arg.Kind, arg.ResourceKey)
}

const failExhaustedResourceCleanups = `-- name: FailExhaustedResourceCleanups :exec
UPDATE resource_cleanup_outbox
SET status = IF(kind = 'upload_blob', 'pending', 'failed'),
    next_attempt_at = IF(kind = 'upload_blob', DATE_ADD(NOW(), INTERVAL 1 HOUR), next_attempt_at),
    lease_until = NULL,
    locked_by = NULL,
    last_error = COALESCE(
      last_error,
      IF(
        kind = 'upload_blob',
        'cleanup lease expired; another retry is scheduled',
        'cleanup lease expired after maximum attempts'
      )
    ),
    updated_at = NOW()
WHERE status = 'processing'
  AND lease_until < NOW()
  AND attempt_count >= max_attempts
`

func (q *Queries) FailExhaustedResourceCleanups(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, failExhaustedResourceCleanups)
	return err
}

const fenceUploadResourceCleanup = `-- name: FenceUploadResourceCleanup :execresult
UPDATE resource_cleanup_outbox
SET delete_fenced_at = COALESCE(delete_fenced_at, NOW()),
    updated_at = NOW()
WHERE id = ?
  AND generation = ?
  AND kind = 'upload_blob'
  AND status = 'processing'
  AND locked_by = ?
`

type FenceUploadResourceCleanupParams struct {
	ID         uint64         `json:"id"`
	Generation uint64         `json:"generation"`
	LockedBy   sql.NullString `json:"locked_by"`
}

func (q *Queries) FenceUploadResourceCleanup(ctx context.Context, arg FenceUploadResourceCleanupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, fenceUploadResourceCleanup, arg.ID, arg.Generation, arg.LockedBy)
}

const lockResourceCleanupByKindKey = `-- name: LockResourceCleanupByKindKey :one
SELECT
  id,
  kind,
  resource_key,
  workspace_id,
  storage_bytes,
  generation,
  delete_fenced_at,
  status,
  attempt_count,
  max_attempts,
  next_attempt_at,
  lease_until,
  locked_by,
  last_error,
  created_at,
  updated_at
FROM resource_cleanup_outbox
WHERE kind = ?
  AND resource_key = ?
FOR UPDATE
`

type LockResourceCleanupByKindKeyParams struct {
	Kind        ResourceCleanupOutboxKind `json:"kind"`
	ResourceKey string                    `json:"resource_key"`
}

func (q *Queries) LockResourceCleanupByKindKey(ctx context.Context, arg LockResourceCleanupByKindKeyParams) (ResourceCleanupOutbox, error) {
	row := q.db.QueryRowContext(ctx, lockResourceCleanupByKindKey, arg.Kind, arg.ResourceKey)
	var i ResourceCleanupOutbox
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ResourceKey,
		&i.WorkspaceID,
		&i.StorageBytes,
		&i.Generation,
		&i.DeleteFencedAt,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LeaseUntil,
		&i.LockedBy,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markResourceCleanupProcessing = `-- name: MarkResourceCleanupProcessing :execresult
UPDATE resource_cleanup_outbox
SET status = 'processing',
    attempt_count = attempt_count + 1,
    lease_until = ?,
    locked_by = ?,
    updated_at = NOW()
WHERE id = ?
  AND generation = ?
  AND (
    (status = 'pending' AND next_attempt_at <= NOW())
    OR (status = 'processing' AND lease_until < NOW() AND attempt_count < max_attempts)
  )
`

type MarkResourceCleanupProcessingParams struct {
	LeaseUntil sql.NullTime   `json:"lease_until"`
	LockedBy   sql.NullString `json:"locked_by"`
	ID         uint64         `json:"id"`
	Generation uint64         `json:"generation"`
}

func (q *Queries) MarkResourceCleanupProcessing(ctx context.Context, arg MarkResourceCleanupProcessingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markResourceCleanupProcessing,
		arg.LeaseUntil,
		arg.LockedBy,
		arg.ID,
		arg.Generation,
	)
}

const resizeStagedUploadCleanup = `-- name: ResizeStagedUploadCleanup :execresult
UPDATE resource_cleanup_outbox
SET workspace_id = ?,
    storage_bytes = GREATEST(storage_bytes, ?),
    next_attempt_at = GREATEST(next_attempt_at, ?),
    updated_at = NOW()
WHERE kind = 'upload_blob'
  AND resource_key = ?
`

type ResizeStagedUploadCleanupParams struct {
	WorkspaceID   uint64      `json:"workspace_id"`
	StorageBytes  interface{} `json:"storage_bytes"`
	NextAttemptAt interface{} `json:"next_attempt_at"`
	ResourceKey   string      `json:"resource_key"`
}

func (q *Queries) ResizeStagedUploadCleanup(ctx context.Context, arg ResizeStagedUploadCleanupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, resizeStagedUploadCleanup,
		arg.WorkspaceID,
		arg.StorageBytes,
		arg.NextAttemptAt,
		arg.ResourceKey,
	)
}

const retryResourceCleanup = `-- name: RetryResourceCleanup :execresult
UPDATE resource_cleanup_outbox
SET status = IF(kind = 'upload_blob', 'pending', IF(attempt_count >= max_attempts, 'failed', 'pending')),
    next_attempt_at = ?,
    lease_until = NULL,
    locked_by = NULL,
    last_error = ?,
    updated_at = NOW()
WHERE id = ?
  AND generation = ?
  AND status = 'processing'
  AND locked_by = ?
`

type RetryResourceCleanupParams struct {
	NextAttemptAt time.Time      `json:"next_attempt_at"`
	LastError     sql.NullString `json:"last_error"`
	ID            uint64         `json:"id"`
	Generation    uint64         `json:"generation"`
	LockedBy      sql.NullString `json:"locked_by"`
}

func (q *Queries) RetryResourceCleanup(ctx context.Context, arg RetryResourceCleanupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, retryResourceCleanup,
		arg.NextAttemptAt,
		arg.LastError,
		arg.ID,
		arg.Generation,
		arg.LockedBy,
	)
}

const selectResourceCleanupForUpdate = `-- name: SelectResourceCleanupForUpdate :one
SELECT
  id,
  kind,
  resource_key,
  workspace_id,
  storage_bytes,
  generation,
  delete_fenced_at,
  status,
  attempt_count,
  max_attempts,
  next_attempt_at,
  lease_until,
  locked_by,
  last_error,
  created_at,
  updated_at
FROM resource_cleanup_outbox
WHERE (
    status = 'pending'
    AND next_attempt_at <= NOW()
  ) OR (
    status = 'processing'
    AND lease_until < NOW()
    AND attempt_count < max_attempts
  )
ORDER BY next_attempt_at ASC, updated_at ASC
LIMIT 1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) SelectResourceCleanupForUpdate(ctx context.Context) (ResourceCleanupOutbox, error) {
	row := q.db.QueryRowContext(ctx, selectResourceCleanupForUpdate)
	var i ResourceCleanupOutbox
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ResourceKey,
		&i.WorkspaceID,
		&i.StorageBytes,
		&i.Generation,
		&i.DeleteFencedAt,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LeaseUntil,
		&i.LockedBy,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertResourceCleanup = `-- name: UpsertResourceCleanup :exec
INSERT INTO resource_cleanup_outbox (
  kind,
  resource_key,
  workspace_id,
  storage_bytes,
  next_attempt_at,
  status,
  attempt_count,
  lease_until,
  locked_by,
  last_error
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  'pending',
  0,
  NULL,
  NULL,
  NULL
)
ON DUPLICATE KEY UPDATE
  workspace_id = IF(VALUES(workspace_id) > 0, VALUES(workspace_id), workspace_id),
  storage_bytes = GREATEST(storage_bytes, VALUES(storage_bytes)),
  generation = generation + 1,
  status = 'pending',
  attempt_count = 0,
  -- A superseded remote operation can still be in flight after its generation
  -- is fenced in this row. Do not let the replacement run until that bounded
  -- operation's lease horizon has passed.
  next_attempt_at = GREATEST(VALUES(next_attempt_at), COALESCE(lease_until, NOW())),
  lease_until = NULL,
  locked_by = NULL,
  last_error = NULL,
  updated_at = NOW()
`

type UpsertResourceCleanupParams struct {
	Kind          ResourceCleanupOutboxKind `json:"kind"`
	ResourceKey   string                    `json:"resource_key"`
	WorkspaceID   uint64                    `json:"workspace_id"`
	StorageBytes  uint64                    `json:"storage_bytes"`
	NextAttemptAt time.Time                 `json:"next_attempt_at"`
}

func (q *Queries) UpsertResourceCleanup(ctx context.Context, arg UpsertResourceCleanupParams) error {
	_, err := q.db.ExecContext(ctx, upsertResourceCleanup,
		arg.Kind,
		arg.ResourceKey,
		arg.WorkspaceID,
		arg.StorageBytes,
		arg.NextAttemptAt,
	)
	return err
}
