// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_graph.sql

package db

import (
	"context"
	"database/sql"
)

const deleteAnnotationIndexForItemResourceGraph = `-- name: DeleteAnnotationIndexForItemResourceGraph :exec
DELETE annotation
FROM annotations annotation
JOIN item_images target ON target.id = annotation.item_image_id
WHERE target.workspace_id = ?
  AND target.item_id = ?
  AND (? = 0 OR target.id = ?)
  AND annotation.workspace_id = ?
`

type DeleteAnnotationIndexForItemResourceGraphParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	ItemID      string `json:"item_id"`
	ItemImageID uint64 `json:"item_image_id"`
}

func (q *Queries) DeleteAnnotationIndexForItemResourceGraph(ctx context.Context, arg DeleteAnnotationIndexForItemResourceGraphParams) error {
	_, err := q.db.ExecContext(ctx, deleteAnnotationIndexForItemResourceGraph,
		arg.WorkspaceID,
		arg.ItemID,
		arg.ItemImageID,
		arg.ItemImageID,
		arg.WorkspaceID,
	)
	return err
}

const deleteAnnotationMirrorTombstonesForItemResourceGraph = `-- name: DeleteAnnotationMirrorTombstonesForItemResourceGraph :exec
DELETE tombstone
FROM annotation_mirror_tombstones tombstone
JOIN item_images target ON target.id = tombstone.item_image_id
WHERE target.workspace_id = ?
  AND target.item_id = ?
  AND (? = 0 OR target.id = ?)
`

type DeleteAnnotationMirrorTombstonesForItemResourceGraphParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	ItemID      string `json:"item_id"`
	ItemImageID uint64 `json:"item_image_id"`
}

func (q *Queries) DeleteAnnotationMirrorTombstonesForItemResourceGraph(ctx context.Context, arg DeleteAnnotationMirrorTombstonesForItemResourceGraphParams) error {
	_, err := q.db.ExecContext(ctx, deleteAnnotationMirrorTombstonesForItemResourceGraph,
		arg.WorkspaceID,
		arg.ItemID,
		arg.ItemImageID,
		arg.ItemImageID,
	)
	return err
}

const deleteAnnotationMirrorsForItemResourceGraph = `-- name: DeleteAnnotationMirrorsForItemResourceGraph :exec
DELETE mirror
FROM annotation_mirror_outbox mirror
JOIN item_images target ON target.id = mirror.item_image_id
WHERE target.workspace_id = ?
  AND target.item_id = ?
  AND (? = 0 OR target.id = ?)
`

type DeleteAnnotationMirrorsForItemResourceGraphParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	ItemID      string `json:"item_id"`
	ItemImageID uint64 `json:"item_image_id"`
}

func (q *Queries) DeleteAnnotationMirrorsForItemResourceGraph(ctx context.Context, arg DeleteAnnotationMirrorsForItemResourceGraphParams) error {
	_, err := q.db.ExecContext(ctx, deleteAnnotationMirrorsForItemResourceGraph,
		arg.WorkspaceID,
		arg.ItemID,
		arg.ItemImageID,
		arg.ItemImageID,
	)
	return err
}

const deleteAnnotationPagesForItemResourceGraph = `-- name: DeleteAnnotationPagesForItemResourceGraph :exec
DELETE page
FROM annotation_pages page
JOIN item_images target ON target.id = page.item_image_id
WHERE target.workspace_id = ?
  AND target.item_id = ?
  AND (? = 0 OR target.id = ?)
  AND page.workspace_id = ?
`

type DeleteAnnotationPagesForItemResourceGraphParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	ItemID      string `json:"item_id"`
	ItemImageID uint64 `json:"item_image_id"`
}

func (q *Queries) DeleteAnnotationPagesForItemResourceGraph(ctx context.Context, arg DeleteAnnotationPagesForItemResourceGraphParams) error {
	_, err := q.db.ExecContext(ctx, deleteAnnotationPagesForItemResourceGraph,
		arg.WorkspaceID,
		arg.ItemID,
		arg.ItemImageID,
		arg.ItemImageID,
		arg.WorkspaceID,
	)
	return err
}

const deleteCurrentOCRRunsForItemResourceGraph = `-- name: DeleteCurrentOCRRunsForItemResourceGraph :exec
DELETE current_run
FROM current_ocr_runs current_run
JOIN item_images target ON target.id = current_run.item_image_id
WHERE target.workspace_id = ?
  AND target.item_id = ?
  AND (? = 0 OR target.id = ?)
`

type DeleteCurrentOCRRunsForItemResourceGraphParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	ItemID      string `json:"item_id"`
	ItemImageID uint64 `json:"item_image_id"`
}

func (q *Queries) DeleteCurrentOCRRunsForItemResourceGraph(ctx context.Context, arg DeleteCurrentOCRRunsForItemResourceGraphParams) error {
	_, err := q.db.ExecContext(ctx, deleteCurrentOCRRunsForItemResourceGraph,
		arg.WorkspaceID,
		arg.ItemID,
		arg.ItemImageID,
		arg.ItemImageID,
	)
	return err
}

const deleteExternalRequestsForItemResourceGraph = `-- name: DeleteExternalRequestsForItemResourceGraph :exec

DELETE er
FROM external_requests er
WHERE er.workspace_id = ?
  AND (
    (
      ? = 0
      AND er.item_id = ?
    )
    OR EXISTS (
      SELECT 1
      FROM item_images target
      WHERE target.workspace_id = ?
        AND target.item_id = ?
        AND (? = 0 OR target.id = ?)
        AND target.id = er.item_image_id
    )
    OR EXISTS (
      SELECT 1
      FROM transcription_jobs tj
      JOIN item_images target ON target.id = tj.item_image_id
      WHERE target.workspace_id = ?
        AND target.item_id = ?
        AND (? = 0 OR target.id = ?)
        AND tj.workspace_id = ?
        AND tj.id = er.transcription_job_id
    )
    OR EXISTS (
      SELECT 1
      FROM ocr_runs run
      JOIN item_images target ON target.id = run.item_image_id
      WHERE target.workspace_id = ?
        AND target.item_id = ?
        AND (? = 0 OR target.id = ?)
        AND run.workspace_id = ?
        AND run.session_id = er.session_id
    )
  )
`

type DeleteExternalRequestsForItemResourceGraphParams struct {
	WorkspaceID    uint64         `json:"workspace_id"`
	ItemImageID    uint64         `json:"item_image_id"`
	NullableItemID sql.NullString `json:"nullable_item_id"`
	ItemID         string         `json:"item_id"`
}

// The application owns relational lifecycle semantics. Every query below is
// scoped by the authoritative workspace/item pair and optionally one image.
// Passing item_image_id = 0 selects the complete item graph.
func (q *Queries) DeleteExternalRequestsForItemResourceGraph(ctx context.Context, arg DeleteExternalRequestsForItemResourceGraphParams) error {
	_, err := q.db.ExecContext(ctx, deleteExternalRequestsForItemResourceGraph,
		arg.WorkspaceID,
		arg.ItemImageID,
		arg.NullableItemID,
		arg.WorkspaceID,
		arg.ItemID,
		arg.ItemImageID,
		arg.ItemImageID,
		arg.WorkspaceID,
		arg.ItemID,
		arg.ItemImageID,
		arg.ItemImageID,
		arg.WorkspaceID,
		arg.WorkspaceID,
		arg.ItemID,
		arg.ItemImageID,
		arg.ItemImageID,
		arg.WorkspaceID,
	)
	return err
}

const deleteItemImagesForItemResourceGraph = `-- name: DeleteItemImagesForItemResourceGraph :exec
DELETE FROM item_images
WHERE workspace_id = ?
  AND item_id = ?
`

type DeleteItemImagesForItemResourceGraphParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	ItemID      string `json:"item_id"`
}

func (q *Queries) DeleteItemImagesForItemResourceGraph(ctx context.Context, arg DeleteItemImagesForItemResourceGraphParams) error {
	_, err := q.db.ExecContext(ctx, deleteItemImagesForItemResourceGraph, arg.WorkspaceID, arg.ItemID)
	return err
}

const deleteOCRRunsForItemResourceGraph = `-- name: DeleteOCRRunsForItemResourceGraph :exec
DELETE run
FROM ocr_runs run
JOIN item_images target ON target.id = run.item_image_id
WHERE target.workspace_id = ?
  AND target.item_id = ?
  AND (? = 0 OR target.id = ?)
  AND run.workspace_id = ?
`

type DeleteOCRRunsForItemResourceGraphParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	ItemID      string `json:"item_id"`
	ItemImageID uint64 `json:"item_image_id"`
}

func (q *Queries) DeleteOCRRunsForItemResourceGraph(ctx context.Context, arg DeleteOCRRunsForItemResourceGraphParams) error {
	_, err := q.db.ExecContext(ctx, deleteOCRRunsForItemResourceGraph,
		arg.WorkspaceID,
		arg.ItemID,
		arg.ItemImageID,
		arg.ItemImageID,
		arg.WorkspaceID,
	)
	return err
}

const deleteProviderAuditsForItemResourceGraph = `-- name: DeleteProviderAuditsForItemResourceGraph :exec
DELETE audit
FROM provider_call_audits audit
JOIN item_images target ON target.id = audit.item_image_id
WHERE target.workspace_id = ?
  AND target.item_id = ?
  AND (? = 0 OR target.id = ?)
  AND audit.workspace_id = ?
`

type DeleteProviderAuditsForItemResourceGraphParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	ItemID      string `json:"item_id"`
	ItemImageID uint64 `json:"item_image_id"`
}

func (q *Queries) DeleteProviderAuditsForItemResourceGraph(ctx context.Context, arg DeleteProviderAuditsForItemResourceGraphParams) error {
	_, err := q.db.ExecContext(ctx, deleteProviderAuditsForItemResourceGraph,
		arg.WorkspaceID,
		arg.ItemID,
		arg.ItemImageID,
		arg.ItemImageID,
		arg.WorkspaceID,
	)
	return err
}

const deletePublishedPagesForItemResourceGraph = `-- name: DeletePublishedPagesForItemResourceGraph :exec
DELETE published
FROM published_annotation_pages published
JOIN item_images target ON target.id = published.item_image_id
WHERE target.workspace_id = ?
  AND target.item_id = ?
  AND (? = 0 OR target.id = ?)
  AND published.workspace_id = ?
`

type DeletePublishedPagesForItemResourceGraphParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	ItemID      string `json:"item_id"`
	ItemImageID uint64 `json:"item_image_id"`
}

func (q *Queries) DeletePublishedPagesForItemResourceGraph(ctx context.Context, arg DeletePublishedPagesForItemResourceGraphParams) error {
	_, err := q.db.ExecContext(ctx, deletePublishedPagesForItemResourceGraph,
		arg.WorkspaceID,
		arg.ItemID,
		arg.ItemImageID,
		arg.ItemImageID,
		arg.WorkspaceID,
	)
	return err
}

const deleteTranscriptionAttemptsForItemResourceGraph = `-- name: DeleteTranscriptionAttemptsForItemResourceGraph :exec
DELETE attempt
FROM transcription_job_attempts attempt
JOIN transcription_jobs job ON job.id = attempt.job_id
JOIN item_images target ON target.id = job.item_image_id
WHERE target.workspace_id = ?
  AND target.item_id = ?
  AND (? = 0 OR target.id = ?)
  AND job.workspace_id = ?
`

type DeleteTranscriptionAttemptsForItemResourceGraphParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	ItemID      string `json:"item_id"`
	ItemImageID uint64 `json:"item_image_id"`
}

func (q *Queries) DeleteTranscriptionAttemptsForItemResourceGraph(ctx context.Context, arg DeleteTranscriptionAttemptsForItemResourceGraphParams) error {
	_, err := q.db.ExecContext(ctx, deleteTranscriptionAttemptsForItemResourceGraph,
		arg.WorkspaceID,
		arg.ItemID,
		arg.ItemImageID,
		arg.ItemImageID,
		arg.WorkspaceID,
	)
	return err
}

const deleteTranscriptionJobsForItemResourceGraph = `-- name: DeleteTranscriptionJobsForItemResourceGraph :exec
DELETE job
FROM transcription_jobs job
JOIN item_images target ON target.id = job.item_image_id
WHERE target.workspace_id = ?
  AND target.item_id = ?
  AND (? = 0 OR target.id = ?)
  AND job.workspace_id = ?
`

type DeleteTranscriptionJobsForItemResourceGraphParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	ItemID      string `json:"item_id"`
	ItemImageID uint64 `json:"item_image_id"`
}

func (q *Queries) DeleteTranscriptionJobsForItemResourceGraph(ctx context.Context, arg DeleteTranscriptionJobsForItemResourceGraphParams) error {
	_, err := q.db.ExecContext(ctx, deleteTranscriptionJobsForItemResourceGraph,
		arg.WorkspaceID,
		arg.ItemID,
		arg.ItemImageID,
		arg.ItemImageID,
		arg.WorkspaceID,
	)
	return err
}

const deleteUploadBatchFilesForItemResourceGraph = `-- name: DeleteUploadBatchFilesForItemResourceGraph :exec
DELETE ubf
FROM upload_batch_files ubf
WHERE ubf.workspace_id = ?
  AND EXISTS (
    SELECT 1
    FROM upload_batches ub
    WHERE ub.workspace_id = ?
      AND ub.id = ubf.batch_id
      AND ub.item_id = ?
  )
`

type DeleteUploadBatchFilesForItemResourceGraphParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	ItemID      string `json:"item_id"`
}

func (q *Queries) DeleteUploadBatchFilesForItemResourceGraph(ctx context.Context, arg DeleteUploadBatchFilesForItemResourceGraphParams) error {
	_, err := q.db.ExecContext(ctx, deleteUploadBatchFilesForItemResourceGraph, arg.WorkspaceID, arg.WorkspaceID, arg.ItemID)
	return err
}

const deleteUploadBatchesForItemResourceGraph = `-- name: DeleteUploadBatchesForItemResourceGraph :exec
DELETE FROM upload_batches
WHERE workspace_id = ?
  AND item_id = ?
`

type DeleteUploadBatchesForItemResourceGraphParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	ItemID      string `json:"item_id"`
}

func (q *Queries) DeleteUploadBatchesForItemResourceGraph(ctx context.Context, arg DeleteUploadBatchesForItemResourceGraphParams) error {
	_, err := q.db.ExecContext(ctx, deleteUploadBatchesForItemResourceGraph, arg.WorkspaceID, arg.ItemID)
	return err
}

const detachUploadBatchFilesForItemImageResourceGraph = `-- name: DetachUploadBatchFilesForItemImageResourceGraph :exec
UPDATE upload_batch_files ubf
LEFT JOIN transcription_jobs tj
  ON tj.workspace_id = ubf.workspace_id
 AND tj.id = ubf.transcription_job_id
SET ubf.item_image_id = NULL,
    ubf.transcription_job_id = NULL,
    ubf.updated_at = GREATEST(DATE_ADD(ubf.updated_at, INTERVAL 1 SECOND), NOW())
WHERE ubf.workspace_id = ?
  AND EXISTS (
    SELECT 1
    FROM item_images target
    WHERE target.workspace_id = ?
      AND target.item_id = ?
      AND target.id = ?
      AND (target.id = ubf.item_image_id OR target.id = tj.item_image_id)
  )
`

type DetachUploadBatchFilesForItemImageResourceGraphParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	ItemID      string `json:"item_id"`
	ItemImageID uint64 `json:"item_image_id"`
}

func (q *Queries) DetachUploadBatchFilesForItemImageResourceGraph(ctx context.Context, arg DetachUploadBatchFilesForItemImageResourceGraphParams) error {
	_, err := q.db.ExecContext(ctx, detachUploadBatchFilesForItemImageResourceGraph,
		arg.WorkspaceID,
		arg.WorkspaceID,
		arg.ItemID,
		arg.ItemImageID,
	)
	return err
}
