// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage_quota.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addStorageQuotaReserved = `-- name: AddStorageQuotaReserved :exec
UPDATE storage_quota_usage
SET
  reserved_upload_blob_bytes = reserved_upload_blob_bytes + ?,
  reserved_database_bytes = reserved_database_bytes + ?,
  reserved_item_count = reserved_item_count + ?,
  reserved_image_count = reserved_image_count + ?
WHERE workspace_id IN (0, ?)
`

type AddStorageQuotaReservedParams struct {
	UploadBlobBytes uint64 `json:"upload_blob_bytes"`
	DatabaseBytes   uint64 `json:"database_bytes"`
	ItemCount       uint64 `json:"item_count"`
	ImageCount      uint64 `json:"image_count"`
	WorkspaceID     uint64 `json:"workspace_id"`
}

func (q *Queries) AddStorageQuotaReserved(ctx context.Context, arg AddStorageQuotaReservedParams) error {
	_, err := q.db.ExecContext(ctx, addStorageQuotaReserved,
		arg.UploadBlobBytes,
		arg.DatabaseBytes,
		arg.ItemCount,
		arg.ImageCount,
		arg.WorkspaceID,
	)
	return err
}

const addStorageQuotaUsed = `-- name: AddStorageQuotaUsed :exec
UPDATE storage_quota_usage
SET
  upload_blob_bytes = upload_blob_bytes + ?,
  database_bytes = database_bytes + ?,
  item_count = item_count + ?,
  image_count = image_count + ?
WHERE workspace_id IN (0, ?)
`

type AddStorageQuotaUsedParams struct {
	UploadBlobBytes uint64 `json:"upload_blob_bytes"`
	DatabaseBytes   uint64 `json:"database_bytes"`
	ItemCount       uint64 `json:"item_count"`
	ImageCount      uint64 `json:"image_count"`
	WorkspaceID     uint64 `json:"workspace_id"`
}

func (q *Queries) AddStorageQuotaUsed(ctx context.Context, arg AddStorageQuotaUsedParams) error {
	_, err := q.db.ExecContext(ctx, addStorageQuotaUsed,
		arg.UploadBlobBytes,
		arg.DatabaseBytes,
		arg.ItemCount,
		arg.ImageCount,
		arg.WorkspaceID,
	)
	return err
}

const bindStorageQuotaReservationResource = `-- name: BindStorageQuotaReservationResource :execresult
UPDATE workspace_storage_reservations
SET reserved_bytes = 0,
    resource_key = ?
WHERE id = ?
  AND workspace_id = ?
`

type BindStorageQuotaReservationResourceParams struct {
	ResourceKey sql.NullString `json:"resource_key"`
	ID          string         `json:"id"`
	WorkspaceID uint64         `json:"workspace_id"`
}

func (q *Queries) BindStorageQuotaReservationResource(ctx context.Context, arg BindStorageQuotaReservationResourceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, bindStorageQuotaReservationResource, arg.ResourceKey, arg.ID, arg.WorkspaceID)
}

const deleteOrphanStorageQuotaUsage = `-- name: DeleteOrphanStorageQuotaUsage :exec
DELETE FROM storage_quota_usage
WHERE workspace_id <> 0
  AND upload_blob_bytes = 0
  AND database_bytes = 0
  AND item_count = 0
  AND image_count = 0
  AND reserved_upload_blob_bytes = 0
  AND reserved_database_bytes = 0
  AND reserved_item_count = 0
  AND reserved_image_count = 0
  AND workspace_id NOT IN (SELECT id FROM workspaces)
  AND workspace_id NOT IN (SELECT workspace_id FROM workspace_storage_reservations)
  AND workspace_id NOT IN (SELECT workspace_id FROM resource_cleanup_outbox WHERE workspace_id > 0)
`

func (q *Queries) DeleteOrphanStorageQuotaUsage(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOrphanStorageQuotaUsage)
	return err
}

const deleteStorageQuotaReservation = `-- name: DeleteStorageQuotaReservation :execresult
DELETE FROM workspace_storage_reservations
WHERE id = ?
  AND workspace_id = ?
`

type DeleteStorageQuotaReservationParams struct {
	ID          string `json:"id"`
	WorkspaceID uint64 `json:"workspace_id"`
}

func (q *Queries) DeleteStorageQuotaReservation(ctx context.Context, arg DeleteStorageQuotaReservationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteStorageQuotaReservation, arg.ID, arg.WorkspaceID)
}

const ensureStorageQuotaUsage = `-- name: EnsureStorageQuotaUsage :exec
INSERT INTO storage_quota_usage (workspace_id)
VALUES (?)
ON DUPLICATE KEY UPDATE workspace_id = VALUES(workspace_id)
`

func (q *Queries) EnsureStorageQuotaUsage(ctx context.Context, workspaceID uint64) error {
	_, err := q.db.ExecContext(ctx, ensureStorageQuotaUsage, workspaceID)
	return err
}

const getItemDurableDatabaseBytes = `-- name: GetItemDurableDatabaseBytes :one
SELECT CAST(COALESCE(SUM(payloads.byte_count), 0) AS UNSIGNED) AS database_bytes
FROM (
  SELECT OCTET_LENGTH(i.source_manifest) AS byte_count
  FROM items i
  WHERE i.workspace_id = ?
    AND i.id = ?
  UNION ALL
  SELECT OCTET_LENGTH(orun.original_hocr) + OCTET_LENGTH(orun.original_text) AS byte_count
  FROM ocr_runs orun
  JOIN item_images ii ON ii.id = orun.item_image_id
  JOIN items i ON i.id = ii.item_id
  WHERE i.workspace_id = ?
    AND i.id = ?
  UNION ALL
  SELECT OCTET_LENGTH(ap.payload)
  FROM annotation_pages ap
  JOIN item_images ii ON ii.id = ap.item_image_id
  WHERE ap.workspace_id = ?
    AND ii.item_id = ?
  UNION ALL
  SELECT OCTET_LENGTH(a.payload)
  FROM annotations a
  JOIN item_images ii ON ii.id = a.item_image_id
  WHERE a.workspace_id = ?
    AND ii.item_id = ?
  UNION ALL
  SELECT OCTET_LENGTH(pap.payload)
  FROM published_annotation_pages pap
  JOIN item_images ii ON ii.id = pap.item_image_id
  WHERE pap.workspace_id = ?
    AND ii.item_id = ?
  UNION ALL
  SELECT pca.database_bytes
  FROM provider_call_audits pca
  JOIN item_images ii ON ii.id = pca.item_image_id
  WHERE pca.workspace_id = ?
    AND ii.item_id = ?
) payloads
`

type GetItemDurableDatabaseBytesParams struct {
	WorkspaceID uint64 `json:"workspace_id"`
	ItemID      string `json:"item_id"`
}

func (q *Queries) GetItemDurableDatabaseBytes(ctx context.Context, arg GetItemDurableDatabaseBytesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getItemDurableDatabaseBytes,
		arg.WorkspaceID,
		arg.ItemID,
		arg.WorkspaceID,
		arg.ItemID,
		arg.WorkspaceID,
		arg.ItemID,
		arg.WorkspaceID,
		arg.ItemID,
		arg.WorkspaceID,
		arg.ItemID,
		arg.WorkspaceID,
		arg.ItemID,
	)
	var database_bytes int64
	err := row.Scan(&database_bytes)
	return database_bytes, err
}

const getItemImageDurableDatabaseBytes = `-- name: GetItemImageDurableDatabaseBytes :one
SELECT CAST(COALESCE(SUM(payloads.byte_count), 0) AS UNSIGNED) AS database_bytes
FROM (
  SELECT OCTET_LENGTH(orun.original_hocr) + OCTET_LENGTH(orun.original_text) AS byte_count
  FROM ocr_runs orun
  WHERE orun.item_image_id = ?
  UNION ALL
  SELECT OCTET_LENGTH(ap.payload)
  FROM annotation_pages ap
  WHERE ap.workspace_id = ?
    AND ap.item_image_id = ?
  UNION ALL
  SELECT OCTET_LENGTH(a.payload)
  FROM annotations a
  WHERE a.workspace_id = ?
    AND a.item_image_id = ?
  UNION ALL
  SELECT OCTET_LENGTH(pap.payload)
  FROM published_annotation_pages pap
  WHERE pap.workspace_id = ?
    AND pap.item_image_id = ?
  UNION ALL
  SELECT pca.database_bytes
  FROM provider_call_audits pca
  JOIN item_images audit_ii ON audit_ii.id = pca.item_image_id
  WHERE pca.workspace_id = ?
    AND audit_ii.id = ?
) payloads
`

type GetItemImageDurableDatabaseBytesParams struct {
	ItemImageID uint64 `json:"item_image_id"`
	WorkspaceID uint64 `json:"workspace_id"`
}

func (q *Queries) GetItemImageDurableDatabaseBytes(ctx context.Context, arg GetItemImageDurableDatabaseBytesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getItemImageDurableDatabaseBytes,
		arg.ItemImageID,
		arg.WorkspaceID,
		arg.ItemImageID,
		arg.WorkspaceID,
		arg.ItemImageID,
		arg.WorkspaceID,
		arg.ItemImageID,
		arg.WorkspaceID,
		arg.ItemImageID,
	)
	var database_bytes int64
	err := row.Scan(&database_bytes)
	return database_bytes, err
}

const getStorageQuotaUsage = `-- name: GetStorageQuotaUsage :one
SELECT
  workspace_id,
  upload_blob_bytes,
  database_bytes,
  item_count,
  image_count,
  reserved_upload_blob_bytes,
  reserved_database_bytes,
  reserved_item_count,
  reserved_image_count,
  updated_at
FROM storage_quota_usage
WHERE workspace_id = ?
`

func (q *Queries) GetStorageQuotaUsage(ctx context.Context, workspaceID uint64) (StorageQuotaUsage, error) {
	row := q.db.QueryRowContext(ctx, getStorageQuotaUsage, workspaceID)
	var i StorageQuotaUsage
	err := row.Scan(
		&i.WorkspaceID,
		&i.UploadBlobBytes,
		&i.DatabaseBytes,
		&i.ItemCount,
		&i.ImageCount,
		&i.ReservedUploadBlobBytes,
		&i.ReservedDatabaseBytes,
		&i.ReservedItemCount,
		&i.ReservedImageCount,
		&i.UpdatedAt,
	)
	return i, err
}

const insertStorageQuotaReservation = `-- name: InsertStorageQuotaReservation :exec
INSERT INTO workspace_storage_reservations (
  id,
  workspace_id,
  reserved_bytes,
  reserved_database_bytes,
  reserved_items,
  reserved_images,
  resource_key,
  expires_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
`

type InsertStorageQuotaReservationParams struct {
	ID                    string         `json:"id"`
	WorkspaceID           uint64         `json:"workspace_id"`
	ReservedBytes         uint64         `json:"reserved_bytes"`
	ReservedDatabaseBytes uint64         `json:"reserved_database_bytes"`
	ReservedItems         uint32         `json:"reserved_items"`
	ReservedImages        uint32         `json:"reserved_images"`
	ResourceKey           sql.NullString `json:"resource_key"`
	ExpiresAt             time.Time      `json:"expires_at"`
}

func (q *Queries) InsertStorageQuotaReservation(ctx context.Context, arg InsertStorageQuotaReservationParams) error {
	_, err := q.db.ExecContext(ctx, insertStorageQuotaReservation,
		arg.ID,
		arg.WorkspaceID,
		arg.ReservedBytes,
		arg.ReservedDatabaseBytes,
		arg.ReservedItems,
		arg.ReservedImages,
		arg.ResourceKey,
		arg.ExpiresAt,
	)
	return err
}

const lockAllTenantStorageQuotaUsage = `-- name: LockAllTenantStorageQuotaUsage :many
SELECT
  workspace_id,
  upload_blob_bytes,
  database_bytes,
  item_count,
  image_count,
  reserved_upload_blob_bytes,
  reserved_database_bytes,
  reserved_item_count,
  reserved_image_count,
  updated_at
FROM storage_quota_usage
WHERE workspace_id > 0
ORDER BY workspace_id
FOR UPDATE
`

// Rebuild is rare maintenance. This ordered locking read also locks the
// positive-key supremum gap, so a concurrently created workspace cannot add a
// quota row between the tenant snapshot and the final global lock.
func (q *Queries) LockAllTenantStorageQuotaUsage(ctx context.Context) ([]StorageQuotaUsage, error) {
	rows, err := q.db.QueryContext(ctx, lockAllTenantStorageQuotaUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageQuotaUsage{}
	for rows.Next() {
		var i StorageQuotaUsage
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UploadBlobBytes,
			&i.DatabaseBytes,
			&i.ItemCount,
			&i.ImageCount,
			&i.ReservedUploadBlobBytes,
			&i.ReservedDatabaseBytes,
			&i.ReservedItemCount,
			&i.ReservedImageCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExpiredStorageQuotaReservations = `-- name: LockExpiredStorageQuotaReservations :many
SELECT
  id,
  workspace_id,
  reserved_bytes,
  reserved_database_bytes,
  reserved_items,
  reserved_images,
  resource_key,
  expires_at,
  created_at
FROM workspace_storage_reservations
WHERE workspace_id = ?
  AND expires_at <= ?
ORDER BY expires_at, id
LIMIT ?
FOR UPDATE SKIP LOCKED
`

type LockExpiredStorageQuotaReservationsParams struct {
	WorkspaceID uint64    `json:"workspace_id"`
	ExpiresAt   time.Time `json:"expires_at"`
	Limit       int32     `json:"limit"`
}

func (q *Queries) LockExpiredStorageQuotaReservations(ctx context.Context, arg LockExpiredStorageQuotaReservationsParams) ([]WorkspaceStorageReservation, error) {
	rows, err := q.db.QueryContext(ctx, lockExpiredStorageQuotaReservations, arg.WorkspaceID, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceStorageReservation{}
	for rows.Next() {
		var i WorkspaceStorageReservation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ReservedBytes,
			&i.ReservedDatabaseBytes,
			&i.ReservedItems,
			&i.ReservedImages,
			&i.ResourceKey,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLiveStorageQuotaReservation = `-- name: LockLiveStorageQuotaReservation :one
SELECT
  id,
  workspace_id,
  reserved_bytes,
  reserved_database_bytes,
  reserved_items,
  reserved_images,
  resource_key,
  expires_at,
  created_at
FROM workspace_storage_reservations
WHERE id = ?
  AND workspace_id = ?
  AND expires_at > NOW(6)
FOR UPDATE
`

type LockLiveStorageQuotaReservationParams struct {
	ID          string `json:"id"`
	WorkspaceID uint64 `json:"workspace_id"`
}

func (q *Queries) LockLiveStorageQuotaReservation(ctx context.Context, arg LockLiveStorageQuotaReservationParams) (WorkspaceStorageReservation, error) {
	row := q.db.QueryRowContext(ctx, lockLiveStorageQuotaReservation, arg.ID, arg.WorkspaceID)
	var i WorkspaceStorageReservation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ReservedBytes,
		&i.ReservedDatabaseBytes,
		&i.ReservedItems,
		&i.ReservedImages,
		&i.ResourceKey,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const lockStorageQuotaReservation = `-- name: LockStorageQuotaReservation :one
SELECT
  id,
  workspace_id,
  reserved_bytes,
  reserved_database_bytes,
  reserved_items,
  reserved_images,
  resource_key,
  expires_at,
  created_at
FROM workspace_storage_reservations
WHERE id = ?
  AND workspace_id = ?
FOR UPDATE
`

type LockStorageQuotaReservationParams struct {
	ID          string `json:"id"`
	WorkspaceID uint64 `json:"workspace_id"`
}

func (q *Queries) LockStorageQuotaReservation(ctx context.Context, arg LockStorageQuotaReservationParams) (WorkspaceStorageReservation, error) {
	row := q.db.QueryRowContext(ctx, lockStorageQuotaReservation, arg.ID, arg.WorkspaceID)
	var i WorkspaceStorageReservation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ReservedBytes,
		&i.ReservedDatabaseBytes,
		&i.ReservedItems,
		&i.ReservedImages,
		&i.ResourceKey,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const lockStorageQuotaSweepWorkspace = `-- name: LockStorageQuotaSweepWorkspace :one
SELECT quota_row.workspace_id
FROM storage_quota_usage quota_row
WHERE quota_row.workspace_id <> 0
  AND EXISTS (
    SELECT 1
    FROM workspace_storage_reservations reservation
    WHERE reservation.workspace_id = quota_row.workspace_id
      AND reservation.expires_at <= ?
  )
ORDER BY quota_row.workspace_id
LIMIT 1
FOR UPDATE SKIP LOCKED
`

// Expiry only makes a reservation eligible for cleanup. Admission continues
// to count it until this locking read owns the row and the sweeper removes it.
// Active aggregate transactions hold the reservation lock and are skipped.
func (q *Queries) LockStorageQuotaSweepWorkspace(ctx context.Context, expiresAt time.Time) (uint64, error) {
	row := q.db.QueryRowContext(ctx, lockStorageQuotaSweepWorkspace, expiresAt)
	var workspace_id uint64
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const lockStorageQuotaUsage = `-- name: LockStorageQuotaUsage :one
SELECT
  workspace_id,
  upload_blob_bytes,
  database_bytes,
  item_count,
  image_count,
  reserved_upload_blob_bytes,
  reserved_database_bytes,
  reserved_item_count,
  reserved_image_count,
  updated_at
FROM storage_quota_usage
WHERE workspace_id = ?
FOR UPDATE
`

func (q *Queries) LockStorageQuotaUsage(ctx context.Context, workspaceID uint64) (StorageQuotaUsage, error) {
	row := q.db.QueryRowContext(ctx, lockStorageQuotaUsage, workspaceID)
	var i StorageQuotaUsage
	err := row.Scan(
		&i.WorkspaceID,
		&i.UploadBlobBytes,
		&i.DatabaseBytes,
		&i.ItemCount,
		&i.ImageCount,
		&i.ReservedUploadBlobBytes,
		&i.ReservedDatabaseBytes,
		&i.ReservedItemCount,
		&i.ReservedImageCount,
		&i.UpdatedAt,
	)
	return i, err
}

const rebuildStorageQuotaUsageRows = `-- name: RebuildStorageQuotaUsageRows :many
SELECT
  w.id AS workspace_id,
  CAST((SELECT COUNT(*) FROM items i WHERE i.workspace_id = w.id) AS UNSIGNED) AS item_count,
  CAST((SELECT COUNT(*) FROM item_images ii JOIN items i ON i.id = ii.item_id WHERE i.workspace_id = w.id) AS UNSIGNED) AS image_count,
  CAST((
    SELECT COALESCE(SUM(accounted.storage_bytes), 0)
    FROM (
      SELECT candidates.workspace_id, candidates.resource_key, MAX(candidates.storage_bytes) AS storage_bytes
      FROM (
        SELECT
          i.workspace_id,
          SUBSTRING(ii.image_url, CHAR_LENGTH('/static/uploads/') + 1) AS resource_key,
          ii.storage_bytes
        FROM item_images ii
        JOIN items i ON i.id = ii.item_id
        WHERE ii.image_url LIKE '/static/uploads/%'
        UNION ALL
        SELECT workspace_id, resource_key, storage_bytes
        FROM resource_cleanup_outbox
        WHERE kind = 'upload_blob' AND storage_bytes > 0
      ) candidates
      GROUP BY candidates.workspace_id, candidates.resource_key
    ) accounted
    WHERE accounted.workspace_id = w.id
  ) AS UNSIGNED) AS upload_blob_bytes,
  CAST((
    SELECT
      COALESCE(SUM(OCTET_LENGTH(orun.original_hocr) + OCTET_LENGTH(orun.original_text)), 0)
    FROM ocr_runs orun
    JOIN item_images ii ON ii.id = orun.item_image_id
    JOIN items i ON i.id = ii.item_id
    WHERE i.workspace_id = w.id
  ) + (
    SELECT COALESCE(SUM(OCTET_LENGTH(ap.payload)), 0)
    FROM annotation_pages ap
    WHERE ap.workspace_id = w.id
  ) + (
    SELECT COALESCE(SUM(OCTET_LENGTH(a.payload)), 0)
    FROM annotations a
    WHERE a.workspace_id = w.id
  ) + (
    SELECT COALESCE(SUM(OCTET_LENGTH(pap.payload)), 0)
    FROM published_annotation_pages pap
    WHERE pap.workspace_id = w.id
  ) + (
    SELECT COALESCE(SUM(OCTET_LENGTH(i.source_manifest)), 0)
    FROM items i
    WHERE i.workspace_id = w.id
  ) + (
    SELECT COALESCE(SUM(pca.database_bytes), 0)
    FROM provider_call_audits pca
    WHERE pca.workspace_id = w.id
  ) AS UNSIGNED) AS database_bytes,
  CAST((
    SELECT COALESCE(SUM(r.reserved_bytes), 0)
    FROM workspace_storage_reservations r
    WHERE r.workspace_id = w.id
  ) AS UNSIGNED) AS reserved_upload_blob_bytes,
  CAST((
    SELECT COALESCE(SUM(r.reserved_database_bytes), 0)
    FROM workspace_storage_reservations r
    WHERE r.workspace_id = w.id
  ) AS UNSIGNED) AS reserved_database_bytes,
  CAST((
    SELECT COALESCE(SUM(r.reserved_items), 0)
    FROM workspace_storage_reservations r
    WHERE r.workspace_id = w.id
  ) AS UNSIGNED) AS reserved_item_count,
  CAST((
    SELECT COALESCE(SUM(r.reserved_images), 0)
    FROM workspace_storage_reservations r
    WHERE r.workspace_id = w.id
  ) AS UNSIGNED) AS reserved_image_count
FROM (
  SELECT id
  FROM workspaces
  UNION
  SELECT workspace_id AS id
  FROM workspace_storage_reservations
  UNION
  SELECT workspace_id AS id
  FROM resource_cleanup_outbox
  WHERE workspace_id > 0
) w
ORDER BY w.id
`

type RebuildStorageQuotaUsageRowsRow struct {
	WorkspaceID             uint64 `json:"workspace_id"`
	ItemCount               int64  `json:"item_count"`
	ImageCount              int64  `json:"image_count"`
	UploadBlobBytes         int64  `json:"upload_blob_bytes"`
	DatabaseBytes           int64  `json:"database_bytes"`
	ReservedUploadBlobBytes int64  `json:"reserved_upload_blob_bytes"`
	ReservedDatabaseBytes   int64  `json:"reserved_database_bytes"`
	ReservedItemCount       int64  `json:"reserved_item_count"`
	ReservedImageCount      int64  `json:"reserved_image_count"`
}

func (q *Queries) RebuildStorageQuotaUsageRows(ctx context.Context) ([]RebuildStorageQuotaUsageRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, rebuildStorageQuotaUsageRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RebuildStorageQuotaUsageRowsRow{}
	for rows.Next() {
		var i RebuildStorageQuotaUsageRowsRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ItemCount,
			&i.ImageCount,
			&i.UploadBlobBytes,
			&i.DatabaseBytes,
			&i.ReservedUploadBlobBytes,
			&i.ReservedDatabaseBytes,
			&i.ReservedItemCount,
			&i.ReservedImageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceStorageQuotaUsage = `-- name: ReplaceStorageQuotaUsage :exec
INSERT INTO storage_quota_usage (
  workspace_id,
  upload_blob_bytes,
  database_bytes,
  item_count,
  image_count,
  reserved_upload_blob_bytes,
  reserved_database_bytes,
  reserved_item_count,
  reserved_image_count
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
ON DUPLICATE KEY UPDATE
  upload_blob_bytes = VALUES(upload_blob_bytes),
  database_bytes = VALUES(database_bytes),
  item_count = VALUES(item_count),
  image_count = VALUES(image_count),
  reserved_upload_blob_bytes = VALUES(reserved_upload_blob_bytes),
  reserved_database_bytes = VALUES(reserved_database_bytes),
  reserved_item_count = VALUES(reserved_item_count),
  reserved_image_count = VALUES(reserved_image_count)
`

type ReplaceStorageQuotaUsageParams struct {
	WorkspaceID             uint64 `json:"workspace_id"`
	UploadBlobBytes         uint64 `json:"upload_blob_bytes"`
	DatabaseBytes           uint64 `json:"database_bytes"`
	ItemCount               uint64 `json:"item_count"`
	ImageCount              uint64 `json:"image_count"`
	ReservedUploadBlobBytes uint64 `json:"reserved_upload_blob_bytes"`
	ReservedDatabaseBytes   uint64 `json:"reserved_database_bytes"`
	ReservedItemCount       uint64 `json:"reserved_item_count"`
	ReservedImageCount      uint64 `json:"reserved_image_count"`
}

func (q *Queries) ReplaceStorageQuotaUsage(ctx context.Context, arg ReplaceStorageQuotaUsageParams) error {
	_, err := q.db.ExecContext(ctx, replaceStorageQuotaUsage,
		arg.WorkspaceID,
		arg.UploadBlobBytes,
		arg.DatabaseBytes,
		arg.ItemCount,
		arg.ImageCount,
		arg.ReservedUploadBlobBytes,
		arg.ReservedDatabaseBytes,
		arg.ReservedItemCount,
		arg.ReservedImageCount,
	)
	return err
}

const subtractStorageQuotaReserved = `-- name: SubtractStorageQuotaReserved :execresult
UPDATE storage_quota_usage
SET
  reserved_upload_blob_bytes = reserved_upload_blob_bytes - ?,
  reserved_database_bytes = reserved_database_bytes - ?,
  reserved_item_count = reserved_item_count - ?,
  reserved_image_count = reserved_image_count - ?
WHERE workspace_id IN (0, ?)
  AND reserved_upload_blob_bytes >= ?
  AND reserved_database_bytes >= ?
  AND reserved_item_count >= ?
  AND reserved_image_count >= ?
`

type SubtractStorageQuotaReservedParams struct {
	UploadBlobBytes uint64 `json:"upload_blob_bytes"`
	DatabaseBytes   uint64 `json:"database_bytes"`
	ItemCount       uint64 `json:"item_count"`
	ImageCount      uint64 `json:"image_count"`
	WorkspaceID     uint64 `json:"workspace_id"`
}

func (q *Queries) SubtractStorageQuotaReserved(ctx context.Context, arg SubtractStorageQuotaReservedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, subtractStorageQuotaReserved,
		arg.UploadBlobBytes,
		arg.DatabaseBytes,
		arg.ItemCount,
		arg.ImageCount,
		arg.WorkspaceID,
		arg.UploadBlobBytes,
		arg.DatabaseBytes,
		arg.ItemCount,
		arg.ImageCount,
	)
}

const subtractStorageQuotaUsed = `-- name: SubtractStorageQuotaUsed :execresult
UPDATE storage_quota_usage
SET
  upload_blob_bytes = upload_blob_bytes - ?,
  database_bytes = database_bytes - ?,
  item_count = item_count - ?,
  image_count = image_count - ?
WHERE workspace_id IN (0, ?)
  AND upload_blob_bytes >= ?
  AND database_bytes >= ?
  AND item_count >= ?
  AND image_count >= ?
`

type SubtractStorageQuotaUsedParams struct {
	UploadBlobBytes uint64 `json:"upload_blob_bytes"`
	DatabaseBytes   uint64 `json:"database_bytes"`
	ItemCount       uint64 `json:"item_count"`
	ImageCount      uint64 `json:"image_count"`
	WorkspaceID     uint64 `json:"workspace_id"`
}

func (q *Queries) SubtractStorageQuotaUsed(ctx context.Context, arg SubtractStorageQuotaUsedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, subtractStorageQuotaUsed,
		arg.UploadBlobBytes,
		arg.DatabaseBytes,
		arg.ItemCount,
		arg.ImageCount,
		arg.WorkspaceID,
		arg.UploadBlobBytes,
		arg.DatabaseBytes,
		arg.ItemCount,
		arg.ImageCount,
	)
}

const updateStorageQuotaReservation = `-- name: UpdateStorageQuotaReservation :execresult
UPDATE workspace_storage_reservations
SET
  reserved_bytes = ?,
  reserved_database_bytes = ?,
  reserved_items = ?,
  reserved_images = ?,
  resource_key = ?,
  expires_at = ?
WHERE id = ?
  AND workspace_id = ?
`

type UpdateStorageQuotaReservationParams struct {
	ReservedBytes         uint64         `json:"reserved_bytes"`
	ReservedDatabaseBytes uint64         `json:"reserved_database_bytes"`
	ReservedItems         uint32         `json:"reserved_items"`
	ReservedImages        uint32         `json:"reserved_images"`
	ResourceKey           sql.NullString `json:"resource_key"`
	ExpiresAt             time.Time      `json:"expires_at"`
	ID                    string         `json:"id"`
	WorkspaceID           uint64         `json:"workspace_id"`
}

func (q *Queries) UpdateStorageQuotaReservation(ctx context.Context, arg UpdateStorageQuotaReservationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateStorageQuotaReservation,
		arg.ReservedBytes,
		arg.ReservedDatabaseBytes,
		arg.ReservedItems,
		arg.ReservedImages,
		arg.ResourceKey,
		arg.ExpiresAt,
		arg.ID,
		arg.WorkspaceID,
	)
}
