// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcription_job_leases.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const claimLeasedTranscriptionJobByIDManual = `-- name: ClaimLeasedTranscriptionJobByIDManual :one
SELECT
  id,
  item_image_id,
  context_id,
  status,
  total_segments,
  completed_segments,
  failed_segments,
  attempt_count,
  max_attempts,
  retry_after,
  lease_until,
  locked_by,
  current_annotation_id,
  current_annotation_json,
  last_result_annotation_json,
  error_message,
  created_at,
  updated_at
FROM transcription_jobs
WHERE id = ?
  AND (
    (
      status = 'pending'
      AND (retry_after IS NULL OR retry_after <= NOW())
    ) OR (
      status = 'running'
      AND lease_until IS NOT NULL
      AND lease_until < NOW()
      AND attempt_count < max_attempts
    )
  )
LIMIT 1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimLeasedTranscriptionJobByIDManual(ctx context.Context, id uint64) (TranscriptionJob, error) {
	row := q.db.QueryRowContext(ctx, claimLeasedTranscriptionJobByIDManual, id)
	var i TranscriptionJob
	err := row.Scan(
		&i.ID,
		&i.ItemImageID,
		&i.ContextID,
		&i.Status,
		&i.TotalSegments,
		&i.CompletedSegments,
		&i.FailedSegments,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.RetryAfter,
		&i.LeaseUntil,
		&i.LockedBy,
		&i.CurrentAnnotationID,
		&i.CurrentAnnotationJson,
		&i.LastResultAnnotationJson,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimNextLeasedTranscriptionJobManual = `-- name: ClaimNextLeasedTranscriptionJobManual :one
SELECT
  id,
  item_image_id,
  context_id,
  status,
  total_segments,
  completed_segments,
  failed_segments,
  attempt_count,
  max_attempts,
  retry_after,
  lease_until,
  locked_by,
  current_annotation_id,
  current_annotation_json,
  last_result_annotation_json,
  error_message,
  created_at,
  updated_at
FROM transcription_jobs
WHERE (
    status = 'pending'
    AND (retry_after IS NULL OR retry_after <= NOW())
  ) OR (
    status = 'running'
    AND lease_until IS NOT NULL
    AND lease_until < NOW()
    AND attempt_count < max_attempts
  )
ORDER BY created_at ASC
LIMIT 1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimNextLeasedTranscriptionJobManual(ctx context.Context) (TranscriptionJob, error) {
	row := q.db.QueryRowContext(ctx, claimNextLeasedTranscriptionJobManual)
	var i TranscriptionJob
	err := row.Scan(
		&i.ID,
		&i.ItemImageID,
		&i.ContextID,
		&i.Status,
		&i.TotalSegments,
		&i.CompletedSegments,
		&i.FailedSegments,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.RetryAfter,
		&i.LeaseUntil,
		&i.LockedBy,
		&i.CurrentAnnotationID,
		&i.CurrentAnnotationJson,
		&i.LastResultAnnotationJson,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimNextLeasedTranscriptionJobOlderThanManual = `-- name: ClaimNextLeasedTranscriptionJobOlderThanManual :one
SELECT
  id,
  item_image_id,
  context_id,
  status,
  total_segments,
  completed_segments,
  failed_segments,
  attempt_count,
  max_attempts,
  retry_after,
  lease_until,
  locked_by,
  current_annotation_id,
  current_annotation_json,
  last_result_annotation_json,
  error_message,
  created_at,
  updated_at
FROM transcription_jobs
WHERE created_at < ?
  AND (
    (
      status = 'pending'
      AND (retry_after IS NULL OR retry_after <= NOW())
    ) OR (
      status = 'running'
      AND lease_until IS NOT NULL
      AND lease_until < NOW()
      AND attempt_count < max_attempts
    )
  )
ORDER BY created_at ASC
LIMIT 1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimNextLeasedTranscriptionJobOlderThanManual(ctx context.Context, cutoff time.Time) (TranscriptionJob, error) {
	row := q.db.QueryRowContext(ctx, claimNextLeasedTranscriptionJobOlderThanManual, cutoff)
	var i TranscriptionJob
	err := row.Scan(
		&i.ID,
		&i.ItemImageID,
		&i.ContextID,
		&i.Status,
		&i.TotalSegments,
		&i.CompletedSegments,
		&i.FailedSegments,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.RetryAfter,
		&i.LeaseUntil,
		&i.LockedBy,
		&i.CurrentAnnotationID,
		&i.CurrentAnnotationJson,
		&i.LastResultAnnotationJson,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeTranscriptionJobLeasedManual = `-- name: CompleteTranscriptionJobLeasedManual :execresult
UPDATE transcription_jobs
SET
  status = 'completed',
  current_annotation_id = NULL,
  current_annotation_json = NULL,
  lease_until = NULL,
  locked_by = NULL,
  updated_at = NOW()
WHERE id = ?
  AND locked_by = ?
  AND status = 'running'
`

type CompleteTranscriptionJobLeasedManualParams struct {
	ID       uint64         `json:"id"`
	LockedBy sql.NullString `json:"locked_by"`
}

func (q *Queries) CompleteTranscriptionJobLeasedManual(ctx context.Context, arg CompleteTranscriptionJobLeasedManualParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, completeTranscriptionJobLeasedManual, arg.ID, arg.LockedBy)
}

const deferTranscriptionJobLeaseManual = `-- name: DeferTranscriptionJobLeaseManual :execresult
UPDATE transcription_jobs
SET
  status = 'pending',
  retry_after = ?,
  error_message = ?,
  current_annotation_id = NULL,
  current_annotation_json = NULL,
  lease_until = NULL,
  locked_by = NULL,
  updated_at = NOW()
WHERE id = ?
  AND locked_by = ?
  AND status = 'running'
`

type DeferTranscriptionJobLeaseManualParams struct {
	RetryAfter   sql.NullTime   `json:"retry_after"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           uint64         `json:"id"`
	LockedBy     sql.NullString `json:"locked_by"`
}

func (q *Queries) DeferTranscriptionJobLeaseManual(ctx context.Context, arg DeferTranscriptionJobLeaseManualParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deferTranscriptionJobLeaseManual,
		arg.RetryAfter,
		arg.ErrorMessage,
		arg.ID,
		arg.LockedBy,
	)
}

const extendTranscriptionJobLeaseManual = `-- name: ExtendTranscriptionJobLeaseManual :execresult
UPDATE transcription_jobs
SET
  lease_until = ?,
  updated_at = NOW()
WHERE id = ?
  AND locked_by = ?
  AND status = 'running'
`

type ExtendTranscriptionJobLeaseManualParams struct {
	LeaseUntil sql.NullTime   `json:"lease_until"`
	ID         uint64         `json:"id"`
	LockedBy   sql.NullString `json:"locked_by"`
}

func (q *Queries) ExtendTranscriptionJobLeaseManual(ctx context.Context, arg ExtendTranscriptionJobLeaseManualParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, extendTranscriptionJobLeaseManual, arg.LeaseUntil, arg.ID, arg.LockedBy)
}

const markTranscriptionJobLeasedManual = `-- name: MarkTranscriptionJobLeasedManual :execresult
UPDATE transcription_jobs
SET
  status = 'running',
  attempt_count = attempt_count + 1,
  lease_until = ?,
  locked_by = ?,
  updated_at = NOW()
WHERE id = ?
  AND (
    (
      status = 'pending'
      AND (retry_after IS NULL OR retry_after <= NOW())
    ) OR (
      status = 'running'
      AND lease_until IS NOT NULL
      AND lease_until < NOW()
      AND attempt_count < max_attempts
    )
  )
`

type MarkTranscriptionJobLeasedManualParams struct {
	LeaseUntil sql.NullTime   `json:"lease_until"`
	LockedBy   sql.NullString `json:"locked_by"`
	ID         uint64         `json:"id"`
}

func (q *Queries) MarkTranscriptionJobLeasedManual(ctx context.Context, arg MarkTranscriptionJobLeasedManualParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markTranscriptionJobLeasedManual, arg.LeaseUntil, arg.LockedBy, arg.ID)
}

const retryOrFailTranscriptionJobManual = `-- name: RetryOrFailTranscriptionJobManual :execresult
UPDATE transcription_jobs
SET
  status = CASE WHEN attempt_count < max_attempts THEN 'pending' ELSE 'failed' END,
  retry_after = CASE WHEN attempt_count < max_attempts THEN DATE_ADD(NOW(), INTERVAL LEAST(300, POW(2, attempt_count) * 10) SECOND) ELSE NULL END,
  error_message = ?,
  current_annotation_id = NULL,
  current_annotation_json = NULL,
  lease_until = NULL,
  locked_by = NULL,
  updated_at = NOW()
WHERE id = ?
  AND locked_by = ?
  AND status = 'running'
`

type RetryOrFailTranscriptionJobManualParams struct {
	ErrorMessage sql.NullString `json:"error_message"`
	ID           uint64         `json:"id"`
	LockedBy     sql.NullString `json:"locked_by"`
}

func (q *Queries) RetryOrFailTranscriptionJobManual(ctx context.Context, arg RetryOrFailTranscriptionJobManualParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, retryOrFailTranscriptionJobManual, arg.ErrorMessage, arg.ID, arg.LockedBy)
}
