// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transcription_jobs.sql

package db

import (
	"context"
	"database/sql"
)

const claimNextPendingTranscriptionJobManual = `-- name: ClaimNextPendingTranscriptionJobManual :one
SELECT
  id,
  item_image_id,
  context_id,
  status,
  total_segments,
  completed_segments,
  failed_segments,
  current_annotation_id,
  current_annotation_json,
  last_result_annotation_json,
  error_message,
  created_at,
  updated_at
FROM transcription_jobs
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT 1
FOR UPDATE
`

func (q *Queries) ClaimNextPendingTranscriptionJobManual(ctx context.Context) (TranscriptionJob, error) {
	row := q.db.QueryRowContext(ctx, claimNextPendingTranscriptionJobManual)
	var i TranscriptionJob
	err := row.Scan(
		&i.ID,
		&i.ItemImageID,
		&i.ContextID,
		&i.Status,
		&i.TotalSegments,
		&i.CompletedSegments,
		&i.FailedSegments,
		&i.CurrentAnnotationID,
		&i.CurrentAnnotationJson,
		&i.LastResultAnnotationJson,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeTranscriptionJobManual = `-- name: CompleteTranscriptionJobManual :exec
UPDATE transcription_jobs
SET
  status = 'completed',
  current_annotation_id = NULL,
  current_annotation_json = NULL,
  updated_at = NOW()
WHERE id = ?
`

func (q *Queries) CompleteTranscriptionJobManual(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, completeTranscriptionJobManual, id)
	return err
}

const createTranscriptionJobManual = `-- name: CreateTranscriptionJobManual :execresult
INSERT INTO transcription_jobs (
  item_image_id,
  context_id,
  status
) VALUES (
  ?,
  ?,
  'pending'
)
`

type CreateTranscriptionJobManualParams struct {
	ItemImageID uint64        `json:"item_image_id"`
	ContextID   sql.NullInt64 `json:"context_id"`
}

func (q *Queries) CreateTranscriptionJobManual(ctx context.Context, arg CreateTranscriptionJobManualParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTranscriptionJobManual, arg.ItemImageID, arg.ContextID)
}

const failTranscriptionJobManual = `-- name: FailTranscriptionJobManual :exec
UPDATE transcription_jobs
SET
  status = 'failed',
  error_message = ?,
  current_annotation_id = NULL,
  current_annotation_json = NULL,
  updated_at = NOW()
WHERE id = ?
`

type FailTranscriptionJobManualParams struct {
	ErrorMessage sql.NullString `json:"error_message"`
	ID           uint64         `json:"id"`
}

func (q *Queries) FailTranscriptionJobManual(ctx context.Context, arg FailTranscriptionJobManualParams) error {
	_, err := q.db.ExecContext(ctx, failTranscriptionJobManual, arg.ErrorMessage, arg.ID)
	return err
}

const getTranscriptionJobManual = `-- name: GetTranscriptionJobManual :one
SELECT
  id,
  item_image_id,
  context_id,
  status,
  total_segments,
  completed_segments,
  failed_segments,
  current_annotation_id,
  current_annotation_json,
  last_result_annotation_json,
  error_message,
  created_at,
  updated_at
FROM transcription_jobs
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTranscriptionJobManual(ctx context.Context, id uint64) (TranscriptionJob, error) {
	row := q.db.QueryRowContext(ctx, getTranscriptionJobManual, id)
	var i TranscriptionJob
	err := row.Scan(
		&i.ID,
		&i.ItemImageID,
		&i.ContextID,
		&i.Status,
		&i.TotalSegments,
		&i.CompletedSegments,
		&i.FailedSegments,
		&i.CurrentAnnotationID,
		&i.CurrentAnnotationJson,
		&i.LastResultAnnotationJson,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTranscriptionJobsByItemImageManual = `-- name: ListTranscriptionJobsByItemImageManual :many
SELECT
  id,
  item_image_id,
  context_id,
  status,
  total_segments,
  completed_segments,
  failed_segments,
  current_annotation_id,
  current_annotation_json,
  last_result_annotation_json,
  error_message,
  created_at,
  updated_at
FROM transcription_jobs
WHERE item_image_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListTranscriptionJobsByItemImageManual(ctx context.Context, itemImageID uint64) ([]TranscriptionJob, error) {
	rows, err := q.db.QueryContext(ctx, listTranscriptionJobsByItemImageManual, itemImageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscriptionJob{}
	for rows.Next() {
		var i TranscriptionJob
		if err := rows.Scan(
			&i.ID,
			&i.ItemImageID,
			&i.ContextID,
			&i.Status,
			&i.TotalSegments,
			&i.CompletedSegments,
			&i.FailedSegments,
			&i.CurrentAnnotationID,
			&i.CurrentAnnotationJson,
			&i.LastResultAnnotationJson,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptionJobsByWorkspaceManual = `-- name: ListTranscriptionJobsByWorkspaceManual :many
SELECT
  tj.id,
  tj.item_image_id,
  tj.context_id,
  tj.status,
  tj.total_segments,
  tj.completed_segments,
  tj.failed_segments,
  tj.current_annotation_id,
  tj.current_annotation_json,
  tj.last_result_annotation_json,
  tj.error_message,
  tj.created_at,
  tj.updated_at
FROM transcription_jobs tj
JOIN item_images ii ON ii.id = tj.item_image_id
JOIN items i ON i.id = ii.item_id
WHERE i.workspace_id = ?
ORDER BY tj.created_at DESC
`

func (q *Queries) ListTranscriptionJobsByWorkspaceManual(ctx context.Context, workspaceID uint64) ([]TranscriptionJob, error) {
	rows, err := q.db.QueryContext(ctx, listTranscriptionJobsByWorkspaceManual, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscriptionJob{}
	for rows.Next() {
		var i TranscriptionJob
		if err := rows.Scan(
			&i.ID,
			&i.ItemImageID,
			&i.ContextID,
			&i.Status,
			&i.TotalSegments,
			&i.CompletedSegments,
			&i.FailedSegments,
			&i.CurrentAnnotationID,
			&i.CurrentAnnotationJson,
			&i.LastResultAnnotationJson,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTranscriptionJobRunningManual = `-- name: MarkTranscriptionJobRunningManual :exec
UPDATE transcription_jobs
SET
  status = 'running',
  updated_at = NOW()
WHERE id = ?
`

func (q *Queries) MarkTranscriptionJobRunningManual(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, markTranscriptionJobRunningManual, id)
	return err
}

const setTranscriptionJobTotalSegmentsManual = `-- name: SetTranscriptionJobTotalSegmentsManual :exec
UPDATE transcription_jobs
SET
  total_segments = ?,
  updated_at = NOW()
WHERE id = ?
`

type SetTranscriptionJobTotalSegmentsManualParams struct {
	TotalSegments int32  `json:"total_segments"`
	ID            uint64 `json:"id"`
}

func (q *Queries) SetTranscriptionJobTotalSegmentsManual(ctx context.Context, arg SetTranscriptionJobTotalSegmentsManualParams) error {
	_, err := q.db.ExecContext(ctx, setTranscriptionJobTotalSegmentsManual, arg.TotalSegments, arg.ID)
	return err
}

const updateTranscriptionJobProgressManual = `-- name: UpdateTranscriptionJobProgressManual :exec
UPDATE transcription_jobs
SET
  completed_segments = ?,
  failed_segments = ?,
  current_annotation_id = ?,
  current_annotation_json = ?,
  last_result_annotation_json = ?,
  updated_at = NOW()
WHERE id = ?
`

type UpdateTranscriptionJobProgressManualParams struct {
	CompletedSegments        int32          `json:"completed_segments"`
	FailedSegments           int32          `json:"failed_segments"`
	CurrentAnnotationID      sql.NullString `json:"current_annotation_id"`
	CurrentAnnotationJson    sql.NullString `json:"current_annotation_json"`
	LastResultAnnotationJson sql.NullString `json:"last_result_annotation_json"`
	ID                       uint64         `json:"id"`
}

func (q *Queries) UpdateTranscriptionJobProgressManual(ctx context.Context, arg UpdateTranscriptionJobProgressManualParams) error {
	_, err := q.db.ExecContext(ctx, updateTranscriptionJobProgressManual,
		arg.CompletedSegments,
		arg.FailedSegments,
		arg.CurrentAnnotationID,
		arg.CurrentAnnotationJson,
		arg.LastResultAnnotationJson,
		arg.ID,
	)
	return err
}

const workspaceOwnsTranscriptionJobManual = `-- name: WorkspaceOwnsTranscriptionJobManual :one
SELECT EXISTS(
  SELECT 1
  FROM transcription_jobs tj
  JOIN item_images ii ON ii.id = tj.item_image_id
  JOIN items i ON i.id = ii.item_id
  WHERE tj.id = ?
    AND i.workspace_id = ?
) AS owns_job
`

type WorkspaceOwnsTranscriptionJobManualParams struct {
	JobID       uint64 `json:"job_id"`
	WorkspaceID uint64 `json:"workspace_id"`
}

func (q *Queries) WorkspaceOwnsTranscriptionJobManual(ctx context.Context, arg WorkspaceOwnsTranscriptionJobManualParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, workspaceOwnsTranscriptionJobManual, arg.JobID, arg.WorkspaceID)
	var owns_job bool
	err := row.Scan(&owns_job)
	return owns_job, err
}
