name: Terraform Apply

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint-test:
    uses: ./.github/workflows/lint-test.yaml
    permissions:
      contents: read
    secrets: inherit

  build-push-image:
    needs: [lint-test]
    uses: ./.github/workflows/build-push-image.yaml
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      checkout_ref: ${{ github.sha }}
      image_tag: ghcr.io/${{ github.repository }}:main
      extra_image_tag: ghcr.io/${{ github.repository }}:main-${{ github.sha }}

  terraform-apply:
    needs: [build-push-image]
    uses: ./.github/workflows/terraform-deploy.yaml
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    with:
      mode: apply
      environment_name: production
      tf_workspace: prod
      site_name: scribe
      docker_compose_branch: main
      checkout_ref: ${{ github.sha }}
      run_snapshots: "true"
      push_image: false
      image_tag: ${{ needs.build-push-image.outputs.image }}
